#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CreatureType {
    Advisor,
    Aetherborn,
    Alien,
    Ally,
    Angel,
    Antelope,
    Ape,
    Archer,
    Archon,
    Armadillo,
    Army,
    Artifact,
    Artificer,
    Assassin,
    AssemblyWorker,
    Astartes,
    Atog,
    Aurochs,
    Automaton,
    Avatar,
    Azra,
    Badger,
    Balloon,
    Barbarian,
    Bard,
    Basilisk,
    Bat,
    Bear,
    Beast,
    Beaver,
    Beeble,
    Beholder,
    Berserker,
    Bird,
    Bison,
    Blinkmoth,
    Boar,
    Brainiac,
    Bringer,
    Brushwagg,
    Ctan,
    Camarid,
    Camel,
    Capybara,
    Caribou,
    Carrier,
    Cat,
    Centaur,
    Chicken,
    Child,
    Chimera,
    Citizen,
    Cleric,
    Clown,
    Cockatrice,
    Construct,
    Coward,
    Coyote,
    Crab,
    Crocodile,
    Custodes,
    Cyberman,
    Cyclops,
    Dalek,
    Dauthi,
    Demigod,
    Demon,
    Deserter,
    Detective,
    Devil,
    Dinosaur,
    Djinn,
    Doctor,
    Dog,
    Dragon,
    Drake,
    Dreadnought,
    Drix,
    Drone,
    Druid,
    Dryad,
    Dwarf,
    Echidna,
    Efreet,
    Egg,
    Elder,
    Eldrazi,
    Elemental,
    Elephant,
    Elf,
    Elk,
    Employee,
    Eye,
    Faerie,
    Ferret,
    Fish,
    Flagbearer,
    Fox,
    Fractal,
    Frog,
    Fungus,
    Gamer,
    Gargoyle,
    Germ,
    Giant,
    Gith,
    Glimmer,
    Gnoll,
    Gnome,
    Goat,
    Goblin,
    God,
    Golem,
    Gorgon,
    Graveborn,
    Gremlin,
    Griffin,
    Guest,
    Hag,
    Halfling,
    Hamster,
    Harpy,
    Head,
    Hedgehog,
    Hellion,
    Hero,
    Hippo,
    Hippogriff,
    Homarid,
    Homunculus,
    Hornet,
    Horror,
    Horse,
    Human,
    Hydra,
    Hyena,
    Illusion,
    Imp,
    Incarnation,
    Inkling,
    Inquisitor,
    Insect,
    Jackal,
    Jellyfish,
    Juggernaut,
    Kangaroo,
    Kavu,
    Kirin,
    Kithkin,
    Knight,
    Kobold,
    Kor,
    Kraken,
    Lamia,
    Lammasu,
    Leech,
    Lemur,
    Leviathan,
    Lhurgoyf,
    Licid,
    Lizard,
    Lobster,
    Manticore,
    Masticore,
    Mercenary,
    Merfolk,
    Metathran,
    Minion,
    Minotaur,
    Mite,
    Mole,
    Monger,
    Mongoose,
    Monk,
    Monkey,
    Moogle,
    Moonfolk,
    Mount,
    Mouse,
    Mutant,
    Myr,
    Mystic,
    Naga,
    Nautilus,
    Necron,
    Nephilim,
    Nightmare,
    Nightstalker,
    Ninja,
    Noble,
    Noggle,
    Nomad,
    Nymph,
    Octopus,
    Ogre,
    Ooze,
    Orb,
    Orc,
    Orgg,
    Otter,
    Ouphe,
    Ox,
    Oyster,
    Pangolin,
    Peasant,
    Pegasus,
    Pentavite,
    Performer,
    Pest,
    Phelddagrif,
    Phoenix,
    Phyrexian,
    Pilot,
    Pincher,
    Pirate,
    Plant,
    Porcupine,
    Possum,
    Praetor,
    Primarch,
    Prism,
    Processor,
    Qu,
    Rabbit,
    Raccoon,
    Ranger,
    Rat,
    Rebel,
    Reflection,
    Reveler,
    Rhino,
    Rigger,
    Robot,
    Rogue,
    Rukh,
    Sable,
    Salamander,
    Samurai,
    Sand,
    Saproling,
    Satyr,
    Scarecrow,
    Scientist,
    Scion,
    Scorpion,
    Scout,
    Sculpture,
    Seal,
    Serf,
    Serpent,
    Servo,
    Shade,
    Shaman,
    Shapeshifter,
    Shark,
    Sheep,
    Siren,
    Skeleton,
    Skunk,
    Slith,
    Sliver,
    Sloth,
    Slug,
    Snail,
    Snake,
    Soldier,
    Soltari,
    Sorcerer,
    Spawn,
    Specter,
    Spellshaper,
    Sphinx,
    Spider,
    Spike,
    Spirit,
    Splinter,
    Sponge,
    Spy,
    Squid,
    Squirrel,
    Starfish,
    Surrakar,
    Survivor,
    Symbiote,
    Synth,
    Teddy,
    Tentacle,
    Tetravite,
    Thalakos,
    Thopter,
    Thrull,
    Tiefling,
    TimeLord,
    Toy,
    Treefolk,
    Trilobite,
    Triskelavite,
    Troll,
    Turtle,
    Tyranid,
    Unicorn,
    Urzan,
    Vampire,
    Varmint,
    Vedalken,
    Villain,
    Volver,
    Wall,
    Walrus,
    Warlock,
    Warrior,
    Wasp,
    Weasel,
    Weird,
    Werewolf,
    Whale,
    Wizard,
    Wolf,
    Wolverine,
    Wombat,
    Worm,
    Wraith,
    Wurm,
    Yeti,
    Zombie,
    Zubera,
}
impl std::str::FromStr for CreatureType {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "advisor" => Ok(Self::Advisor),
            "aetherborn" => Ok(Self::Aetherborn),
            "alien" => Ok(Self::Alien),
            "ally" => Ok(Self::Ally),
            "angel" => Ok(Self::Angel),
            "antelope" => Ok(Self::Antelope),
            "ape" => Ok(Self::Ape),
            "archer" => Ok(Self::Archer),
            "archon" => Ok(Self::Archon),
            "armadillo" => Ok(Self::Armadillo),
            "army" => Ok(Self::Army),
            "artifact" => Ok(Self::Artifact),
            "artificer" => Ok(Self::Artificer),
            "assassin" => Ok(Self::Assassin),
            "assembly-worker" => Ok(Self::AssemblyWorker),
            "astartes" => Ok(Self::Astartes),
            "atog" => Ok(Self::Atog),
            "aurochs" => Ok(Self::Aurochs),
            "automaton" => Ok(Self::Automaton),
            "avatar" => Ok(Self::Avatar),
            "azra" => Ok(Self::Azra),
            "badger" => Ok(Self::Badger),
            "balloon" => Ok(Self::Balloon),
            "barbarian" => Ok(Self::Barbarian),
            "bard" => Ok(Self::Bard),
            "basilisk" => Ok(Self::Basilisk),
            "bat" => Ok(Self::Bat),
            "bear" => Ok(Self::Bear),
            "beast" => Ok(Self::Beast),
            "beaver" => Ok(Self::Beaver),
            "beeble" => Ok(Self::Beeble),
            "beholder" => Ok(Self::Beholder),
            "berserker" => Ok(Self::Berserker),
            "bird" => Ok(Self::Bird),
            "bison" => Ok(Self::Bison),
            "blinkmoth" => Ok(Self::Blinkmoth),
            "boar" => Ok(Self::Boar),
            "brainiac" => Ok(Self::Brainiac),
            "bringer" => Ok(Self::Bringer),
            "brushwagg" => Ok(Self::Brushwagg),
            "c'tan" => Ok(Self::Ctan),
            "camarid" => Ok(Self::Camarid),
            "camel" => Ok(Self::Camel),
            "capybara" => Ok(Self::Capybara),
            "caribou" => Ok(Self::Caribou),
            "carrier" => Ok(Self::Carrier),
            "cat" => Ok(Self::Cat),
            "centaur" => Ok(Self::Centaur),
            "chicken" => Ok(Self::Chicken),
            "child" => Ok(Self::Child),
            "chimera" => Ok(Self::Chimera),
            "citizen" => Ok(Self::Citizen),
            "cleric" => Ok(Self::Cleric),
            "clown" => Ok(Self::Clown),
            "cockatrice" => Ok(Self::Cockatrice),
            "construct" => Ok(Self::Construct),
            "coward" => Ok(Self::Coward),
            "coyote" => Ok(Self::Coyote),
            "crab" => Ok(Self::Crab),
            "crocodile" => Ok(Self::Crocodile),
            "custodes" => Ok(Self::Custodes),
            "cyberman" => Ok(Self::Cyberman),
            "cyclops" => Ok(Self::Cyclops),
            "dalek" => Ok(Self::Dalek),
            "dauthi" => Ok(Self::Dauthi),
            "demigod" => Ok(Self::Demigod),
            "demon" => Ok(Self::Demon),
            "deserter" => Ok(Self::Deserter),
            "detective" => Ok(Self::Detective),
            "devil" => Ok(Self::Devil),
            "dinosaur" => Ok(Self::Dinosaur),
            "djinn" => Ok(Self::Djinn),
            "doctor" => Ok(Self::Doctor),
            "dog" => Ok(Self::Dog),
            "dragon" => Ok(Self::Dragon),
            "drake" => Ok(Self::Drake),
            "dreadnought" => Ok(Self::Dreadnought),
            "drix" => Ok(Self::Drix),
            "drone" => Ok(Self::Drone),
            "druid" => Ok(Self::Druid),
            "dryad" => Ok(Self::Dryad),
            "dwarf" => Ok(Self::Dwarf),
            "echidna" => Ok(Self::Echidna),
            "efreet" => Ok(Self::Efreet),
            "egg" => Ok(Self::Egg),
            "elder" => Ok(Self::Elder),
            "eldrazi" => Ok(Self::Eldrazi),
            "elemental" => Ok(Self::Elemental),
            "elephant" => Ok(Self::Elephant),
            "elf" => Ok(Self::Elf),
            "elk" => Ok(Self::Elk),
            "employee" => Ok(Self::Employee),
            "eye" => Ok(Self::Eye),
            "faerie" => Ok(Self::Faerie),
            "ferret" => Ok(Self::Ferret),
            "fish" => Ok(Self::Fish),
            "flagbearer" => Ok(Self::Flagbearer),
            "fox" => Ok(Self::Fox),
            "fractal" => Ok(Self::Fractal),
            "frog" => Ok(Self::Frog),
            "fungus" => Ok(Self::Fungus),
            "gamer" => Ok(Self::Gamer),
            "gargoyle" => Ok(Self::Gargoyle),
            "germ" => Ok(Self::Germ),
            "giant" => Ok(Self::Giant),
            "gith" => Ok(Self::Gith),
            "glimmer" => Ok(Self::Glimmer),
            "gnoll" => Ok(Self::Gnoll),
            "gnome" => Ok(Self::Gnome),
            "goat" => Ok(Self::Goat),
            "goblin" => Ok(Self::Goblin),
            "god" => Ok(Self::God),
            "golem" => Ok(Self::Golem),
            "gorgon" => Ok(Self::Gorgon),
            "graveborn" => Ok(Self::Graveborn),
            "gremlin" => Ok(Self::Gremlin),
            "griffin" => Ok(Self::Griffin),
            "guest" => Ok(Self::Guest),
            "hag" => Ok(Self::Hag),
            "halfling" => Ok(Self::Halfling),
            "hamster" => Ok(Self::Hamster),
            "harpy" => Ok(Self::Harpy),
            "head" => Ok(Self::Head),
            "hedgehog" => Ok(Self::Hedgehog),
            "hellion" => Ok(Self::Hellion),
            "hero" => Ok(Self::Hero),
            "hippo" => Ok(Self::Hippo),
            "hippogriff" => Ok(Self::Hippogriff),
            "homarid" => Ok(Self::Homarid),
            "homunculus" => Ok(Self::Homunculus),
            "hornet" => Ok(Self::Hornet),
            "horror" => Ok(Self::Horror),
            "horse" => Ok(Self::Horse),
            "human" => Ok(Self::Human),
            "hydra" => Ok(Self::Hydra),
            "hyena" => Ok(Self::Hyena),
            "illusion" => Ok(Self::Illusion),
            "imp" => Ok(Self::Imp),
            "incarnation" => Ok(Self::Incarnation),
            "inkling" => Ok(Self::Inkling),
            "inquisitor" => Ok(Self::Inquisitor),
            "insect" => Ok(Self::Insect),
            "jackal" => Ok(Self::Jackal),
            "jellyfish" => Ok(Self::Jellyfish),
            "juggernaut" => Ok(Self::Juggernaut),
            "kangaroo" => Ok(Self::Kangaroo),
            "kavu" => Ok(Self::Kavu),
            "kirin" => Ok(Self::Kirin),
            "kithkin" => Ok(Self::Kithkin),
            "knight" => Ok(Self::Knight),
            "kobold" => Ok(Self::Kobold),
            "kor" => Ok(Self::Kor),
            "kraken" => Ok(Self::Kraken),
            "lamia" => Ok(Self::Lamia),
            "lammasu" => Ok(Self::Lammasu),
            "leech" => Ok(Self::Leech),
            "lemur" => Ok(Self::Lemur),
            "leviathan" => Ok(Self::Leviathan),
            "lhurgoyf" => Ok(Self::Lhurgoyf),
            "licid" => Ok(Self::Licid),
            "lizard" => Ok(Self::Lizard),
            "lobster" => Ok(Self::Lobster),
            "manticore" => Ok(Self::Manticore),
            "masticore" => Ok(Self::Masticore),
            "mercenary" => Ok(Self::Mercenary),
            "merfolk" => Ok(Self::Merfolk),
            "metathran" => Ok(Self::Metathran),
            "minion" => Ok(Self::Minion),
            "minotaur" => Ok(Self::Minotaur),
            "mite" => Ok(Self::Mite),
            "mole" => Ok(Self::Mole),
            "monger" => Ok(Self::Monger),
            "mongoose" => Ok(Self::Mongoose),
            "monk" => Ok(Self::Monk),
            "monkey" => Ok(Self::Monkey),
            "moogle" => Ok(Self::Moogle),
            "moonfolk" => Ok(Self::Moonfolk),
            "mount" => Ok(Self::Mount),
            "mouse" => Ok(Self::Mouse),
            "mutant" => Ok(Self::Mutant),
            "myr" => Ok(Self::Myr),
            "mystic" => Ok(Self::Mystic),
            "naga" => Ok(Self::Naga),
            "nautilus" => Ok(Self::Nautilus),
            "necron" => Ok(Self::Necron),
            "nephilim" => Ok(Self::Nephilim),
            "nightmare" => Ok(Self::Nightmare),
            "nightstalker" => Ok(Self::Nightstalker),
            "ninja" => Ok(Self::Ninja),
            "noble" => Ok(Self::Noble),
            "noggle" => Ok(Self::Noggle),
            "nomad" => Ok(Self::Nomad),
            "nymph" => Ok(Self::Nymph),
            "octopus" => Ok(Self::Octopus),
            "ogre" => Ok(Self::Ogre),
            "ooze" => Ok(Self::Ooze),
            "orb" => Ok(Self::Orb),
            "orc" => Ok(Self::Orc),
            "orgg" => Ok(Self::Orgg),
            "otter" => Ok(Self::Otter),
            "ouphe" => Ok(Self::Ouphe),
            "ox" => Ok(Self::Ox),
            "oyster" => Ok(Self::Oyster),
            "pangolin" => Ok(Self::Pangolin),
            "peasant" => Ok(Self::Peasant),
            "pegasus" => Ok(Self::Pegasus),
            "pentavite" => Ok(Self::Pentavite),
            "performer" => Ok(Self::Performer),
            "pest" => Ok(Self::Pest),
            "phelddagrif" => Ok(Self::Phelddagrif),
            "phoenix" => Ok(Self::Phoenix),
            "phyrexian" => Ok(Self::Phyrexian),
            "pilot" => Ok(Self::Pilot),
            "pincher" => Ok(Self::Pincher),
            "pirate" => Ok(Self::Pirate),
            "plant" => Ok(Self::Plant),
            "porcupine" => Ok(Self::Porcupine),
            "possum" => Ok(Self::Possum),
            "praetor" => Ok(Self::Praetor),
            "primarch" => Ok(Self::Primarch),
            "prism" => Ok(Self::Prism),
            "processor" => Ok(Self::Processor),
            "qu" => Ok(Self::Qu),
            "rabbit" => Ok(Self::Rabbit),
            "raccoon" => Ok(Self::Raccoon),
            "ranger" => Ok(Self::Ranger),
            "rat" => Ok(Self::Rat),
            "rebel" => Ok(Self::Rebel),
            "reflection" => Ok(Self::Reflection),
            "reveler" => Ok(Self::Reveler),
            "rhino" => Ok(Self::Rhino),
            "rigger" => Ok(Self::Rigger),
            "robot" => Ok(Self::Robot),
            "rogue" => Ok(Self::Rogue),
            "rukh" => Ok(Self::Rukh),
            "sable" => Ok(Self::Sable),
            "salamander" => Ok(Self::Salamander),
            "samurai" => Ok(Self::Samurai),
            "sand" => Ok(Self::Sand),
            "saproling" => Ok(Self::Saproling),
            "satyr" => Ok(Self::Satyr),
            "scarecrow" => Ok(Self::Scarecrow),
            "scientist" => Ok(Self::Scientist),
            "scion" => Ok(Self::Scion),
            "scorpion" => Ok(Self::Scorpion),
            "scout" => Ok(Self::Scout),
            "sculpture" => Ok(Self::Sculpture),
            "seal" => Ok(Self::Seal),
            "serf" => Ok(Self::Serf),
            "serpent" => Ok(Self::Serpent),
            "servo" => Ok(Self::Servo),
            "shade" => Ok(Self::Shade),
            "shaman" => Ok(Self::Shaman),
            "shapeshifter" => Ok(Self::Shapeshifter),
            "shark" => Ok(Self::Shark),
            "sheep" => Ok(Self::Sheep),
            "siren" => Ok(Self::Siren),
            "skeleton" => Ok(Self::Skeleton),
            "skunk" => Ok(Self::Skunk),
            "slith" => Ok(Self::Slith),
            "sliver" => Ok(Self::Sliver),
            "sloth" => Ok(Self::Sloth),
            "slug" => Ok(Self::Slug),
            "snail" => Ok(Self::Snail),
            "snake" => Ok(Self::Snake),
            "soldier" => Ok(Self::Soldier),
            "soltari" => Ok(Self::Soltari),
            "sorcerer" => Ok(Self::Sorcerer),
            "spawn" => Ok(Self::Spawn),
            "specter" => Ok(Self::Specter),
            "spellshaper" => Ok(Self::Spellshaper),
            "sphinx" => Ok(Self::Sphinx),
            "spider" => Ok(Self::Spider),
            "spike" => Ok(Self::Spike),
            "spirit" => Ok(Self::Spirit),
            "splinter" => Ok(Self::Splinter),
            "sponge" => Ok(Self::Sponge),
            "spy" => Ok(Self::Spy),
            "squid" => Ok(Self::Squid),
            "squirrel" => Ok(Self::Squirrel),
            "starfish" => Ok(Self::Starfish),
            "surrakar" => Ok(Self::Surrakar),
            "survivor" => Ok(Self::Survivor),
            "symbiote" => Ok(Self::Symbiote),
            "synth" => Ok(Self::Synth),
            "teddy" => Ok(Self::Teddy),
            "tentacle" => Ok(Self::Tentacle),
            "tetravite" => Ok(Self::Tetravite),
            "thalakos" => Ok(Self::Thalakos),
            "thopter" => Ok(Self::Thopter),
            "thrull" => Ok(Self::Thrull),
            "tiefling" => Ok(Self::Tiefling),
            "time lord" => Ok(Self::TimeLord),
            "toy" => Ok(Self::Toy),
            "treefolk" => Ok(Self::Treefolk),
            "trilobite" => Ok(Self::Trilobite),
            "triskelavite" => Ok(Self::Triskelavite),
            "troll" => Ok(Self::Troll),
            "turtle" => Ok(Self::Turtle),
            "tyranid" => Ok(Self::Tyranid),
            "unicorn" => Ok(Self::Unicorn),
            "urzan" => Ok(Self::Urzan),
            "vampire" => Ok(Self::Vampire),
            "varmint" => Ok(Self::Varmint),
            "vedalken" => Ok(Self::Vedalken),
            "villain" => Ok(Self::Villain),
            "volver" => Ok(Self::Volver),
            "wall" => Ok(Self::Wall),
            "walrus" => Ok(Self::Walrus),
            "warlock" => Ok(Self::Warlock),
            "warrior" => Ok(Self::Warrior),
            "wasp" => Ok(Self::Wasp),
            "weasel" => Ok(Self::Weasel),
            "weird" => Ok(Self::Weird),
            "werewolf" => Ok(Self::Werewolf),
            "whale" => Ok(Self::Whale),
            "wizard" => Ok(Self::Wizard),
            "wolf" => Ok(Self::Wolf),
            "wolverine" => Ok(Self::Wolverine),
            "wombat" => Ok(Self::Wombat),
            "worm" => Ok(Self::Worm),
            "wraith" => Ok(Self::Wraith),
            "wurm" => Ok(Self::Wurm),
            "yeti" => Ok(Self::Yeti),
            "zombie" => Ok(Self::Zombie),
            "zubera" => Ok(Self::Zubera),
            other => Err(format!("Unknown CreatureType: {}", other.to_string())),
        }
    }
}
impl CreatureType {
    fn as_str(&self) -> &'static str {
        match self {
            Self::Advisor => "advisor",
            Self::Aetherborn => "aetherborn",
            Self::Alien => "alien",
            Self::Ally => "ally",
            Self::Angel => "angel",
            Self::Antelope => "antelope",
            Self::Ape => "ape",
            Self::Archer => "archer",
            Self::Archon => "archon",
            Self::Armadillo => "armadillo",
            Self::Army => "army",
            Self::Artifact => "artifact",
            Self::Artificer => "artificer",
            Self::Assassin => "assassin",
            Self::AssemblyWorker => "assembly-worker",
            Self::Astartes => "astartes",
            Self::Atog => "atog",
            Self::Aurochs => "aurochs",
            Self::Automaton => "automaton",
            Self::Avatar => "avatar",
            Self::Azra => "azra",
            Self::Badger => "badger",
            Self::Balloon => "balloon",
            Self::Barbarian => "barbarian",
            Self::Bard => "bard",
            Self::Basilisk => "basilisk",
            Self::Bat => "bat",
            Self::Bear => "bear",
            Self::Beast => "beast",
            Self::Beaver => "beaver",
            Self::Beeble => "beeble",
            Self::Beholder => "beholder",
            Self::Berserker => "berserker",
            Self::Bird => "bird",
            Self::Bison => "bison",
            Self::Blinkmoth => "blinkmoth",
            Self::Boar => "boar",
            Self::Brainiac => "brainiac",
            Self::Bringer => "bringer",
            Self::Brushwagg => "brushwagg",
            Self::Ctan => "c'tan",
            Self::Camarid => "camarid",
            Self::Camel => "camel",
            Self::Capybara => "capybara",
            Self::Caribou => "caribou",
            Self::Carrier => "carrier",
            Self::Cat => "cat",
            Self::Centaur => "centaur",
            Self::Chicken => "chicken",
            Self::Child => "child",
            Self::Chimera => "chimera",
            Self::Citizen => "citizen",
            Self::Cleric => "cleric",
            Self::Clown => "clown",
            Self::Cockatrice => "cockatrice",
            Self::Construct => "construct",
            Self::Coward => "coward",
            Self::Coyote => "coyote",
            Self::Crab => "crab",
            Self::Crocodile => "crocodile",
            Self::Custodes => "custodes",
            Self::Cyberman => "cyberman",
            Self::Cyclops => "cyclops",
            Self::Dalek => "dalek",
            Self::Dauthi => "dauthi",
            Self::Demigod => "demigod",
            Self::Demon => "demon",
            Self::Deserter => "deserter",
            Self::Detective => "detective",
            Self::Devil => "devil",
            Self::Dinosaur => "dinosaur",
            Self::Djinn => "djinn",
            Self::Doctor => "doctor",
            Self::Dog => "dog",
            Self::Dragon => "dragon",
            Self::Drake => "drake",
            Self::Dreadnought => "dreadnought",
            Self::Drix => "drix",
            Self::Drone => "drone",
            Self::Druid => "druid",
            Self::Dryad => "dryad",
            Self::Dwarf => "dwarf",
            Self::Echidna => "echidna",
            Self::Efreet => "efreet",
            Self::Egg => "egg",
            Self::Elder => "elder",
            Self::Eldrazi => "eldrazi",
            Self::Elemental => "elemental",
            Self::Elephant => "elephant",
            Self::Elf => "elf",
            Self::Elk => "elk",
            Self::Employee => "employee",
            Self::Eye => "eye",
            Self::Faerie => "faerie",
            Self::Ferret => "ferret",
            Self::Fish => "fish",
            Self::Flagbearer => "flagbearer",
            Self::Fox => "fox",
            Self::Fractal => "fractal",
            Self::Frog => "frog",
            Self::Fungus => "fungus",
            Self::Gamer => "gamer",
            Self::Gargoyle => "gargoyle",
            Self::Germ => "germ",
            Self::Giant => "giant",
            Self::Gith => "gith",
            Self::Glimmer => "glimmer",
            Self::Gnoll => "gnoll",
            Self::Gnome => "gnome",
            Self::Goat => "goat",
            Self::Goblin => "goblin",
            Self::God => "god",
            Self::Golem => "golem",
            Self::Gorgon => "gorgon",
            Self::Graveborn => "graveborn",
            Self::Gremlin => "gremlin",
            Self::Griffin => "griffin",
            Self::Guest => "guest",
            Self::Hag => "hag",
            Self::Halfling => "halfling",
            Self::Hamster => "hamster",
            Self::Harpy => "harpy",
            Self::Head => "head",
            Self::Hedgehog => "hedgehog",
            Self::Hellion => "hellion",
            Self::Hero => "hero",
            Self::Hippo => "hippo",
            Self::Hippogriff => "hippogriff",
            Self::Homarid => "homarid",
            Self::Homunculus => "homunculus",
            Self::Hornet => "hornet",
            Self::Horror => "horror",
            Self::Horse => "horse",
            Self::Human => "human",
            Self::Hydra => "hydra",
            Self::Hyena => "hyena",
            Self::Illusion => "illusion",
            Self::Imp => "imp",
            Self::Incarnation => "incarnation",
            Self::Inkling => "inkling",
            Self::Inquisitor => "inquisitor",
            Self::Insect => "insect",
            Self::Jackal => "jackal",
            Self::Jellyfish => "jellyfish",
            Self::Juggernaut => "juggernaut",
            Self::Kangaroo => "kangaroo",
            Self::Kavu => "kavu",
            Self::Kirin => "kirin",
            Self::Kithkin => "kithkin",
            Self::Knight => "knight",
            Self::Kobold => "kobold",
            Self::Kor => "kor",
            Self::Kraken => "kraken",
            Self::Lamia => "lamia",
            Self::Lammasu => "lammasu",
            Self::Leech => "leech",
            Self::Lemur => "lemur",
            Self::Leviathan => "leviathan",
            Self::Lhurgoyf => "lhurgoyf",
            Self::Licid => "licid",
            Self::Lizard => "lizard",
            Self::Lobster => "lobster",
            Self::Manticore => "manticore",
            Self::Masticore => "masticore",
            Self::Mercenary => "mercenary",
            Self::Merfolk => "merfolk",
            Self::Metathran => "metathran",
            Self::Minion => "minion",
            Self::Minotaur => "minotaur",
            Self::Mite => "mite",
            Self::Mole => "mole",
            Self::Monger => "monger",
            Self::Mongoose => "mongoose",
            Self::Monk => "monk",
            Self::Monkey => "monkey",
            Self::Moogle => "moogle",
            Self::Moonfolk => "moonfolk",
            Self::Mount => "mount",
            Self::Mouse => "mouse",
            Self::Mutant => "mutant",
            Self::Myr => "myr",
            Self::Mystic => "mystic",
            Self::Naga => "naga",
            Self::Nautilus => "nautilus",
            Self::Necron => "necron",
            Self::Nephilim => "nephilim",
            Self::Nightmare => "nightmare",
            Self::Nightstalker => "nightstalker",
            Self::Ninja => "ninja",
            Self::Noble => "noble",
            Self::Noggle => "noggle",
            Self::Nomad => "nomad",
            Self::Nymph => "nymph",
            Self::Octopus => "octopus",
            Self::Ogre => "ogre",
            Self::Ooze => "ooze",
            Self::Orb => "orb",
            Self::Orc => "orc",
            Self::Orgg => "orgg",
            Self::Otter => "otter",
            Self::Ouphe => "ouphe",
            Self::Ox => "ox",
            Self::Oyster => "oyster",
            Self::Pangolin => "pangolin",
            Self::Peasant => "peasant",
            Self::Pegasus => "pegasus",
            Self::Pentavite => "pentavite",
            Self::Performer => "performer",
            Self::Pest => "pest",
            Self::Phelddagrif => "phelddagrif",
            Self::Phoenix => "phoenix",
            Self::Phyrexian => "phyrexian",
            Self::Pilot => "pilot",
            Self::Pincher => "pincher",
            Self::Pirate => "pirate",
            Self::Plant => "plant",
            Self::Porcupine => "porcupine",
            Self::Possum => "possum",
            Self::Praetor => "praetor",
            Self::Primarch => "primarch",
            Self::Prism => "prism",
            Self::Processor => "processor",
            Self::Qu => "qu",
            Self::Rabbit => "rabbit",
            Self::Raccoon => "raccoon",
            Self::Ranger => "ranger",
            Self::Rat => "rat",
            Self::Rebel => "rebel",
            Self::Reflection => "reflection",
            Self::Reveler => "reveler",
            Self::Rhino => "rhino",
            Self::Rigger => "rigger",
            Self::Robot => "robot",
            Self::Rogue => "rogue",
            Self::Rukh => "rukh",
            Self::Sable => "sable",
            Self::Salamander => "salamander",
            Self::Samurai => "samurai",
            Self::Sand => "sand",
            Self::Saproling => "saproling",
            Self::Satyr => "satyr",
            Self::Scarecrow => "scarecrow",
            Self::Scientist => "scientist",
            Self::Scion => "scion",
            Self::Scorpion => "scorpion",
            Self::Scout => "scout",
            Self::Sculpture => "sculpture",
            Self::Seal => "seal",
            Self::Serf => "serf",
            Self::Serpent => "serpent",
            Self::Servo => "servo",
            Self::Shade => "shade",
            Self::Shaman => "shaman",
            Self::Shapeshifter => "shapeshifter",
            Self::Shark => "shark",
            Self::Sheep => "sheep",
            Self::Siren => "siren",
            Self::Skeleton => "skeleton",
            Self::Skunk => "skunk",
            Self::Slith => "slith",
            Self::Sliver => "sliver",
            Self::Sloth => "sloth",
            Self::Slug => "slug",
            Self::Snail => "snail",
            Self::Snake => "snake",
            Self::Soldier => "soldier",
            Self::Soltari => "soltari",
            Self::Sorcerer => "sorcerer",
            Self::Spawn => "spawn",
            Self::Specter => "specter",
            Self::Spellshaper => "spellshaper",
            Self::Sphinx => "sphinx",
            Self::Spider => "spider",
            Self::Spike => "spike",
            Self::Spirit => "spirit",
            Self::Splinter => "splinter",
            Self::Sponge => "sponge",
            Self::Spy => "spy",
            Self::Squid => "squid",
            Self::Squirrel => "squirrel",
            Self::Starfish => "starfish",
            Self::Surrakar => "surrakar",
            Self::Survivor => "survivor",
            Self::Symbiote => "symbiote",
            Self::Synth => "synth",
            Self::Teddy => "teddy",
            Self::Tentacle => "tentacle",
            Self::Tetravite => "tetravite",
            Self::Thalakos => "thalakos",
            Self::Thopter => "thopter",
            Self::Thrull => "thrull",
            Self::Tiefling => "tiefling",
            Self::TimeLord => "time lord",
            Self::Toy => "toy",
            Self::Treefolk => "treefolk",
            Self::Trilobite => "trilobite",
            Self::Triskelavite => "triskelavite",
            Self::Troll => "troll",
            Self::Turtle => "turtle",
            Self::Tyranid => "tyranid",
            Self::Unicorn => "unicorn",
            Self::Urzan => "urzan",
            Self::Vampire => "vampire",
            Self::Varmint => "varmint",
            Self::Vedalken => "vedalken",
            Self::Villain => "villain",
            Self::Volver => "volver",
            Self::Wall => "wall",
            Self::Walrus => "walrus",
            Self::Warlock => "warlock",
            Self::Warrior => "warrior",
            Self::Wasp => "wasp",
            Self::Weasel => "weasel",
            Self::Weird => "weird",
            Self::Werewolf => "werewolf",
            Self::Whale => "whale",
            Self::Wizard => "wizard",
            Self::Wolf => "wolf",
            Self::Wolverine => "wolverine",
            Self::Wombat => "wombat",
            Self::Worm => "worm",
            Self::Wraith => "wraith",
            Self::Wurm => "wurm",
            Self::Yeti => "yeti",
            Self::Zombie => "zombie",
            Self::Zubera => "zubera",
        }
    }
}
impl std::fmt::Display for CreatureType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
impl CreatureType {
    pub fn all() -> impl Iterator<Item = Self> {
        [
            Self::Advisor,
            Self::Aetherborn,
            Self::Alien,
            Self::Ally,
            Self::Angel,
            Self::Antelope,
            Self::Ape,
            Self::Archer,
            Self::Archon,
            Self::Armadillo,
            Self::Army,
            Self::Artifact,
            Self::Artificer,
            Self::Assassin,
            Self::AssemblyWorker,
            Self::Astartes,
            Self::Atog,
            Self::Aurochs,
            Self::Automaton,
            Self::Avatar,
            Self::Azra,
            Self::Badger,
            Self::Balloon,
            Self::Barbarian,
            Self::Bard,
            Self::Basilisk,
            Self::Bat,
            Self::Bear,
            Self::Beast,
            Self::Beaver,
            Self::Beeble,
            Self::Beholder,
            Self::Berserker,
            Self::Bird,
            Self::Bison,
            Self::Blinkmoth,
            Self::Boar,
            Self::Brainiac,
            Self::Bringer,
            Self::Brushwagg,
            Self::Ctan,
            Self::Camarid,
            Self::Camel,
            Self::Capybara,
            Self::Caribou,
            Self::Carrier,
            Self::Cat,
            Self::Centaur,
            Self::Chicken,
            Self::Child,
            Self::Chimera,
            Self::Citizen,
            Self::Cleric,
            Self::Clown,
            Self::Cockatrice,
            Self::Construct,
            Self::Coward,
            Self::Coyote,
            Self::Crab,
            Self::Crocodile,
            Self::Custodes,
            Self::Cyberman,
            Self::Cyclops,
            Self::Dalek,
            Self::Dauthi,
            Self::Demigod,
            Self::Demon,
            Self::Deserter,
            Self::Detective,
            Self::Devil,
            Self::Dinosaur,
            Self::Djinn,
            Self::Doctor,
            Self::Dog,
            Self::Dragon,
            Self::Drake,
            Self::Dreadnought,
            Self::Drix,
            Self::Drone,
            Self::Druid,
            Self::Dryad,
            Self::Dwarf,
            Self::Echidna,
            Self::Efreet,
            Self::Egg,
            Self::Elder,
            Self::Eldrazi,
            Self::Elemental,
            Self::Elephant,
            Self::Elf,
            Self::Elk,
            Self::Employee,
            Self::Eye,
            Self::Faerie,
            Self::Ferret,
            Self::Fish,
            Self::Flagbearer,
            Self::Fox,
            Self::Fractal,
            Self::Frog,
            Self::Fungus,
            Self::Gamer,
            Self::Gargoyle,
            Self::Germ,
            Self::Giant,
            Self::Gith,
            Self::Glimmer,
            Self::Gnoll,
            Self::Gnome,
            Self::Goat,
            Self::Goblin,
            Self::God,
            Self::Golem,
            Self::Gorgon,
            Self::Graveborn,
            Self::Gremlin,
            Self::Griffin,
            Self::Guest,
            Self::Hag,
            Self::Halfling,
            Self::Hamster,
            Self::Harpy,
            Self::Head,
            Self::Hedgehog,
            Self::Hellion,
            Self::Hero,
            Self::Hippo,
            Self::Hippogriff,
            Self::Homarid,
            Self::Homunculus,
            Self::Hornet,
            Self::Horror,
            Self::Horse,
            Self::Human,
            Self::Hydra,
            Self::Hyena,
            Self::Illusion,
            Self::Imp,
            Self::Incarnation,
            Self::Inkling,
            Self::Inquisitor,
            Self::Insect,
            Self::Jackal,
            Self::Jellyfish,
            Self::Juggernaut,
            Self::Kangaroo,
            Self::Kavu,
            Self::Kirin,
            Self::Kithkin,
            Self::Knight,
            Self::Kobold,
            Self::Kor,
            Self::Kraken,
            Self::Lamia,
            Self::Lammasu,
            Self::Leech,
            Self::Lemur,
            Self::Leviathan,
            Self::Lhurgoyf,
            Self::Licid,
            Self::Lizard,
            Self::Lobster,
            Self::Manticore,
            Self::Masticore,
            Self::Mercenary,
            Self::Merfolk,
            Self::Metathran,
            Self::Minion,
            Self::Minotaur,
            Self::Mite,
            Self::Mole,
            Self::Monger,
            Self::Mongoose,
            Self::Monk,
            Self::Monkey,
            Self::Moogle,
            Self::Moonfolk,
            Self::Mount,
            Self::Mouse,
            Self::Mutant,
            Self::Myr,
            Self::Mystic,
            Self::Naga,
            Self::Nautilus,
            Self::Necron,
            Self::Nephilim,
            Self::Nightmare,
            Self::Nightstalker,
            Self::Ninja,
            Self::Noble,
            Self::Noggle,
            Self::Nomad,
            Self::Nymph,
            Self::Octopus,
            Self::Ogre,
            Self::Ooze,
            Self::Orb,
            Self::Orc,
            Self::Orgg,
            Self::Otter,
            Self::Ouphe,
            Self::Ox,
            Self::Oyster,
            Self::Pangolin,
            Self::Peasant,
            Self::Pegasus,
            Self::Pentavite,
            Self::Performer,
            Self::Pest,
            Self::Phelddagrif,
            Self::Phoenix,
            Self::Phyrexian,
            Self::Pilot,
            Self::Pincher,
            Self::Pirate,
            Self::Plant,
            Self::Porcupine,
            Self::Possum,
            Self::Praetor,
            Self::Primarch,
            Self::Prism,
            Self::Processor,
            Self::Qu,
            Self::Rabbit,
            Self::Raccoon,
            Self::Ranger,
            Self::Rat,
            Self::Rebel,
            Self::Reflection,
            Self::Reveler,
            Self::Rhino,
            Self::Rigger,
            Self::Robot,
            Self::Rogue,
            Self::Rukh,
            Self::Sable,
            Self::Salamander,
            Self::Samurai,
            Self::Sand,
            Self::Saproling,
            Self::Satyr,
            Self::Scarecrow,
            Self::Scientist,
            Self::Scion,
            Self::Scorpion,
            Self::Scout,
            Self::Sculpture,
            Self::Seal,
            Self::Serf,
            Self::Serpent,
            Self::Servo,
            Self::Shade,
            Self::Shaman,
            Self::Shapeshifter,
            Self::Shark,
            Self::Sheep,
            Self::Siren,
            Self::Skeleton,
            Self::Skunk,
            Self::Slith,
            Self::Sliver,
            Self::Sloth,
            Self::Slug,
            Self::Snail,
            Self::Snake,
            Self::Soldier,
            Self::Soltari,
            Self::Sorcerer,
            Self::Spawn,
            Self::Specter,
            Self::Spellshaper,
            Self::Sphinx,
            Self::Spider,
            Self::Spike,
            Self::Spirit,
            Self::Splinter,
            Self::Sponge,
            Self::Spy,
            Self::Squid,
            Self::Squirrel,
            Self::Starfish,
            Self::Surrakar,
            Self::Survivor,
            Self::Symbiote,
            Self::Synth,
            Self::Teddy,
            Self::Tentacle,
            Self::Tetravite,
            Self::Thalakos,
            Self::Thopter,
            Self::Thrull,
            Self::Tiefling,
            Self::TimeLord,
            Self::Toy,
            Self::Treefolk,
            Self::Trilobite,
            Self::Triskelavite,
            Self::Troll,
            Self::Turtle,
            Self::Tyranid,
            Self::Unicorn,
            Self::Urzan,
            Self::Vampire,
            Self::Varmint,
            Self::Vedalken,
            Self::Villain,
            Self::Volver,
            Self::Wall,
            Self::Walrus,
            Self::Warlock,
            Self::Warrior,
            Self::Wasp,
            Self::Weasel,
            Self::Weird,
            Self::Werewolf,
            Self::Whale,
            Self::Wizard,
            Self::Wolf,
            Self::Wolverine,
            Self::Wombat,
            Self::Worm,
            Self::Wraith,
            Self::Wurm,
            Self::Yeti,
            Self::Zombie,
            Self::Zubera,
        ]
        .into_iter()
    }
}
