#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CreatureType {
    Advisor,
    Aetherborn,
    Alien,
    Ally,
    Angel,
    Antelope,
    Ape,
    Archer,
    Archon,
    Armadillo,
    Army,
    Artifact,
    Artificer,
    Assassin,
    AssemblyWorker,
    Astartes,
    Atog,
    Aurochs,
    Automaton,
    Avatar,
    Azra,
    Badger,
    Balloon,
    Barbarian,
    Bard,
    Basilisk,
    Bat,
    Bear,
    Beast,
    Beaver,
    Beeble,
    Beholder,
    Berserker,
    Bird,
    Bison,
    Blinkmoth,
    Boar,
    Brainiac,
    Bringer,
    Brushwagg,
    Ctan,
    Camarid,
    Camel,
    Capybara,
    Caribou,
    Carrier,
    Cat,
    Centaur,
    Chicken,
    Child,
    Chimera,
    Citizen,
    Cleric,
    Clown,
    Cockatrice,
    Construct,
    Coward,
    Coyote,
    Crab,
    Crocodile,
    Custodes,
    Cyberman,
    Cyclops,
    Dalek,
    Dauthi,
    Demigod,
    Demon,
    Deserter,
    Detective,
    Devil,
    Dinosaur,
    Djinn,
    Doctor,
    Dog,
    Dragon,
    Drake,
    Dreadnought,
    Drix,
    Drone,
    Druid,
    Dryad,
    Dwarf,
    Echidna,
    Efreet,
    Egg,
    Elder,
    Eldrazi,
    Elemental,
    Elephant,
    Elf,
    Elk,
    Employee,
    Eye,
    Faerie,
    Ferret,
    Fish,
    Flagbearer,
    Fox,
    Fractal,
    Frog,
    Fungus,
    Gamer,
    Gargoyle,
    Germ,
    Giant,
    Gith,
    Glimmer,
    Gnoll,
    Gnome,
    Goat,
    Goblin,
    God,
    Golem,
    Gorgon,
    Graveborn,
    Gremlin,
    Griffin,
    Guest,
    Hag,
    Halfling,
    Hamster,
    Harpy,
    Head,
    Hedgehog,
    Hellion,
    Hero,
    Hippo,
    Hippogriff,
    Homarid,
    Homunculus,
    Hornet,
    Horror,
    Horse,
    Human,
    Hydra,
    Hyena,
    Illusion,
    Imp,
    Incarnation,
    Inkling,
    Inquisitor,
    Insect,
    Jackal,
    Jellyfish,
    Juggernaut,
    Kangaroo,
    Kavu,
    Kirin,
    Kithkin,
    Knight,
    Kobold,
    Kor,
    Kraken,
    Lamia,
    Lammasu,
    Leech,
    Lemur,
    Leviathan,
    Lhurgoyf,
    Licid,
    Lizard,
    Lobster,
    Manticore,
    Masticore,
    Mercenary,
    Merfolk,
    Metathran,
    Minion,
    Minotaur,
    Mite,
    Mole,
    Monger,
    Mongoose,
    Monk,
    Monkey,
    Moogle,
    Moonfolk,
    Mount,
    Mouse,
    Mutant,
    Myr,
    Mystic,
    Naga,
    Nautilus,
    Necron,
    Nephilim,
    Nightmare,
    Nightstalker,
    Ninja,
    Noble,
    Noggle,
    Nomad,
    Nymph,
    Octopus,
    Ogre,
    Ooze,
    Orb,
    Orc,
    Orgg,
    Otter,
    Ouphe,
    Ox,
    Oyster,
    Pangolin,
    Peasant,
    Pegasus,
    Pentavite,
    Performer,
    Pest,
    Phelddagrif,
    Phoenix,
    Phyrexian,
    Pilot,
    Pincher,
    Pirate,
    Plant,
    Porcupine,
    Possum,
    Praetor,
    Primarch,
    Prism,
    Processor,
    Qu,
    Rabbit,
    Raccoon,
    Ranger,
    Rat,
    Rebel,
    Reflection,
    Reveler,
    Rhino,
    Rigger,
    Robot,
    Rogue,
    Rukh,
    Sable,
    Salamander,
    Samurai,
    Sand,
    Saproling,
    Satyr,
    Scarecrow,
    Scientist,
    Scion,
    Scorpion,
    Scout,
    Sculpture,
    Seal,
    Serf,
    Serpent,
    Servo,
    Shade,
    Shaman,
    Shapeshifter,
    Shark,
    Sheep,
    Siren,
    Skeleton,
    Skunk,
    Slith,
    Sliver,
    Sloth,
    Slug,
    Snail,
    Snake,
    Soldier,
    Soltari,
    Spawn,
    Specter,
    Spellshaper,
    Sphinx,
    Spider,
    Spike,
    Spirit,
    Splinter,
    Sponge,
    Spy,
    Squid,
    Squirrel,
    Starfish,
    Surrakar,
    Survivor,
    Symbiote,
    Synth,
    Teddy,
    Tentacle,
    Tetravite,
    Thalakos,
    Thopter,
    Thrull,
    Tiefling,
    TimeLord,
    Toy,
    Treefolk,
    Trilobite,
    Triskelavite,
    Troll,
    Turtle,
    Tyranid,
    Unicorn,
    Urzan,
    Vampire,
    Varmint,
    Vedalken,
    Villain,
    Volver,
    Wall,
    Walrus,
    Warlock,
    Warrior,
    Wasp,
    Weasel,
    Weird,
    Werewolf,
    Whale,
    Wizard,
    Wolf,
    Wolverine,
    Wombat,
    Worm,
    Wraith,
    Wurm,
    Yeti,
    Zombie,
    Zubera,
}
impl std::str::FromStr for CreatureType {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Advisor" => Ok(Self::Advisor),
            "Aetherborn" => Ok(Self::Aetherborn),
            "Alien" => Ok(Self::Alien),
            "Ally" => Ok(Self::Ally),
            "Angel" => Ok(Self::Angel),
            "Antelope" => Ok(Self::Antelope),
            "Ape" => Ok(Self::Ape),
            "Archer" => Ok(Self::Archer),
            "Archon" => Ok(Self::Archon),
            "Armadillo" => Ok(Self::Armadillo),
            "Army" => Ok(Self::Army),
            "Artifact" => Ok(Self::Artifact),
            "Artificer" => Ok(Self::Artificer),
            "Assassin" => Ok(Self::Assassin),
            "Assembly-Worker" => Ok(Self::AssemblyWorker),
            "Astartes" => Ok(Self::Astartes),
            "Atog" => Ok(Self::Atog),
            "Aurochs" => Ok(Self::Aurochs),
            "Automaton" => Ok(Self::Automaton),
            "Avatar" => Ok(Self::Avatar),
            "Azra" => Ok(Self::Azra),
            "Badger" => Ok(Self::Badger),
            "Balloon" => Ok(Self::Balloon),
            "Barbarian" => Ok(Self::Barbarian),
            "Bard" => Ok(Self::Bard),
            "Basilisk" => Ok(Self::Basilisk),
            "Bat" => Ok(Self::Bat),
            "Bear" => Ok(Self::Bear),
            "Beast" => Ok(Self::Beast),
            "Beaver" => Ok(Self::Beaver),
            "Beeble" => Ok(Self::Beeble),
            "Beholder" => Ok(Self::Beholder),
            "Berserker" => Ok(Self::Berserker),
            "Bird" => Ok(Self::Bird),
            "Bison" => Ok(Self::Bison),
            "Blinkmoth" => Ok(Self::Blinkmoth),
            "Boar" => Ok(Self::Boar),
            "Brainiac" => Ok(Self::Brainiac),
            "Bringer" => Ok(Self::Bringer),
            "Brushwagg" => Ok(Self::Brushwagg),
            "C'tan" => Ok(Self::Ctan),
            "Camarid" => Ok(Self::Camarid),
            "Camel" => Ok(Self::Camel),
            "Capybara" => Ok(Self::Capybara),
            "Caribou" => Ok(Self::Caribou),
            "Carrier" => Ok(Self::Carrier),
            "Cat" => Ok(Self::Cat),
            "Centaur" => Ok(Self::Centaur),
            "Chicken" => Ok(Self::Chicken),
            "Child" => Ok(Self::Child),
            "Chimera" => Ok(Self::Chimera),
            "Citizen" => Ok(Self::Citizen),
            "Cleric" => Ok(Self::Cleric),
            "Clown" => Ok(Self::Clown),
            "Cockatrice" => Ok(Self::Cockatrice),
            "Construct" => Ok(Self::Construct),
            "Coward" => Ok(Self::Coward),
            "Coyote" => Ok(Self::Coyote),
            "Crab" => Ok(Self::Crab),
            "Crocodile" => Ok(Self::Crocodile),
            "Custodes" => Ok(Self::Custodes),
            "Cyberman" => Ok(Self::Cyberman),
            "Cyclops" => Ok(Self::Cyclops),
            "Dalek" => Ok(Self::Dalek),
            "Dauthi" => Ok(Self::Dauthi),
            "Demigod" => Ok(Self::Demigod),
            "Demon" => Ok(Self::Demon),
            "Deserter" => Ok(Self::Deserter),
            "Detective" => Ok(Self::Detective),
            "Devil" => Ok(Self::Devil),
            "Dinosaur" => Ok(Self::Dinosaur),
            "Djinn" => Ok(Self::Djinn),
            "Doctor" => Ok(Self::Doctor),
            "Dog" => Ok(Self::Dog),
            "Dragon" => Ok(Self::Dragon),
            "Drake" => Ok(Self::Drake),
            "Dreadnought" => Ok(Self::Dreadnought),
            "Drix" => Ok(Self::Drix),
            "Drone" => Ok(Self::Drone),
            "Druid" => Ok(Self::Druid),
            "Dryad" => Ok(Self::Dryad),
            "Dwarf" => Ok(Self::Dwarf),
            "Echidna" => Ok(Self::Echidna),
            "Efreet" => Ok(Self::Efreet),
            "Egg" => Ok(Self::Egg),
            "Elder" => Ok(Self::Elder),
            "Eldrazi" => Ok(Self::Eldrazi),
            "Elemental" => Ok(Self::Elemental),
            "Elephant" => Ok(Self::Elephant),
            "Elf" => Ok(Self::Elf),
            "Elk" => Ok(Self::Elk),
            "Employee" => Ok(Self::Employee),
            "Eye" => Ok(Self::Eye),
            "Faerie" => Ok(Self::Faerie),
            "Ferret" => Ok(Self::Ferret),
            "Fish" => Ok(Self::Fish),
            "Flagbearer" => Ok(Self::Flagbearer),
            "Fox" => Ok(Self::Fox),
            "Fractal" => Ok(Self::Fractal),
            "Frog" => Ok(Self::Frog),
            "Fungus" => Ok(Self::Fungus),
            "Gamer" => Ok(Self::Gamer),
            "Gargoyle" => Ok(Self::Gargoyle),
            "Germ" => Ok(Self::Germ),
            "Giant" => Ok(Self::Giant),
            "Gith" => Ok(Self::Gith),
            "Glimmer" => Ok(Self::Glimmer),
            "Gnoll" => Ok(Self::Gnoll),
            "Gnome" => Ok(Self::Gnome),
            "Goat" => Ok(Self::Goat),
            "Goblin" => Ok(Self::Goblin),
            "God" => Ok(Self::God),
            "Golem" => Ok(Self::Golem),
            "Gorgon" => Ok(Self::Gorgon),
            "Graveborn" => Ok(Self::Graveborn),
            "Gremlin" => Ok(Self::Gremlin),
            "Griffin" => Ok(Self::Griffin),
            "Guest" => Ok(Self::Guest),
            "Hag" => Ok(Self::Hag),
            "Halfling" => Ok(Self::Halfling),
            "Hamster" => Ok(Self::Hamster),
            "Harpy" => Ok(Self::Harpy),
            "Head" => Ok(Self::Head),
            "Hedgehog" => Ok(Self::Hedgehog),
            "Hellion" => Ok(Self::Hellion),
            "Hero" => Ok(Self::Hero),
            "Hippo" => Ok(Self::Hippo),
            "Hippogriff" => Ok(Self::Hippogriff),
            "Homarid" => Ok(Self::Homarid),
            "Homunculus" => Ok(Self::Homunculus),
            "Hornet" => Ok(Self::Hornet),
            "Horror" => Ok(Self::Horror),
            "Horse" => Ok(Self::Horse),
            "Human" => Ok(Self::Human),
            "Hydra" => Ok(Self::Hydra),
            "Hyena" => Ok(Self::Hyena),
            "Illusion" => Ok(Self::Illusion),
            "Imp" => Ok(Self::Imp),
            "Incarnation" => Ok(Self::Incarnation),
            "Inkling" => Ok(Self::Inkling),
            "Inquisitor" => Ok(Self::Inquisitor),
            "Insect" => Ok(Self::Insect),
            "Jackal" => Ok(Self::Jackal),
            "Jellyfish" => Ok(Self::Jellyfish),
            "Juggernaut" => Ok(Self::Juggernaut),
            "Kangaroo" => Ok(Self::Kangaroo),
            "Kavu" => Ok(Self::Kavu),
            "Kirin" => Ok(Self::Kirin),
            "Kithkin" => Ok(Self::Kithkin),
            "Knight" => Ok(Self::Knight),
            "Kobold" => Ok(Self::Kobold),
            "Kor" => Ok(Self::Kor),
            "Kraken" => Ok(Self::Kraken),
            "Lamia" => Ok(Self::Lamia),
            "Lammasu" => Ok(Self::Lammasu),
            "Leech" => Ok(Self::Leech),
            "Lemur" => Ok(Self::Lemur),
            "Leviathan" => Ok(Self::Leviathan),
            "Lhurgoyf" => Ok(Self::Lhurgoyf),
            "Licid" => Ok(Self::Licid),
            "Lizard" => Ok(Self::Lizard),
            "Lobster" => Ok(Self::Lobster),
            "Manticore" => Ok(Self::Manticore),
            "Masticore" => Ok(Self::Masticore),
            "Mercenary" => Ok(Self::Mercenary),
            "Merfolk" => Ok(Self::Merfolk),
            "Metathran" => Ok(Self::Metathran),
            "Minion" => Ok(Self::Minion),
            "Minotaur" => Ok(Self::Minotaur),
            "Mite" => Ok(Self::Mite),
            "Mole" => Ok(Self::Mole),
            "Monger" => Ok(Self::Monger),
            "Mongoose" => Ok(Self::Mongoose),
            "Monk" => Ok(Self::Monk),
            "Monkey" => Ok(Self::Monkey),
            "Moogle" => Ok(Self::Moogle),
            "Moonfolk" => Ok(Self::Moonfolk),
            "Mount" => Ok(Self::Mount),
            "Mouse" => Ok(Self::Mouse),
            "Mutant" => Ok(Self::Mutant),
            "Myr" => Ok(Self::Myr),
            "Mystic" => Ok(Self::Mystic),
            "Naga" => Ok(Self::Naga),
            "Nautilus" => Ok(Self::Nautilus),
            "Necron" => Ok(Self::Necron),
            "Nephilim" => Ok(Self::Nephilim),
            "Nightmare" => Ok(Self::Nightmare),
            "Nightstalker" => Ok(Self::Nightstalker),
            "Ninja" => Ok(Self::Ninja),
            "Noble" => Ok(Self::Noble),
            "Noggle" => Ok(Self::Noggle),
            "Nomad" => Ok(Self::Nomad),
            "Nymph" => Ok(Self::Nymph),
            "Octopus" => Ok(Self::Octopus),
            "Ogre" => Ok(Self::Ogre),
            "Ooze" => Ok(Self::Ooze),
            "Orb" => Ok(Self::Orb),
            "Orc" => Ok(Self::Orc),
            "Orgg" => Ok(Self::Orgg),
            "Otter" => Ok(Self::Otter),
            "Ouphe" => Ok(Self::Ouphe),
            "Ox" => Ok(Self::Ox),
            "Oyster" => Ok(Self::Oyster),
            "Pangolin" => Ok(Self::Pangolin),
            "Peasant" => Ok(Self::Peasant),
            "Pegasus" => Ok(Self::Pegasus),
            "Pentavite" => Ok(Self::Pentavite),
            "Performer" => Ok(Self::Performer),
            "Pest" => Ok(Self::Pest),
            "Phelddagrif" => Ok(Self::Phelddagrif),
            "Phoenix" => Ok(Self::Phoenix),
            "Phyrexian" => Ok(Self::Phyrexian),
            "Pilot" => Ok(Self::Pilot),
            "Pincher" => Ok(Self::Pincher),
            "Pirate" => Ok(Self::Pirate),
            "Plant" => Ok(Self::Plant),
            "Porcupine" => Ok(Self::Porcupine),
            "Possum" => Ok(Self::Possum),
            "Praetor" => Ok(Self::Praetor),
            "Primarch" => Ok(Self::Primarch),
            "Prism" => Ok(Self::Prism),
            "Processor" => Ok(Self::Processor),
            "Qu" => Ok(Self::Qu),
            "Rabbit" => Ok(Self::Rabbit),
            "Raccoon" => Ok(Self::Raccoon),
            "Ranger" => Ok(Self::Ranger),
            "Rat" => Ok(Self::Rat),
            "Rebel" => Ok(Self::Rebel),
            "Reflection" => Ok(Self::Reflection),
            "Reveler" => Ok(Self::Reveler),
            "Rhino" => Ok(Self::Rhino),
            "Rigger" => Ok(Self::Rigger),
            "Robot" => Ok(Self::Robot),
            "Rogue" => Ok(Self::Rogue),
            "Rukh" => Ok(Self::Rukh),
            "Sable" => Ok(Self::Sable),
            "Salamander" => Ok(Self::Salamander),
            "Samurai" => Ok(Self::Samurai),
            "Sand" => Ok(Self::Sand),
            "Saproling" => Ok(Self::Saproling),
            "Satyr" => Ok(Self::Satyr),
            "Scarecrow" => Ok(Self::Scarecrow),
            "Scientist" => Ok(Self::Scientist),
            "Scion" => Ok(Self::Scion),
            "Scorpion" => Ok(Self::Scorpion),
            "Scout" => Ok(Self::Scout),
            "Sculpture" => Ok(Self::Sculpture),
            "Seal" => Ok(Self::Seal),
            "Serf" => Ok(Self::Serf),
            "Serpent" => Ok(Self::Serpent),
            "Servo" => Ok(Self::Servo),
            "Shade" => Ok(Self::Shade),
            "Shaman" => Ok(Self::Shaman),
            "Shapeshifter" => Ok(Self::Shapeshifter),
            "Shark" => Ok(Self::Shark),
            "Sheep" => Ok(Self::Sheep),
            "Siren" => Ok(Self::Siren),
            "Skeleton" => Ok(Self::Skeleton),
            "Skunk" => Ok(Self::Skunk),
            "Slith" => Ok(Self::Slith),
            "Sliver" => Ok(Self::Sliver),
            "Sloth" => Ok(Self::Sloth),
            "Slug" => Ok(Self::Slug),
            "Snail" => Ok(Self::Snail),
            "Snake" => Ok(Self::Snake),
            "Soldier" => Ok(Self::Soldier),
            "Soltari" => Ok(Self::Soltari),
            "Spawn" => Ok(Self::Spawn),
            "Specter" => Ok(Self::Specter),
            "Spellshaper" => Ok(Self::Spellshaper),
            "Sphinx" => Ok(Self::Sphinx),
            "Spider" => Ok(Self::Spider),
            "Spike" => Ok(Self::Spike),
            "Spirit" => Ok(Self::Spirit),
            "Splinter" => Ok(Self::Splinter),
            "Sponge" => Ok(Self::Sponge),
            "Spy" => Ok(Self::Spy),
            "Squid" => Ok(Self::Squid),
            "Squirrel" => Ok(Self::Squirrel),
            "Starfish" => Ok(Self::Starfish),
            "Surrakar" => Ok(Self::Surrakar),
            "Survivor" => Ok(Self::Survivor),
            "Symbiote" => Ok(Self::Symbiote),
            "Synth" => Ok(Self::Synth),
            "Teddy" => Ok(Self::Teddy),
            "Tentacle" => Ok(Self::Tentacle),
            "Tetravite" => Ok(Self::Tetravite),
            "Thalakos" => Ok(Self::Thalakos),
            "Thopter" => Ok(Self::Thopter),
            "Thrull" => Ok(Self::Thrull),
            "Tiefling" => Ok(Self::Tiefling),
            "Time Lord" => Ok(Self::TimeLord),
            "Toy" => Ok(Self::Toy),
            "Treefolk" => Ok(Self::Treefolk),
            "Trilobite" => Ok(Self::Trilobite),
            "Triskelavite" => Ok(Self::Triskelavite),
            "Troll" => Ok(Self::Troll),
            "Turtle" => Ok(Self::Turtle),
            "Tyranid" => Ok(Self::Tyranid),
            "Unicorn" => Ok(Self::Unicorn),
            "Urzan" => Ok(Self::Urzan),
            "Vampire" => Ok(Self::Vampire),
            "Varmint" => Ok(Self::Varmint),
            "Vedalken" => Ok(Self::Vedalken),
            "Villain" => Ok(Self::Villain),
            "Volver" => Ok(Self::Volver),
            "Wall" => Ok(Self::Wall),
            "Walrus" => Ok(Self::Walrus),
            "Warlock" => Ok(Self::Warlock),
            "Warrior" => Ok(Self::Warrior),
            "Wasp" => Ok(Self::Wasp),
            "Weasel" => Ok(Self::Weasel),
            "Weird" => Ok(Self::Weird),
            "Werewolf" => Ok(Self::Werewolf),
            "Whale" => Ok(Self::Whale),
            "Wizard" => Ok(Self::Wizard),
            "Wolf" => Ok(Self::Wolf),
            "Wolverine" => Ok(Self::Wolverine),
            "Wombat" => Ok(Self::Wombat),
            "Worm" => Ok(Self::Worm),
            "Wraith" => Ok(Self::Wraith),
            "Wurm" => Ok(Self::Wurm),
            "Yeti" => Ok(Self::Yeti),
            "Zombie" => Ok(Self::Zombie),
            "Zubera" => Ok(Self::Zubera),
            other => Err(format!("Unknown CreatureType: {}", other.to_string())),
        }
    }
}
impl CreatureType {
    fn as_str(&self) -> &'static str {
        match self {
            Self::Advisor => "Advisor",
            Self::Aetherborn => "Aetherborn",
            Self::Alien => "Alien",
            Self::Ally => "Ally",
            Self::Angel => "Angel",
            Self::Antelope => "Antelope",
            Self::Ape => "Ape",
            Self::Archer => "Archer",
            Self::Archon => "Archon",
            Self::Armadillo => "Armadillo",
            Self::Army => "Army",
            Self::Artifact => "Artifact",
            Self::Artificer => "Artificer",
            Self::Assassin => "Assassin",
            Self::AssemblyWorker => "Assembly-Worker",
            Self::Astartes => "Astartes",
            Self::Atog => "Atog",
            Self::Aurochs => "Aurochs",
            Self::Automaton => "Automaton",
            Self::Avatar => "Avatar",
            Self::Azra => "Azra",
            Self::Badger => "Badger",
            Self::Balloon => "Balloon",
            Self::Barbarian => "Barbarian",
            Self::Bard => "Bard",
            Self::Basilisk => "Basilisk",
            Self::Bat => "Bat",
            Self::Bear => "Bear",
            Self::Beast => "Beast",
            Self::Beaver => "Beaver",
            Self::Beeble => "Beeble",
            Self::Beholder => "Beholder",
            Self::Berserker => "Berserker",
            Self::Bird => "Bird",
            Self::Bison => "Bison",
            Self::Blinkmoth => "Blinkmoth",
            Self::Boar => "Boar",
            Self::Brainiac => "Brainiac",
            Self::Bringer => "Bringer",
            Self::Brushwagg => "Brushwagg",
            Self::Ctan => "C'tan",
            Self::Camarid => "Camarid",
            Self::Camel => "Camel",
            Self::Capybara => "Capybara",
            Self::Caribou => "Caribou",
            Self::Carrier => "Carrier",
            Self::Cat => "Cat",
            Self::Centaur => "Centaur",
            Self::Chicken => "Chicken",
            Self::Child => "Child",
            Self::Chimera => "Chimera",
            Self::Citizen => "Citizen",
            Self::Cleric => "Cleric",
            Self::Clown => "Clown",
            Self::Cockatrice => "Cockatrice",
            Self::Construct => "Construct",
            Self::Coward => "Coward",
            Self::Coyote => "Coyote",
            Self::Crab => "Crab",
            Self::Crocodile => "Crocodile",
            Self::Custodes => "Custodes",
            Self::Cyberman => "Cyberman",
            Self::Cyclops => "Cyclops",
            Self::Dalek => "Dalek",
            Self::Dauthi => "Dauthi",
            Self::Demigod => "Demigod",
            Self::Demon => "Demon",
            Self::Deserter => "Deserter",
            Self::Detective => "Detective",
            Self::Devil => "Devil",
            Self::Dinosaur => "Dinosaur",
            Self::Djinn => "Djinn",
            Self::Doctor => "Doctor",
            Self::Dog => "Dog",
            Self::Dragon => "Dragon",
            Self::Drake => "Drake",
            Self::Dreadnought => "Dreadnought",
            Self::Drix => "Drix",
            Self::Drone => "Drone",
            Self::Druid => "Druid",
            Self::Dryad => "Dryad",
            Self::Dwarf => "Dwarf",
            Self::Echidna => "Echidna",
            Self::Efreet => "Efreet",
            Self::Egg => "Egg",
            Self::Elder => "Elder",
            Self::Eldrazi => "Eldrazi",
            Self::Elemental => "Elemental",
            Self::Elephant => "Elephant",
            Self::Elf => "Elf",
            Self::Elk => "Elk",
            Self::Employee => "Employee",
            Self::Eye => "Eye",
            Self::Faerie => "Faerie",
            Self::Ferret => "Ferret",
            Self::Fish => "Fish",
            Self::Flagbearer => "Flagbearer",
            Self::Fox => "Fox",
            Self::Fractal => "Fractal",
            Self::Frog => "Frog",
            Self::Fungus => "Fungus",
            Self::Gamer => "Gamer",
            Self::Gargoyle => "Gargoyle",
            Self::Germ => "Germ",
            Self::Giant => "Giant",
            Self::Gith => "Gith",
            Self::Glimmer => "Glimmer",
            Self::Gnoll => "Gnoll",
            Self::Gnome => "Gnome",
            Self::Goat => "Goat",
            Self::Goblin => "Goblin",
            Self::God => "God",
            Self::Golem => "Golem",
            Self::Gorgon => "Gorgon",
            Self::Graveborn => "Graveborn",
            Self::Gremlin => "Gremlin",
            Self::Griffin => "Griffin",
            Self::Guest => "Guest",
            Self::Hag => "Hag",
            Self::Halfling => "Halfling",
            Self::Hamster => "Hamster",
            Self::Harpy => "Harpy",
            Self::Head => "Head",
            Self::Hedgehog => "Hedgehog",
            Self::Hellion => "Hellion",
            Self::Hero => "Hero",
            Self::Hippo => "Hippo",
            Self::Hippogriff => "Hippogriff",
            Self::Homarid => "Homarid",
            Self::Homunculus => "Homunculus",
            Self::Hornet => "Hornet",
            Self::Horror => "Horror",
            Self::Horse => "Horse",
            Self::Human => "Human",
            Self::Hydra => "Hydra",
            Self::Hyena => "Hyena",
            Self::Illusion => "Illusion",
            Self::Imp => "Imp",
            Self::Incarnation => "Incarnation",
            Self::Inkling => "Inkling",
            Self::Inquisitor => "Inquisitor",
            Self::Insect => "Insect",
            Self::Jackal => "Jackal",
            Self::Jellyfish => "Jellyfish",
            Self::Juggernaut => "Juggernaut",
            Self::Kangaroo => "Kangaroo",
            Self::Kavu => "Kavu",
            Self::Kirin => "Kirin",
            Self::Kithkin => "Kithkin",
            Self::Knight => "Knight",
            Self::Kobold => "Kobold",
            Self::Kor => "Kor",
            Self::Kraken => "Kraken",
            Self::Lamia => "Lamia",
            Self::Lammasu => "Lammasu",
            Self::Leech => "Leech",
            Self::Lemur => "Lemur",
            Self::Leviathan => "Leviathan",
            Self::Lhurgoyf => "Lhurgoyf",
            Self::Licid => "Licid",
            Self::Lizard => "Lizard",
            Self::Lobster => "Lobster",
            Self::Manticore => "Manticore",
            Self::Masticore => "Masticore",
            Self::Mercenary => "Mercenary",
            Self::Merfolk => "Merfolk",
            Self::Metathran => "Metathran",
            Self::Minion => "Minion",
            Self::Minotaur => "Minotaur",
            Self::Mite => "Mite",
            Self::Mole => "Mole",
            Self::Monger => "Monger",
            Self::Mongoose => "Mongoose",
            Self::Monk => "Monk",
            Self::Monkey => "Monkey",
            Self::Moogle => "Moogle",
            Self::Moonfolk => "Moonfolk",
            Self::Mount => "Mount",
            Self::Mouse => "Mouse",
            Self::Mutant => "Mutant",
            Self::Myr => "Myr",
            Self::Mystic => "Mystic",
            Self::Naga => "Naga",
            Self::Nautilus => "Nautilus",
            Self::Necron => "Necron",
            Self::Nephilim => "Nephilim",
            Self::Nightmare => "Nightmare",
            Self::Nightstalker => "Nightstalker",
            Self::Ninja => "Ninja",
            Self::Noble => "Noble",
            Self::Noggle => "Noggle",
            Self::Nomad => "Nomad",
            Self::Nymph => "Nymph",
            Self::Octopus => "Octopus",
            Self::Ogre => "Ogre",
            Self::Ooze => "Ooze",
            Self::Orb => "Orb",
            Self::Orc => "Orc",
            Self::Orgg => "Orgg",
            Self::Otter => "Otter",
            Self::Ouphe => "Ouphe",
            Self::Ox => "Ox",
            Self::Oyster => "Oyster",
            Self::Pangolin => "Pangolin",
            Self::Peasant => "Peasant",
            Self::Pegasus => "Pegasus",
            Self::Pentavite => "Pentavite",
            Self::Performer => "Performer",
            Self::Pest => "Pest",
            Self::Phelddagrif => "Phelddagrif",
            Self::Phoenix => "Phoenix",
            Self::Phyrexian => "Phyrexian",
            Self::Pilot => "Pilot",
            Self::Pincher => "Pincher",
            Self::Pirate => "Pirate",
            Self::Plant => "Plant",
            Self::Porcupine => "Porcupine",
            Self::Possum => "Possum",
            Self::Praetor => "Praetor",
            Self::Primarch => "Primarch",
            Self::Prism => "Prism",
            Self::Processor => "Processor",
            Self::Qu => "Qu",
            Self::Rabbit => "Rabbit",
            Self::Raccoon => "Raccoon",
            Self::Ranger => "Ranger",
            Self::Rat => "Rat",
            Self::Rebel => "Rebel",
            Self::Reflection => "Reflection",
            Self::Reveler => "Reveler",
            Self::Rhino => "Rhino",
            Self::Rigger => "Rigger",
            Self::Robot => "Robot",
            Self::Rogue => "Rogue",
            Self::Rukh => "Rukh",
            Self::Sable => "Sable",
            Self::Salamander => "Salamander",
            Self::Samurai => "Samurai",
            Self::Sand => "Sand",
            Self::Saproling => "Saproling",
            Self::Satyr => "Satyr",
            Self::Scarecrow => "Scarecrow",
            Self::Scientist => "Scientist",
            Self::Scion => "Scion",
            Self::Scorpion => "Scorpion",
            Self::Scout => "Scout",
            Self::Sculpture => "Sculpture",
            Self::Seal => "Seal",
            Self::Serf => "Serf",
            Self::Serpent => "Serpent",
            Self::Servo => "Servo",
            Self::Shade => "Shade",
            Self::Shaman => "Shaman",
            Self::Shapeshifter => "Shapeshifter",
            Self::Shark => "Shark",
            Self::Sheep => "Sheep",
            Self::Siren => "Siren",
            Self::Skeleton => "Skeleton",
            Self::Skunk => "Skunk",
            Self::Slith => "Slith",
            Self::Sliver => "Sliver",
            Self::Sloth => "Sloth",
            Self::Slug => "Slug",
            Self::Snail => "Snail",
            Self::Snake => "Snake",
            Self::Soldier => "Soldier",
            Self::Soltari => "Soltari",
            Self::Spawn => "Spawn",
            Self::Specter => "Specter",
            Self::Spellshaper => "Spellshaper",
            Self::Sphinx => "Sphinx",
            Self::Spider => "Spider",
            Self::Spike => "Spike",
            Self::Spirit => "Spirit",
            Self::Splinter => "Splinter",
            Self::Sponge => "Sponge",
            Self::Spy => "Spy",
            Self::Squid => "Squid",
            Self::Squirrel => "Squirrel",
            Self::Starfish => "Starfish",
            Self::Surrakar => "Surrakar",
            Self::Survivor => "Survivor",
            Self::Symbiote => "Symbiote",
            Self::Synth => "Synth",
            Self::Teddy => "Teddy",
            Self::Tentacle => "Tentacle",
            Self::Tetravite => "Tetravite",
            Self::Thalakos => "Thalakos",
            Self::Thopter => "Thopter",
            Self::Thrull => "Thrull",
            Self::Tiefling => "Tiefling",
            Self::TimeLord => "Time Lord",
            Self::Toy => "Toy",
            Self::Treefolk => "Treefolk",
            Self::Trilobite => "Trilobite",
            Self::Triskelavite => "Triskelavite",
            Self::Troll => "Troll",
            Self::Turtle => "Turtle",
            Self::Tyranid => "Tyranid",
            Self::Unicorn => "Unicorn",
            Self::Urzan => "Urzan",
            Self::Vampire => "Vampire",
            Self::Varmint => "Varmint",
            Self::Vedalken => "Vedalken",
            Self::Villain => "Villain",
            Self::Volver => "Volver",
            Self::Wall => "Wall",
            Self::Walrus => "Walrus",
            Self::Warlock => "Warlock",
            Self::Warrior => "Warrior",
            Self::Wasp => "Wasp",
            Self::Weasel => "Weasel",
            Self::Weird => "Weird",
            Self::Werewolf => "Werewolf",
            Self::Whale => "Whale",
            Self::Wizard => "Wizard",
            Self::Wolf => "Wolf",
            Self::Wolverine => "Wolverine",
            Self::Wombat => "Wombat",
            Self::Worm => "Worm",
            Self::Wraith => "Wraith",
            Self::Wurm => "Wurm",
            Self::Yeti => "Yeti",
            Self::Zombie => "Zombie",
            Self::Zubera => "Zubera",
        }
    }
}
impl std::fmt::Display for CreatureType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
impl CreatureType {
    pub fn all() -> impl Iterator<Item = Self> {
        [
            Self::Advisor,
            Self::Aetherborn,
            Self::Alien,
            Self::Ally,
            Self::Angel,
            Self::Antelope,
            Self::Ape,
            Self::Archer,
            Self::Archon,
            Self::Armadillo,
            Self::Army,
            Self::Artifact,
            Self::Artificer,
            Self::Assassin,
            Self::AssemblyWorker,
            Self::Astartes,
            Self::Atog,
            Self::Aurochs,
            Self::Automaton,
            Self::Avatar,
            Self::Azra,
            Self::Badger,
            Self::Balloon,
            Self::Barbarian,
            Self::Bard,
            Self::Basilisk,
            Self::Bat,
            Self::Bear,
            Self::Beast,
            Self::Beaver,
            Self::Beeble,
            Self::Beholder,
            Self::Berserker,
            Self::Bird,
            Self::Bison,
            Self::Blinkmoth,
            Self::Boar,
            Self::Brainiac,
            Self::Bringer,
            Self::Brushwagg,
            Self::Ctan,
            Self::Camarid,
            Self::Camel,
            Self::Capybara,
            Self::Caribou,
            Self::Carrier,
            Self::Cat,
            Self::Centaur,
            Self::Chicken,
            Self::Child,
            Self::Chimera,
            Self::Citizen,
            Self::Cleric,
            Self::Clown,
            Self::Cockatrice,
            Self::Construct,
            Self::Coward,
            Self::Coyote,
            Self::Crab,
            Self::Crocodile,
            Self::Custodes,
            Self::Cyberman,
            Self::Cyclops,
            Self::Dalek,
            Self::Dauthi,
            Self::Demigod,
            Self::Demon,
            Self::Deserter,
            Self::Detective,
            Self::Devil,
            Self::Dinosaur,
            Self::Djinn,
            Self::Doctor,
            Self::Dog,
            Self::Dragon,
            Self::Drake,
            Self::Dreadnought,
            Self::Drix,
            Self::Drone,
            Self::Druid,
            Self::Dryad,
            Self::Dwarf,
            Self::Echidna,
            Self::Efreet,
            Self::Egg,
            Self::Elder,
            Self::Eldrazi,
            Self::Elemental,
            Self::Elephant,
            Self::Elf,
            Self::Elk,
            Self::Employee,
            Self::Eye,
            Self::Faerie,
            Self::Ferret,
            Self::Fish,
            Self::Flagbearer,
            Self::Fox,
            Self::Fractal,
            Self::Frog,
            Self::Fungus,
            Self::Gamer,
            Self::Gargoyle,
            Self::Germ,
            Self::Giant,
            Self::Gith,
            Self::Glimmer,
            Self::Gnoll,
            Self::Gnome,
            Self::Goat,
            Self::Goblin,
            Self::God,
            Self::Golem,
            Self::Gorgon,
            Self::Graveborn,
            Self::Gremlin,
            Self::Griffin,
            Self::Guest,
            Self::Hag,
            Self::Halfling,
            Self::Hamster,
            Self::Harpy,
            Self::Head,
            Self::Hedgehog,
            Self::Hellion,
            Self::Hero,
            Self::Hippo,
            Self::Hippogriff,
            Self::Homarid,
            Self::Homunculus,
            Self::Hornet,
            Self::Horror,
            Self::Horse,
            Self::Human,
            Self::Hydra,
            Self::Hyena,
            Self::Illusion,
            Self::Imp,
            Self::Incarnation,
            Self::Inkling,
            Self::Inquisitor,
            Self::Insect,
            Self::Jackal,
            Self::Jellyfish,
            Self::Juggernaut,
            Self::Kangaroo,
            Self::Kavu,
            Self::Kirin,
            Self::Kithkin,
            Self::Knight,
            Self::Kobold,
            Self::Kor,
            Self::Kraken,
            Self::Lamia,
            Self::Lammasu,
            Self::Leech,
            Self::Lemur,
            Self::Leviathan,
            Self::Lhurgoyf,
            Self::Licid,
            Self::Lizard,
            Self::Lobster,
            Self::Manticore,
            Self::Masticore,
            Self::Mercenary,
            Self::Merfolk,
            Self::Metathran,
            Self::Minion,
            Self::Minotaur,
            Self::Mite,
            Self::Mole,
            Self::Monger,
            Self::Mongoose,
            Self::Monk,
            Self::Monkey,
            Self::Moogle,
            Self::Moonfolk,
            Self::Mount,
            Self::Mouse,
            Self::Mutant,
            Self::Myr,
            Self::Mystic,
            Self::Naga,
            Self::Nautilus,
            Self::Necron,
            Self::Nephilim,
            Self::Nightmare,
            Self::Nightstalker,
            Self::Ninja,
            Self::Noble,
            Self::Noggle,
            Self::Nomad,
            Self::Nymph,
            Self::Octopus,
            Self::Ogre,
            Self::Ooze,
            Self::Orb,
            Self::Orc,
            Self::Orgg,
            Self::Otter,
            Self::Ouphe,
            Self::Ox,
            Self::Oyster,
            Self::Pangolin,
            Self::Peasant,
            Self::Pegasus,
            Self::Pentavite,
            Self::Performer,
            Self::Pest,
            Self::Phelddagrif,
            Self::Phoenix,
            Self::Phyrexian,
            Self::Pilot,
            Self::Pincher,
            Self::Pirate,
            Self::Plant,
            Self::Porcupine,
            Self::Possum,
            Self::Praetor,
            Self::Primarch,
            Self::Prism,
            Self::Processor,
            Self::Qu,
            Self::Rabbit,
            Self::Raccoon,
            Self::Ranger,
            Self::Rat,
            Self::Rebel,
            Self::Reflection,
            Self::Reveler,
            Self::Rhino,
            Self::Rigger,
            Self::Robot,
            Self::Rogue,
            Self::Rukh,
            Self::Sable,
            Self::Salamander,
            Self::Samurai,
            Self::Sand,
            Self::Saproling,
            Self::Satyr,
            Self::Scarecrow,
            Self::Scientist,
            Self::Scion,
            Self::Scorpion,
            Self::Scout,
            Self::Sculpture,
            Self::Seal,
            Self::Serf,
            Self::Serpent,
            Self::Servo,
            Self::Shade,
            Self::Shaman,
            Self::Shapeshifter,
            Self::Shark,
            Self::Sheep,
            Self::Siren,
            Self::Skeleton,
            Self::Skunk,
            Self::Slith,
            Self::Sliver,
            Self::Sloth,
            Self::Slug,
            Self::Snail,
            Self::Snake,
            Self::Soldier,
            Self::Soltari,
            Self::Spawn,
            Self::Specter,
            Self::Spellshaper,
            Self::Sphinx,
            Self::Spider,
            Self::Spike,
            Self::Spirit,
            Self::Splinter,
            Self::Sponge,
            Self::Spy,
            Self::Squid,
            Self::Squirrel,
            Self::Starfish,
            Self::Surrakar,
            Self::Survivor,
            Self::Symbiote,
            Self::Synth,
            Self::Teddy,
            Self::Tentacle,
            Self::Tetravite,
            Self::Thalakos,
            Self::Thopter,
            Self::Thrull,
            Self::Tiefling,
            Self::TimeLord,
            Self::Toy,
            Self::Treefolk,
            Self::Trilobite,
            Self::Triskelavite,
            Self::Troll,
            Self::Turtle,
            Self::Tyranid,
            Self::Unicorn,
            Self::Urzan,
            Self::Vampire,
            Self::Varmint,
            Self::Vedalken,
            Self::Villain,
            Self::Volver,
            Self::Wall,
            Self::Walrus,
            Self::Warlock,
            Self::Warrior,
            Self::Wasp,
            Self::Weasel,
            Self::Weird,
            Self::Werewolf,
            Self::Whale,
            Self::Wizard,
            Self::Wolf,
            Self::Wolverine,
            Self::Wombat,
            Self::Worm,
            Self::Wraith,
            Self::Wurm,
            Self::Yeti,
            Self::Zombie,
            Self::Zubera,
        ]
        .into_iter()
    }
}
