#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CreatureType {
    Advisor,
    Aetherborn,
    Alien,
    Ally,
    Angel,
    Antelope,
    Ape,
    Archer,
    Archon,
    Armadillo,
    Army,
    Artificer,
    Assassin,
    AssemblyWorker,
    Astartes,
    Atog,
    Aurochs,
    Automaton,
    Avatar,
    Azra,
    Badger,
    Balloon,
    Barbarian,
    Bard,
    Basilisk,
    Bat,
    Bear,
    Beast,
    Beaver,
    Beeble,
    Beholder,
    Berserker,
    Bird,
    Blinkmoth,
    Boar,
    Brainiac,
    Bringer,
    Brushwagg,
    Ctan,
    Camarid,
    Camel,
    Capybara,
    Caribou,
    Carrier,
    Cat,
    Centaur,
    Chicken,
    Child,
    Chimera,
    Citizen,
    Cleric,
    Clown,
    Cockatrice,
    Construct,
    Coward,
    Coyote,
    Crab,
    Crocodile,
    Custodes,
    Cyberman,
    Cyclops,
    Dalek,
    Dauthi,
    Demigod,
    Demon,
    Deserter,
    Detective,
    Devil,
    Dinosaur,
    Djinn,
    Doctor,
    Dog,
    Dragon,
    Drake,
    Dreadnought,
    Drone,
    Druid,
    Dryad,
    Dwarf,
    Efreet,
    Egg,
    Elder,
    Eldrazi,
    Elemental,
    Elephant,
    Elf,
    Elk,
    Employee,
    Eye,
    Faerie,
    Ferret,
    Fish,
    Flagbearer,
    Fox,
    Fractal,
    Frog,
    Fungus,
    Gamer,
    Gargoyle,
    Germ,
    Giant,
    Gith,
    Glimmer,
    Gnoll,
    Gnome,
    Goat,
    Goblin,
    God,
    Golem,
    Gorgon,
    Graveborn,
    Gremlin,
    Griffin,
    Guest,
    Hag,
    Halfling,
    Hamster,
    Harpy,
    Head,
    Hellion,
    Hero,
    Hippo,
    Hippogriff,
    Homarid,
    Homunculus,
    Hornet,
    Horror,
    Horse,
    Human,
    Hydra,
    Hyena,
    Illusion,
    Imp,
    Incarnation,
    Inkling,
    Inquisitor,
    Insect,
    Jackal,
    Jellyfish,
    Juggernaut,
    Kavu,
    Kirin,
    Kithkin,
    Knight,
    Kobold,
    Kor,
    Kraken,
    Lamia,
    Lammasu,
    Leech,
    Leviathan,
    Lhurgoyf,
    Licid,
    Lizard,
    Manticore,
    Masticore,
    Mercenary,
    Merfolk,
    Metathran,
    Minion,
    Minotaur,
    Mite,
    Mole,
    Monger,
    Mongoose,
    Monk,
    Monkey,
    Moonfolk,
    Mount,
    Mouse,
    Mutant,
    Myr,
    Mystic,
    Naga,
    Nautilus,
    Necron,
    Nephilim,
    Nightmare,
    Nightstalker,
    Ninja,
    Noble,
    Noggle,
    Nomad,
    Nymph,
    Octopus,
    Ogre,
    Ooze,
    Orb,
    Orc,
    Orgg,
    Otter,
    Ouphe,
    Ox,
    Oyster,
    Pangolin,
    Peasant,
    Pegasus,
    Pentavite,
    Performer,
    Pest,
    Phelddagrif,
    Phoenix,
    Phyrexian,
    Pilot,
    Pincher,
    Pirate,
    Plant,
    Porcupine,
    Possum,
    Praetor,
    Primarch,
    Prism,
    Processor,
    Rabbit,
    Raccoon,
    Ranger,
    Rat,
    Rebel,
    Reflection,
    Reveler,
    Rhino,
    Rigger,
    Robot,
    Rogue,
    Rukh,
    Sable,
    Salamander,
    Samurai,
    Sand,
    Saproling,
    Satyr,
    Scarecrow,
    Scientist,
    Scion,
    Scorpion,
    Scout,
    Sculpture,
    Serf,
    Serpent,
    Servo,
    Shade,
    Shaman,
    Shapeshifter,
    Shark,
    Sheep,
    Siren,
    Skeleton,
    Skunk,
    Slith,
    Sliver,
    Sloth,
    Slug,
    Snail,
    Snake,
    Soldier,
    Soltari,
    Spawn,
    Specter,
    Spellshaper,
    Sphinx,
    Spider,
    Spike,
    Spirit,
    Splinter,
    Sponge,
    Spy,
    Squid,
    Squirrel,
    Starfish,
    Surrakar,
    Survivor,
    Synth,
    Teddy,
    Tentacle,
    Tetravite,
    Thalakos,
    Thopter,
    Thrull,
    Tiefling,
    TimeLord,
    Toy,
    Treefolk,
    Trilobite,
    Triskelavite,
    Troll,
    Turtle,
    Tyranid,
    Unicorn,
    Urzan,
    Vampire,
    Varmint,
    Vedalken,
    Volver,
    Wall,
    Walrus,
    Warlock,
    Warrior,
    Wasp,
    Weasel,
    Weird,
    Werewolf,
    Whale,
    Wizard,
    Wolf,
    Wolverine,
    Wombat,
    Worm,
    Wraith,
    Wurm,
    Yeti,
    Zombie,
    Zubera,
}

impl std::str::FromStr for CreatureType {
    type Err = crate::ParsingError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Advisor" => Ok(Self::Advisor),
            "Aetherborn" => Ok(Self::Aetherborn),
            "Alien" => Ok(Self::Alien),
            "Ally" => Ok(Self::Ally),
            "Angel" => Ok(Self::Angel),
            "Antelope" => Ok(Self::Antelope),
            "Ape" => Ok(Self::Ape),
            "Archer" => Ok(Self::Archer),
            "Archon" => Ok(Self::Archon),
            "Armadillo" => Ok(Self::Armadillo),
            "Army" => Ok(Self::Army),
            "Artificer" => Ok(Self::Artificer),
            "Assassin" => Ok(Self::Assassin),
            "Assembly-Worker" => Ok(Self::AssemblyWorker),
            "Astartes" => Ok(Self::Astartes),
            "Atog" => Ok(Self::Atog),
            "Aurochs" => Ok(Self::Aurochs),
            "Automaton" => Ok(Self::Automaton),
            "Avatar" => Ok(Self::Avatar),
            "Azra" => Ok(Self::Azra),
            "Badger" => Ok(Self::Badger),
            "Balloon" => Ok(Self::Balloon),
            "Barbarian" => Ok(Self::Barbarian),
            "Bard" => Ok(Self::Bard),
            "Basilisk" => Ok(Self::Basilisk),
            "Bat" => Ok(Self::Bat),
            "Bear" => Ok(Self::Bear),
            "Beast" => Ok(Self::Beast),
            "Beaver" => Ok(Self::Beaver),
            "Beeble" => Ok(Self::Beeble),
            "Beholder" => Ok(Self::Beholder),
            "Berserker" => Ok(Self::Berserker),
            "Bird" => Ok(Self::Bird),
            "Blinkmoth" => Ok(Self::Blinkmoth),
            "Boar" => Ok(Self::Boar),
            "Brainiac" => Ok(Self::Brainiac),
            "Bringer" => Ok(Self::Bringer),
            "Brushwagg" => Ok(Self::Brushwagg),
            "C'tan" => Ok(Self::Ctan),
            "Camarid" => Ok(Self::Camarid),
            "Camel" => Ok(Self::Camel),
            "Capybara" => Ok(Self::Capybara),
            "Caribou" => Ok(Self::Caribou),
            "Carrier" => Ok(Self::Carrier),
            "Cat" => Ok(Self::Cat),
            "Centaur" => Ok(Self::Centaur),
            "Chicken" => Ok(Self::Chicken),
            "Child" => Ok(Self::Child),
            "Chimera" => Ok(Self::Chimera),
            "Citizen" => Ok(Self::Citizen),
            "Cleric" => Ok(Self::Cleric),
            "Clown" => Ok(Self::Clown),
            "Cockatrice" => Ok(Self::Cockatrice),
            "Construct" => Ok(Self::Construct),
            "Coward" => Ok(Self::Coward),
            "Coyote" => Ok(Self::Coyote),
            "Crab" => Ok(Self::Crab),
            "Crocodile" => Ok(Self::Crocodile),
            "Custodes" => Ok(Self::Custodes),
            "Cyberman" => Ok(Self::Cyberman),
            "Cyclops" => Ok(Self::Cyclops),
            "Dalek" => Ok(Self::Dalek),
            "Dauthi" => Ok(Self::Dauthi),
            "Demigod" => Ok(Self::Demigod),
            "Demon" => Ok(Self::Demon),
            "Deserter" => Ok(Self::Deserter),
            "Detective" => Ok(Self::Detective),
            "Devil" => Ok(Self::Devil),
            "Dinosaur" => Ok(Self::Dinosaur),
            "Djinn" => Ok(Self::Djinn),
            "Doctor" => Ok(Self::Doctor),
            "Dog" => Ok(Self::Dog),
            "Dragon" => Ok(Self::Dragon),
            "Drake" => Ok(Self::Drake),
            "Dreadnought" => Ok(Self::Dreadnought),
            "Drone" => Ok(Self::Drone),
            "Druid" => Ok(Self::Druid),
            "Dryad" => Ok(Self::Dryad),
            "Dwarf" => Ok(Self::Dwarf),
            "Efreet" => Ok(Self::Efreet),
            "Egg" => Ok(Self::Egg),
            "Elder" => Ok(Self::Elder),
            "Eldrazi" => Ok(Self::Eldrazi),
            "Elemental" => Ok(Self::Elemental),
            "Elephant" => Ok(Self::Elephant),
            "Elf" => Ok(Self::Elf),
            "Elk" => Ok(Self::Elk),
            "Employee" => Ok(Self::Employee),
            "Eye" => Ok(Self::Eye),
            "Faerie" => Ok(Self::Faerie),
            "Ferret" => Ok(Self::Ferret),
            "Fish" => Ok(Self::Fish),
            "Flagbearer" => Ok(Self::Flagbearer),
            "Fox" => Ok(Self::Fox),
            "Fractal" => Ok(Self::Fractal),
            "Frog" => Ok(Self::Frog),
            "Fungus" => Ok(Self::Fungus),
            "Gamer" => Ok(Self::Gamer),
            "Gargoyle" => Ok(Self::Gargoyle),
            "Germ" => Ok(Self::Germ),
            "Giant" => Ok(Self::Giant),
            "Gith" => Ok(Self::Gith),
            "Glimmer" => Ok(Self::Glimmer),
            "Gnoll" => Ok(Self::Gnoll),
            "Gnome" => Ok(Self::Gnome),
            "Goat" => Ok(Self::Goat),
            "Goblin" => Ok(Self::Goblin),
            "God" => Ok(Self::God),
            "Golem" => Ok(Self::Golem),
            "Gorgon" => Ok(Self::Gorgon),
            "Graveborn" => Ok(Self::Graveborn),
            "Gremlin" => Ok(Self::Gremlin),
            "Griffin" => Ok(Self::Griffin),
            "Guest" => Ok(Self::Guest),
            "Hag" => Ok(Self::Hag),
            "Halfling" => Ok(Self::Halfling),
            "Hamster" => Ok(Self::Hamster),
            "Harpy" => Ok(Self::Harpy),
            "Head" => Ok(Self::Head),
            "Hellion" => Ok(Self::Hellion),
            "Hero" => Ok(Self::Hero),
            "Hippo" => Ok(Self::Hippo),
            "Hippogriff" => Ok(Self::Hippogriff),
            "Homarid" => Ok(Self::Homarid),
            "Homunculus" => Ok(Self::Homunculus),
            "Hornet" => Ok(Self::Hornet),
            "Horror" => Ok(Self::Horror),
            "Horse" => Ok(Self::Horse),
            "Human" => Ok(Self::Human),
            "Hydra" => Ok(Self::Hydra),
            "Hyena" => Ok(Self::Hyena),
            "Illusion" => Ok(Self::Illusion),
            "Imp" => Ok(Self::Imp),
            "Incarnation" => Ok(Self::Incarnation),
            "Inkling" => Ok(Self::Inkling),
            "Inquisitor" => Ok(Self::Inquisitor),
            "Insect" => Ok(Self::Insect),
            "Jackal" => Ok(Self::Jackal),
            "Jellyfish" => Ok(Self::Jellyfish),
            "Juggernaut" => Ok(Self::Juggernaut),
            "Kavu" => Ok(Self::Kavu),
            "Kirin" => Ok(Self::Kirin),
            "Kithkin" => Ok(Self::Kithkin),
            "Knight" => Ok(Self::Knight),
            "Kobold" => Ok(Self::Kobold),
            "Kor" => Ok(Self::Kor),
            "Kraken" => Ok(Self::Kraken),
            "Lamia" => Ok(Self::Lamia),
            "Lammasu" => Ok(Self::Lammasu),
            "Leech" => Ok(Self::Leech),
            "Leviathan" => Ok(Self::Leviathan),
            "Lhurgoyf" => Ok(Self::Lhurgoyf),
            "Licid" => Ok(Self::Licid),
            "Lizard" => Ok(Self::Lizard),
            "Manticore" => Ok(Self::Manticore),
            "Masticore" => Ok(Self::Masticore),
            "Mercenary" => Ok(Self::Mercenary),
            "Merfolk" => Ok(Self::Merfolk),
            "Metathran" => Ok(Self::Metathran),
            "Minion" => Ok(Self::Minion),
            "Minotaur" => Ok(Self::Minotaur),
            "Mite" => Ok(Self::Mite),
            "Mole" => Ok(Self::Mole),
            "Monger" => Ok(Self::Monger),
            "Mongoose" => Ok(Self::Mongoose),
            "Monk" => Ok(Self::Monk),
            "Monkey" => Ok(Self::Monkey),
            "Moonfolk" => Ok(Self::Moonfolk),
            "Mount" => Ok(Self::Mount),
            "Mouse" => Ok(Self::Mouse),
            "Mutant" => Ok(Self::Mutant),
            "Myr" => Ok(Self::Myr),
            "Mystic" => Ok(Self::Mystic),
            "Naga" => Ok(Self::Naga),
            "Nautilus" => Ok(Self::Nautilus),
            "Necron" => Ok(Self::Necron),
            "Nephilim" => Ok(Self::Nephilim),
            "Nightmare" => Ok(Self::Nightmare),
            "Nightstalker" => Ok(Self::Nightstalker),
            "Ninja" => Ok(Self::Ninja),
            "Noble" => Ok(Self::Noble),
            "Noggle" => Ok(Self::Noggle),
            "Nomad" => Ok(Self::Nomad),
            "Nymph" => Ok(Self::Nymph),
            "Octopus" => Ok(Self::Octopus),
            "Ogre" => Ok(Self::Ogre),
            "Ooze" => Ok(Self::Ooze),
            "Orb" => Ok(Self::Orb),
            "Orc" => Ok(Self::Orc),
            "Orgg" => Ok(Self::Orgg),
            "Otter" => Ok(Self::Otter),
            "Ouphe" => Ok(Self::Ouphe),
            "Ox" => Ok(Self::Ox),
            "Oyster" => Ok(Self::Oyster),
            "Pangolin" => Ok(Self::Pangolin),
            "Peasant" => Ok(Self::Peasant),
            "Pegasus" => Ok(Self::Pegasus),
            "Pentavite" => Ok(Self::Pentavite),
            "Performer" => Ok(Self::Performer),
            "Pest" => Ok(Self::Pest),
            "Phelddagrif" => Ok(Self::Phelddagrif),
            "Phoenix" => Ok(Self::Phoenix),
            "Phyrexian" => Ok(Self::Phyrexian),
            "Pilot" => Ok(Self::Pilot),
            "Pincher" => Ok(Self::Pincher),
            "Pirate" => Ok(Self::Pirate),
            "Plant" => Ok(Self::Plant),
            "Porcupine" => Ok(Self::Porcupine),
            "Possum" => Ok(Self::Possum),
            "Praetor" => Ok(Self::Praetor),
            "Primarch" => Ok(Self::Primarch),
            "Prism" => Ok(Self::Prism),
            "Processor" => Ok(Self::Processor),
            "Rabbit" => Ok(Self::Rabbit),
            "Raccoon" => Ok(Self::Raccoon),
            "Ranger" => Ok(Self::Ranger),
            "Rat" => Ok(Self::Rat),
            "Rebel" => Ok(Self::Rebel),
            "Reflection" => Ok(Self::Reflection),
            "Reveler" => Ok(Self::Reveler),
            "Rhino" => Ok(Self::Rhino),
            "Rigger" => Ok(Self::Rigger),
            "Robot" => Ok(Self::Robot),
            "Rogue" => Ok(Self::Rogue),
            "Rukh" => Ok(Self::Rukh),
            "Sable" => Ok(Self::Sable),
            "Salamander" => Ok(Self::Salamander),
            "Samurai" => Ok(Self::Samurai),
            "Sand" => Ok(Self::Sand),
            "Saproling" => Ok(Self::Saproling),
            "Satyr" => Ok(Self::Satyr),
            "Scarecrow" => Ok(Self::Scarecrow),
            "Scientist" => Ok(Self::Scientist),
            "Scion" => Ok(Self::Scion),
            "Scorpion" => Ok(Self::Scorpion),
            "Scout" => Ok(Self::Scout),
            "Sculpture" => Ok(Self::Sculpture),
            "Serf" => Ok(Self::Serf),
            "Serpent" => Ok(Self::Serpent),
            "Servo" => Ok(Self::Servo),
            "Shade" => Ok(Self::Shade),
            "Shaman" => Ok(Self::Shaman),
            "Shapeshifter" => Ok(Self::Shapeshifter),
            "Shark" => Ok(Self::Shark),
            "Sheep" => Ok(Self::Sheep),
            "Siren" => Ok(Self::Siren),
            "Skeleton" => Ok(Self::Skeleton),
            "Skunk" => Ok(Self::Skunk),
            "Slith" => Ok(Self::Slith),
            "Sliver" => Ok(Self::Sliver),
            "Sloth" => Ok(Self::Sloth),
            "Slug" => Ok(Self::Slug),
            "Snail" => Ok(Self::Snail),
            "Snake" => Ok(Self::Snake),
            "Soldier" => Ok(Self::Soldier),
            "Soltari" => Ok(Self::Soltari),
            "Spawn" => Ok(Self::Spawn),
            "Specter" => Ok(Self::Specter),
            "Spellshaper" => Ok(Self::Spellshaper),
            "Sphinx" => Ok(Self::Sphinx),
            "Spider" => Ok(Self::Spider),
            "Spike" => Ok(Self::Spike),
            "Spirit" => Ok(Self::Spirit),
            "Splinter" => Ok(Self::Splinter),
            "Sponge" => Ok(Self::Sponge),
            "Spy" => Ok(Self::Spy),
            "Squid" => Ok(Self::Squid),
            "Squirrel" => Ok(Self::Squirrel),
            "Starfish" => Ok(Self::Starfish),
            "Surrakar" => Ok(Self::Surrakar),
            "Survivor" => Ok(Self::Survivor),
            "Synth" => Ok(Self::Synth),
            "Teddy" => Ok(Self::Teddy),
            "Tentacle" => Ok(Self::Tentacle),
            "Tetravite" => Ok(Self::Tetravite),
            "Thalakos" => Ok(Self::Thalakos),
            "Thopter" => Ok(Self::Thopter),
            "Thrull" => Ok(Self::Thrull),
            "Tiefling" => Ok(Self::Tiefling),
            "Time Lord" => Ok(Self::TimeLord),
            "Toy" => Ok(Self::Toy),
            "Treefolk" => Ok(Self::Treefolk),
            "Trilobite" => Ok(Self::Trilobite),
            "Triskelavite" => Ok(Self::Triskelavite),
            "Troll" => Ok(Self::Troll),
            "Turtle" => Ok(Self::Turtle),
            "Tyranid" => Ok(Self::Tyranid),
            "Unicorn" => Ok(Self::Unicorn),
            "Urzan" => Ok(Self::Urzan),
            "Vampire" => Ok(Self::Vampire),
            "Varmint" => Ok(Self::Varmint),
            "Vedalken" => Ok(Self::Vedalken),
            "Volver" => Ok(Self::Volver),
            "Wall" => Ok(Self::Wall),
            "Walrus" => Ok(Self::Walrus),
            "Warlock" => Ok(Self::Warlock),
            "Warrior" => Ok(Self::Warrior),
            "Wasp" => Ok(Self::Wasp),
            "Weasel" => Ok(Self::Weasel),
            "Weird" => Ok(Self::Weird),
            "Werewolf" => Ok(Self::Werewolf),
            "Whale" => Ok(Self::Whale),
            "Wizard" => Ok(Self::Wizard),
            "Wolf" => Ok(Self::Wolf),
            "Wolverine" => Ok(Self::Wolverine),
            "Wombat" => Ok(Self::Wombat),
            "Worm" => Ok(Self::Worm),
            "Wraith" => Ok(Self::Wraith),
            "Wurm" => Ok(Self::Wurm),
            "Yeti" => Ok(Self::Yeti),
            "Zombie" => Ok(Self::Zombie),
            "Zubera" => Ok(Self::Zubera),
            _ => Err(crate::ParsingError::UnknownInput { input: s.to_string() }),
        }
    }
}

impl std::fmt::Display for CreatureType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self {
            Self::Advisor => write!(f, "Advisor"),
            Self::Aetherborn => write!(f, "Aetherborn"),
            Self::Alien => write!(f, "Alien"),
            Self::Ally => write!(f, "Ally"),
            Self::Angel => write!(f, "Angel"),
            Self::Antelope => write!(f, "Antelope"),
            Self::Ape => write!(f, "Ape"),
            Self::Archer => write!(f, "Archer"),
            Self::Archon => write!(f, "Archon"),
            Self::Armadillo => write!(f, "Armadillo"),
            Self::Army => write!(f, "Army"),
            Self::Artificer => write!(f, "Artificer"),
            Self::Assassin => write!(f, "Assassin"),
            Self::AssemblyWorker => write!(f, "Assembly-Worker"),
            Self::Astartes => write!(f, "Astartes"),
            Self::Atog => write!(f, "Atog"),
            Self::Aurochs => write!(f, "Aurochs"),
            Self::Automaton => write!(f, "Automaton"),
            Self::Avatar => write!(f, "Avatar"),
            Self::Azra => write!(f, "Azra"),
            Self::Badger => write!(f, "Badger"),
            Self::Balloon => write!(f, "Balloon"),
            Self::Barbarian => write!(f, "Barbarian"),
            Self::Bard => write!(f, "Bard"),
            Self::Basilisk => write!(f, "Basilisk"),
            Self::Bat => write!(f, "Bat"),
            Self::Bear => write!(f, "Bear"),
            Self::Beast => write!(f, "Beast"),
            Self::Beaver => write!(f, "Beaver"),
            Self::Beeble => write!(f, "Beeble"),
            Self::Beholder => write!(f, "Beholder"),
            Self::Berserker => write!(f, "Berserker"),
            Self::Bird => write!(f, "Bird"),
            Self::Blinkmoth => write!(f, "Blinkmoth"),
            Self::Boar => write!(f, "Boar"),
            Self::Brainiac => write!(f, "Brainiac"),
            Self::Bringer => write!(f, "Bringer"),
            Self::Brushwagg => write!(f, "Brushwagg"),
            Self::Ctan => write!(f, "C'tan"),
            Self::Camarid => write!(f, "Camarid"),
            Self::Camel => write!(f, "Camel"),
            Self::Capybara => write!(f, "Capybara"),
            Self::Caribou => write!(f, "Caribou"),
            Self::Carrier => write!(f, "Carrier"),
            Self::Cat => write!(f, "Cat"),
            Self::Centaur => write!(f, "Centaur"),
            Self::Chicken => write!(f, "Chicken"),
            Self::Child => write!(f, "Child"),
            Self::Chimera => write!(f, "Chimera"),
            Self::Citizen => write!(f, "Citizen"),
            Self::Cleric => write!(f, "Cleric"),
            Self::Clown => write!(f, "Clown"),
            Self::Cockatrice => write!(f, "Cockatrice"),
            Self::Construct => write!(f, "Construct"),
            Self::Coward => write!(f, "Coward"),
            Self::Coyote => write!(f, "Coyote"),
            Self::Crab => write!(f, "Crab"),
            Self::Crocodile => write!(f, "Crocodile"),
            Self::Custodes => write!(f, "Custodes"),
            Self::Cyberman => write!(f, "Cyberman"),
            Self::Cyclops => write!(f, "Cyclops"),
            Self::Dalek => write!(f, "Dalek"),
            Self::Dauthi => write!(f, "Dauthi"),
            Self::Demigod => write!(f, "Demigod"),
            Self::Demon => write!(f, "Demon"),
            Self::Deserter => write!(f, "Deserter"),
            Self::Detective => write!(f, "Detective"),
            Self::Devil => write!(f, "Devil"),
            Self::Dinosaur => write!(f, "Dinosaur"),
            Self::Djinn => write!(f, "Djinn"),
            Self::Doctor => write!(f, "Doctor"),
            Self::Dog => write!(f, "Dog"),
            Self::Dragon => write!(f, "Dragon"),
            Self::Drake => write!(f, "Drake"),
            Self::Dreadnought => write!(f, "Dreadnought"),
            Self::Drone => write!(f, "Drone"),
            Self::Druid => write!(f, "Druid"),
            Self::Dryad => write!(f, "Dryad"),
            Self::Dwarf => write!(f, "Dwarf"),
            Self::Efreet => write!(f, "Efreet"),
            Self::Egg => write!(f, "Egg"),
            Self::Elder => write!(f, "Elder"),
            Self::Eldrazi => write!(f, "Eldrazi"),
            Self::Elemental => write!(f, "Elemental"),
            Self::Elephant => write!(f, "Elephant"),
            Self::Elf => write!(f, "Elf"),
            Self::Elk => write!(f, "Elk"),
            Self::Employee => write!(f, "Employee"),
            Self::Eye => write!(f, "Eye"),
            Self::Faerie => write!(f, "Faerie"),
            Self::Ferret => write!(f, "Ferret"),
            Self::Fish => write!(f, "Fish"),
            Self::Flagbearer => write!(f, "Flagbearer"),
            Self::Fox => write!(f, "Fox"),
            Self::Fractal => write!(f, "Fractal"),
            Self::Frog => write!(f, "Frog"),
            Self::Fungus => write!(f, "Fungus"),
            Self::Gamer => write!(f, "Gamer"),
            Self::Gargoyle => write!(f, "Gargoyle"),
            Self::Germ => write!(f, "Germ"),
            Self::Giant => write!(f, "Giant"),
            Self::Gith => write!(f, "Gith"),
            Self::Glimmer => write!(f, "Glimmer"),
            Self::Gnoll => write!(f, "Gnoll"),
            Self::Gnome => write!(f, "Gnome"),
            Self::Goat => write!(f, "Goat"),
            Self::Goblin => write!(f, "Goblin"),
            Self::God => write!(f, "God"),
            Self::Golem => write!(f, "Golem"),
            Self::Gorgon => write!(f, "Gorgon"),
            Self::Graveborn => write!(f, "Graveborn"),
            Self::Gremlin => write!(f, "Gremlin"),
            Self::Griffin => write!(f, "Griffin"),
            Self::Guest => write!(f, "Guest"),
            Self::Hag => write!(f, "Hag"),
            Self::Halfling => write!(f, "Halfling"),
            Self::Hamster => write!(f, "Hamster"),
            Self::Harpy => write!(f, "Harpy"),
            Self::Head => write!(f, "Head"),
            Self::Hellion => write!(f, "Hellion"),
            Self::Hero => write!(f, "Hero"),
            Self::Hippo => write!(f, "Hippo"),
            Self::Hippogriff => write!(f, "Hippogriff"),
            Self::Homarid => write!(f, "Homarid"),
            Self::Homunculus => write!(f, "Homunculus"),
            Self::Hornet => write!(f, "Hornet"),
            Self::Horror => write!(f, "Horror"),
            Self::Horse => write!(f, "Horse"),
            Self::Human => write!(f, "Human"),
            Self::Hydra => write!(f, "Hydra"),
            Self::Hyena => write!(f, "Hyena"),
            Self::Illusion => write!(f, "Illusion"),
            Self::Imp => write!(f, "Imp"),
            Self::Incarnation => write!(f, "Incarnation"),
            Self::Inkling => write!(f, "Inkling"),
            Self::Inquisitor => write!(f, "Inquisitor"),
            Self::Insect => write!(f, "Insect"),
            Self::Jackal => write!(f, "Jackal"),
            Self::Jellyfish => write!(f, "Jellyfish"),
            Self::Juggernaut => write!(f, "Juggernaut"),
            Self::Kavu => write!(f, "Kavu"),
            Self::Kirin => write!(f, "Kirin"),
            Self::Kithkin => write!(f, "Kithkin"),
            Self::Knight => write!(f, "Knight"),
            Self::Kobold => write!(f, "Kobold"),
            Self::Kor => write!(f, "Kor"),
            Self::Kraken => write!(f, "Kraken"),
            Self::Lamia => write!(f, "Lamia"),
            Self::Lammasu => write!(f, "Lammasu"),
            Self::Leech => write!(f, "Leech"),
            Self::Leviathan => write!(f, "Leviathan"),
            Self::Lhurgoyf => write!(f, "Lhurgoyf"),
            Self::Licid => write!(f, "Licid"),
            Self::Lizard => write!(f, "Lizard"),
            Self::Manticore => write!(f, "Manticore"),
            Self::Masticore => write!(f, "Masticore"),
            Self::Mercenary => write!(f, "Mercenary"),
            Self::Merfolk => write!(f, "Merfolk"),
            Self::Metathran => write!(f, "Metathran"),
            Self::Minion => write!(f, "Minion"),
            Self::Minotaur => write!(f, "Minotaur"),
            Self::Mite => write!(f, "Mite"),
            Self::Mole => write!(f, "Mole"),
            Self::Monger => write!(f, "Monger"),
            Self::Mongoose => write!(f, "Mongoose"),
            Self::Monk => write!(f, "Monk"),
            Self::Monkey => write!(f, "Monkey"),
            Self::Moonfolk => write!(f, "Moonfolk"),
            Self::Mount => write!(f, "Mount"),
            Self::Mouse => write!(f, "Mouse"),
            Self::Mutant => write!(f, "Mutant"),
            Self::Myr => write!(f, "Myr"),
            Self::Mystic => write!(f, "Mystic"),
            Self::Naga => write!(f, "Naga"),
            Self::Nautilus => write!(f, "Nautilus"),
            Self::Necron => write!(f, "Necron"),
            Self::Nephilim => write!(f, "Nephilim"),
            Self::Nightmare => write!(f, "Nightmare"),
            Self::Nightstalker => write!(f, "Nightstalker"),
            Self::Ninja => write!(f, "Ninja"),
            Self::Noble => write!(f, "Noble"),
            Self::Noggle => write!(f, "Noggle"),
            Self::Nomad => write!(f, "Nomad"),
            Self::Nymph => write!(f, "Nymph"),
            Self::Octopus => write!(f, "Octopus"),
            Self::Ogre => write!(f, "Ogre"),
            Self::Ooze => write!(f, "Ooze"),
            Self::Orb => write!(f, "Orb"),
            Self::Orc => write!(f, "Orc"),
            Self::Orgg => write!(f, "Orgg"),
            Self::Otter => write!(f, "Otter"),
            Self::Ouphe => write!(f, "Ouphe"),
            Self::Ox => write!(f, "Ox"),
            Self::Oyster => write!(f, "Oyster"),
            Self::Pangolin => write!(f, "Pangolin"),
            Self::Peasant => write!(f, "Peasant"),
            Self::Pegasus => write!(f, "Pegasus"),
            Self::Pentavite => write!(f, "Pentavite"),
            Self::Performer => write!(f, "Performer"),
            Self::Pest => write!(f, "Pest"),
            Self::Phelddagrif => write!(f, "Phelddagrif"),
            Self::Phoenix => write!(f, "Phoenix"),
            Self::Phyrexian => write!(f, "Phyrexian"),
            Self::Pilot => write!(f, "Pilot"),
            Self::Pincher => write!(f, "Pincher"),
            Self::Pirate => write!(f, "Pirate"),
            Self::Plant => write!(f, "Plant"),
            Self::Porcupine => write!(f, "Porcupine"),
            Self::Possum => write!(f, "Possum"),
            Self::Praetor => write!(f, "Praetor"),
            Self::Primarch => write!(f, "Primarch"),
            Self::Prism => write!(f, "Prism"),
            Self::Processor => write!(f, "Processor"),
            Self::Rabbit => write!(f, "Rabbit"),
            Self::Raccoon => write!(f, "Raccoon"),
            Self::Ranger => write!(f, "Ranger"),
            Self::Rat => write!(f, "Rat"),
            Self::Rebel => write!(f, "Rebel"),
            Self::Reflection => write!(f, "Reflection"),
            Self::Reveler => write!(f, "Reveler"),
            Self::Rhino => write!(f, "Rhino"),
            Self::Rigger => write!(f, "Rigger"),
            Self::Robot => write!(f, "Robot"),
            Self::Rogue => write!(f, "Rogue"),
            Self::Rukh => write!(f, "Rukh"),
            Self::Sable => write!(f, "Sable"),
            Self::Salamander => write!(f, "Salamander"),
            Self::Samurai => write!(f, "Samurai"),
            Self::Sand => write!(f, "Sand"),
            Self::Saproling => write!(f, "Saproling"),
            Self::Satyr => write!(f, "Satyr"),
            Self::Scarecrow => write!(f, "Scarecrow"),
            Self::Scientist => write!(f, "Scientist"),
            Self::Scion => write!(f, "Scion"),
            Self::Scorpion => write!(f, "Scorpion"),
            Self::Scout => write!(f, "Scout"),
            Self::Sculpture => write!(f, "Sculpture"),
            Self::Serf => write!(f, "Serf"),
            Self::Serpent => write!(f, "Serpent"),
            Self::Servo => write!(f, "Servo"),
            Self::Shade => write!(f, "Shade"),
            Self::Shaman => write!(f, "Shaman"),
            Self::Shapeshifter => write!(f, "Shapeshifter"),
            Self::Shark => write!(f, "Shark"),
            Self::Sheep => write!(f, "Sheep"),
            Self::Siren => write!(f, "Siren"),
            Self::Skeleton => write!(f, "Skeleton"),
            Self::Skunk => write!(f, "Skunk"),
            Self::Slith => write!(f, "Slith"),
            Self::Sliver => write!(f, "Sliver"),
            Self::Sloth => write!(f, "Sloth"),
            Self::Slug => write!(f, "Slug"),
            Self::Snail => write!(f, "Snail"),
            Self::Snake => write!(f, "Snake"),
            Self::Soldier => write!(f, "Soldier"),
            Self::Soltari => write!(f, "Soltari"),
            Self::Spawn => write!(f, "Spawn"),
            Self::Specter => write!(f, "Specter"),
            Self::Spellshaper => write!(f, "Spellshaper"),
            Self::Sphinx => write!(f, "Sphinx"),
            Self::Spider => write!(f, "Spider"),
            Self::Spike => write!(f, "Spike"),
            Self::Spirit => write!(f, "Spirit"),
            Self::Splinter => write!(f, "Splinter"),
            Self::Sponge => write!(f, "Sponge"),
            Self::Spy => write!(f, "Spy"),
            Self::Squid => write!(f, "Squid"),
            Self::Squirrel => write!(f, "Squirrel"),
            Self::Starfish => write!(f, "Starfish"),
            Self::Surrakar => write!(f, "Surrakar"),
            Self::Survivor => write!(f, "Survivor"),
            Self::Synth => write!(f, "Synth"),
            Self::Teddy => write!(f, "Teddy"),
            Self::Tentacle => write!(f, "Tentacle"),
            Self::Tetravite => write!(f, "Tetravite"),
            Self::Thalakos => write!(f, "Thalakos"),
            Self::Thopter => write!(f, "Thopter"),
            Self::Thrull => write!(f, "Thrull"),
            Self::Tiefling => write!(f, "Tiefling"),
            Self::TimeLord => write!(f, "Time Lord"),
            Self::Toy => write!(f, "Toy"),
            Self::Treefolk => write!(f, "Treefolk"),
            Self::Trilobite => write!(f, "Trilobite"),
            Self::Triskelavite => write!(f, "Triskelavite"),
            Self::Troll => write!(f, "Troll"),
            Self::Turtle => write!(f, "Turtle"),
            Self::Tyranid => write!(f, "Tyranid"),
            Self::Unicorn => write!(f, "Unicorn"),
            Self::Urzan => write!(f, "Urzan"),
            Self::Vampire => write!(f, "Vampire"),
            Self::Varmint => write!(f, "Varmint"),
            Self::Vedalken => write!(f, "Vedalken"),
            Self::Volver => write!(f, "Volver"),
            Self::Wall => write!(f, "Wall"),
            Self::Walrus => write!(f, "Walrus"),
            Self::Warlock => write!(f, "Warlock"),
            Self::Warrior => write!(f, "Warrior"),
            Self::Wasp => write!(f, "Wasp"),
            Self::Weasel => write!(f, "Weasel"),
            Self::Weird => write!(f, "Weird"),
            Self::Werewolf => write!(f, "Werewolf"),
            Self::Whale => write!(f, "Whale"),
            Self::Wizard => write!(f, "Wizard"),
            Self::Wolf => write!(f, "Wolf"),
            Self::Wolverine => write!(f, "Wolverine"),
            Self::Wombat => write!(f, "Wombat"),
            Self::Worm => write!(f, "Worm"),
            Self::Wraith => write!(f, "Wraith"),
            Self::Wurm => write!(f, "Wurm"),
            Self::Yeti => write!(f, "Yeti"),
            Self::Zombie => write!(f, "Zombie"),
            Self::Zubera => write!(f, "Zubera"),
        }
    }
}

impl CreatureType {
    pub fn iter() -> impl Iterator<Item = Self> {
        [
            Self::Advisor,
            Self::Aetherborn,
            Self::Alien,
            Self::Ally,
            Self::Angel,
            Self::Antelope,
            Self::Ape,
            Self::Archer,
            Self::Archon,
            Self::Armadillo,
            Self::Army,
            Self::Artificer,
            Self::Assassin,
            Self::AssemblyWorker,
            Self::Astartes,
            Self::Atog,
            Self::Aurochs,
            Self::Automaton,
            Self::Avatar,
            Self::Azra,
            Self::Badger,
            Self::Balloon,
            Self::Barbarian,
            Self::Bard,
            Self::Basilisk,
            Self::Bat,
            Self::Bear,
            Self::Beast,
            Self::Beaver,
            Self::Beeble,
            Self::Beholder,
            Self::Berserker,
            Self::Bird,
            Self::Blinkmoth,
            Self::Boar,
            Self::Brainiac,
            Self::Bringer,
            Self::Brushwagg,
            Self::Ctan,
            Self::Camarid,
            Self::Camel,
            Self::Capybara,
            Self::Caribou,
            Self::Carrier,
            Self::Cat,
            Self::Centaur,
            Self::Chicken,
            Self::Child,
            Self::Chimera,
            Self::Citizen,
            Self::Cleric,
            Self::Clown,
            Self::Cockatrice,
            Self::Construct,
            Self::Coward,
            Self::Coyote,
            Self::Crab,
            Self::Crocodile,
            Self::Custodes,
            Self::Cyberman,
            Self::Cyclops,
            Self::Dalek,
            Self::Dauthi,
            Self::Demigod,
            Self::Demon,
            Self::Deserter,
            Self::Detective,
            Self::Devil,
            Self::Dinosaur,
            Self::Djinn,
            Self::Doctor,
            Self::Dog,
            Self::Dragon,
            Self::Drake,
            Self::Dreadnought,
            Self::Drone,
            Self::Druid,
            Self::Dryad,
            Self::Dwarf,
            Self::Efreet,
            Self::Egg,
            Self::Elder,
            Self::Eldrazi,
            Self::Elemental,
            Self::Elephant,
            Self::Elf,
            Self::Elk,
            Self::Employee,
            Self::Eye,
            Self::Faerie,
            Self::Ferret,
            Self::Fish,
            Self::Flagbearer,
            Self::Fox,
            Self::Fractal,
            Self::Frog,
            Self::Fungus,
            Self::Gamer,
            Self::Gargoyle,
            Self::Germ,
            Self::Giant,
            Self::Gith,
            Self::Glimmer,
            Self::Gnoll,
            Self::Gnome,
            Self::Goat,
            Self::Goblin,
            Self::God,
            Self::Golem,
            Self::Gorgon,
            Self::Graveborn,
            Self::Gremlin,
            Self::Griffin,
            Self::Guest,
            Self::Hag,
            Self::Halfling,
            Self::Hamster,
            Self::Harpy,
            Self::Head,
            Self::Hellion,
            Self::Hero,
            Self::Hippo,
            Self::Hippogriff,
            Self::Homarid,
            Self::Homunculus,
            Self::Hornet,
            Self::Horror,
            Self::Horse,
            Self::Human,
            Self::Hydra,
            Self::Hyena,
            Self::Illusion,
            Self::Imp,
            Self::Incarnation,
            Self::Inkling,
            Self::Inquisitor,
            Self::Insect,
            Self::Jackal,
            Self::Jellyfish,
            Self::Juggernaut,
            Self::Kavu,
            Self::Kirin,
            Self::Kithkin,
            Self::Knight,
            Self::Kobold,
            Self::Kor,
            Self::Kraken,
            Self::Lamia,
            Self::Lammasu,
            Self::Leech,
            Self::Leviathan,
            Self::Lhurgoyf,
            Self::Licid,
            Self::Lizard,
            Self::Manticore,
            Self::Masticore,
            Self::Mercenary,
            Self::Merfolk,
            Self::Metathran,
            Self::Minion,
            Self::Minotaur,
            Self::Mite,
            Self::Mole,
            Self::Monger,
            Self::Mongoose,
            Self::Monk,
            Self::Monkey,
            Self::Moonfolk,
            Self::Mount,
            Self::Mouse,
            Self::Mutant,
            Self::Myr,
            Self::Mystic,
            Self::Naga,
            Self::Nautilus,
            Self::Necron,
            Self::Nephilim,
            Self::Nightmare,
            Self::Nightstalker,
            Self::Ninja,
            Self::Noble,
            Self::Noggle,
            Self::Nomad,
            Self::Nymph,
            Self::Octopus,
            Self::Ogre,
            Self::Ooze,
            Self::Orb,
            Self::Orc,
            Self::Orgg,
            Self::Otter,
            Self::Ouphe,
            Self::Ox,
            Self::Oyster,
            Self::Pangolin,
            Self::Peasant,
            Self::Pegasus,
            Self::Pentavite,
            Self::Performer,
            Self::Pest,
            Self::Phelddagrif,
            Self::Phoenix,
            Self::Phyrexian,
            Self::Pilot,
            Self::Pincher,
            Self::Pirate,
            Self::Plant,
            Self::Porcupine,
            Self::Possum,
            Self::Praetor,
            Self::Primarch,
            Self::Prism,
            Self::Processor,
            Self::Rabbit,
            Self::Raccoon,
            Self::Ranger,
            Self::Rat,
            Self::Rebel,
            Self::Reflection,
            Self::Reveler,
            Self::Rhino,
            Self::Rigger,
            Self::Robot,
            Self::Rogue,
            Self::Rukh,
            Self::Sable,
            Self::Salamander,
            Self::Samurai,
            Self::Sand,
            Self::Saproling,
            Self::Satyr,
            Self::Scarecrow,
            Self::Scientist,
            Self::Scion,
            Self::Scorpion,
            Self::Scout,
            Self::Sculpture,
            Self::Serf,
            Self::Serpent,
            Self::Servo,
            Self::Shade,
            Self::Shaman,
            Self::Shapeshifter,
            Self::Shark,
            Self::Sheep,
            Self::Siren,
            Self::Skeleton,
            Self::Skunk,
            Self::Slith,
            Self::Sliver,
            Self::Sloth,
            Self::Slug,
            Self::Snail,
            Self::Snake,
            Self::Soldier,
            Self::Soltari,
            Self::Spawn,
            Self::Specter,
            Self::Spellshaper,
            Self::Sphinx,
            Self::Spider,
            Self::Spike,
            Self::Spirit,
            Self::Splinter,
            Self::Sponge,
            Self::Spy,
            Self::Squid,
            Self::Squirrel,
            Self::Starfish,
            Self::Surrakar,
            Self::Survivor,
            Self::Synth,
            Self::Teddy,
            Self::Tentacle,
            Self::Tetravite,
            Self::Thalakos,
            Self::Thopter,
            Self::Thrull,
            Self::Tiefling,
            Self::TimeLord,
            Self::Toy,
            Self::Treefolk,
            Self::Trilobite,
            Self::Triskelavite,
            Self::Troll,
            Self::Turtle,
            Self::Tyranid,
            Self::Unicorn,
            Self::Urzan,
            Self::Vampire,
            Self::Varmint,
            Self::Vedalken,
            Self::Volver,
            Self::Wall,
            Self::Walrus,
            Self::Warlock,
            Self::Warrior,
            Self::Wasp,
            Self::Weasel,
            Self::Weird,
            Self::Werewolf,
            Self::Whale,
            Self::Wizard,
            Self::Wolf,
            Self::Wolverine,
            Self::Wombat,
            Self::Worm,
            Self::Wraith,
            Self::Wurm,
            Self::Yeti,
            Self::Zombie,
            Self::Zubera,
        ].into_iter()
    }
}
