#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum KeywordAbility {
    Absorb,
    Affinity,
    Afflict,
    Afterlife,
    Aftermath,
    Amplify,
    Annihilator,
    Ascend,
    Assist,
    Augment,
    AuraSwap,
    Awaken,
    Backup,
    Banding,
    Bargain,
    BasicLandcycling,
    BattleCry,
    Bestow,
    Blitz,
    Bloodthirst,
    Boast,
    Bushido,
    Buyback,
    Cascade,
    Casualty,
    Champion,
    Changeling,
    ChooseABackground,
    Cipher,
    Cleave,
    CommanderNinjutsu,
    Companion,
    Compleated,
    Conspire,
    Convoke,
    Craft,
    Crew,
    CumulativeUpkeep,
    Cycling,
    Dash,
    Daybound,
    Deathtouch,
    Decayed,
    Defender,
    Delve,
    Demonstrate,
    Desertwalk,
    Dethrone,
    Devoid,
    Devour,
    Disguise,
    Disturb,
    DoctorsCompanion,
    DoubleAgenda,
    DoubleStrike,
    Dredge,
    Echo,
    Embalm,
    Emerge,
    Enchant,
    Encore,
    Enlist,
    Entwine,
    Epic,
    Equip,
    Escalate,
    Escape,
    Eternalize,
    Evoke,
    Evolve,
    Exalted,
    Exploit,
    Extort,
    Fabricate,
    Fading,
    Fear,
    FirstStrike,
    Flanking,
    Flash,
    Flashback,
    Flying,
    ForMirrodin,
    Forecast,
    Forestcycling,
    Forestwalk,
    Foretell,
    Fortify,
    Freerunning,
    Frenzy,
    FriendsForever,
    Fuse,
    Gift,
    Graft,
    Gravestorm,
    Haste,
    Haunt,
    Hexproof,
    HexproofFrom,
    HiddenAgenda,
    Hideaway,
    Horsemanship,
    Impending,
    Improvise,
    Indestructible,
    Infect,
    Ingest,
    Intensity,
    Intimidate,
    Islandcycling,
    Islandwalk,
    JumpStart,
    Kicker,
    Landcycling,
    Landwalk,
    LegendaryLandwalk,
    LevelUp,
    Lifelink,
    LivingMetal,
    LivingWeapon,
    Madness,
    Megamorph,
    Melee,
    Menace,
    Mentor,
    Miracle,
    Modular,
    MoreThanMeetsTheEye,
    Morph,
    Mountaincycling,
    Mountainwalk,
    Multikicker,
    Mutate,
    Myriad,
    Nightbound,
    Ninjutsu,
    NonbasicLandwalk,
    Offering,
    Offspring,
    Outlast,
    Overload,
    Partner,
    PartnerWith,
    Persist,
    Phasing,
    Plainscycling,
    Plainswalk,
    Poisonous,
    Protection,
    Prototype,
    Provoke,
    Prowess,
    Prowl,
    Rampage,
    Ravenous,
    Reach,
    ReadAhead,
    Rebound,
    Reconfigure,
    Recover,
    Reinforce,
    Renown,
    Replicate,
    Retrace,
    Riot,
    Ripple,
    Saddle,
    Scavenge,
    Shadow,
    Shroud,
    Skulk,
    Slivercycling,
    Soulbond,
    Soulshift,
    Specialize,
    Spectacle,
    Splice,
    SplitSecond,
    Spree,
    Squad,
    Storm,
    Sunburst,
    Surge,
    Suspend,
    Swampcycling,
    Swampwalk,
    Toxic,
    Training,
    Trample,
    Transfigure,
    Transmute,
    Tribute,
    Typecycling,
    UmbraArmor,
    Undaunted,
    Undying,
    Unearth,
    Unleash,
    Vanishing,
    Vigilance,
    Ward,
    Wither,
    Wizardcycling,
}

impl std::str::FromStr for KeywordAbility {
    type Err = crate::ParsingError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Absorb" => Ok(Self::Absorb),
            "Affinity" => Ok(Self::Affinity),
            "Afflict" => Ok(Self::Afflict),
            "Afterlife" => Ok(Self::Afterlife),
            "Aftermath" => Ok(Self::Aftermath),
            "Amplify" => Ok(Self::Amplify),
            "Annihilator" => Ok(Self::Annihilator),
            "Ascend" => Ok(Self::Ascend),
            "Assist" => Ok(Self::Assist),
            "Augment" => Ok(Self::Augment),
            "Aura Swap" => Ok(Self::AuraSwap),
            "Awaken" => Ok(Self::Awaken),
            "Backup" => Ok(Self::Backup),
            "Banding" => Ok(Self::Banding),
            "Bargain" => Ok(Self::Bargain),
            "Basic landcycling" => Ok(Self::BasicLandcycling),
            "Battle Cry" => Ok(Self::BattleCry),
            "Bestow" => Ok(Self::Bestow),
            "Blitz" => Ok(Self::Blitz),
            "Bloodthirst" => Ok(Self::Bloodthirst),
            "Boast" => Ok(Self::Boast),
            "Bushido" => Ok(Self::Bushido),
            "Buyback" => Ok(Self::Buyback),
            "Cascade" => Ok(Self::Cascade),
            "Casualty" => Ok(Self::Casualty),
            "Champion" => Ok(Self::Champion),
            "Changeling" => Ok(Self::Changeling),
            "Choose a background" => Ok(Self::ChooseABackground),
            "Cipher" => Ok(Self::Cipher),
            "Cleave" => Ok(Self::Cleave),
            "Commander ninjutsu" => Ok(Self::CommanderNinjutsu),
            "Companion" => Ok(Self::Companion),
            "Compleated" => Ok(Self::Compleated),
            "Conspire" => Ok(Self::Conspire),
            "Convoke" => Ok(Self::Convoke),
            "Craft" => Ok(Self::Craft),
            "Crew" => Ok(Self::Crew),
            "Cumulative upkeep" => Ok(Self::CumulativeUpkeep),
            "Cycling" => Ok(Self::Cycling),
            "Dash" => Ok(Self::Dash),
            "Daybound" => Ok(Self::Daybound),
            "Deathtouch" => Ok(Self::Deathtouch),
            "Decayed" => Ok(Self::Decayed),
            "Defender" => Ok(Self::Defender),
            "Delve" => Ok(Self::Delve),
            "Demonstrate" => Ok(Self::Demonstrate),
            "Desertwalk" => Ok(Self::Desertwalk),
            "Dethrone" => Ok(Self::Dethrone),
            "Devoid" => Ok(Self::Devoid),
            "Devour" => Ok(Self::Devour),
            "Disguise" => Ok(Self::Disguise),
            "Disturb" => Ok(Self::Disturb),
            "Doctor's companion" => Ok(Self::DoctorsCompanion),
            "Double agenda" => Ok(Self::DoubleAgenda),
            "Double strike" => Ok(Self::DoubleStrike),
            "Dredge" => Ok(Self::Dredge),
            "Echo" => Ok(Self::Echo),
            "Embalm" => Ok(Self::Embalm),
            "Emerge" => Ok(Self::Emerge),
            "Enchant" => Ok(Self::Enchant),
            "Encore" => Ok(Self::Encore),
            "Enlist" => Ok(Self::Enlist),
            "Entwine" => Ok(Self::Entwine),
            "Epic" => Ok(Self::Epic),
            "Equip" => Ok(Self::Equip),
            "Escalate" => Ok(Self::Escalate),
            "Escape" => Ok(Self::Escape),
            "Eternalize" => Ok(Self::Eternalize),
            "Evoke" => Ok(Self::Evoke),
            "Evolve" => Ok(Self::Evolve),
            "Exalted" => Ok(Self::Exalted),
            "Exploit" => Ok(Self::Exploit),
            "Extort" => Ok(Self::Extort),
            "Fabricate" => Ok(Self::Fabricate),
            "Fading" => Ok(Self::Fading),
            "Fear" => Ok(Self::Fear),
            "First strike" => Ok(Self::FirstStrike),
            "Flanking" => Ok(Self::Flanking),
            "Flash" => Ok(Self::Flash),
            "Flashback" => Ok(Self::Flashback),
            "Flying" => Ok(Self::Flying),
            "For Mirrodin!" => Ok(Self::ForMirrodin),
            "Forecast" => Ok(Self::Forecast),
            "Forestcycling" => Ok(Self::Forestcycling),
            "Forestwalk" => Ok(Self::Forestwalk),
            "Foretell" => Ok(Self::Foretell),
            "Fortify" => Ok(Self::Fortify),
            "Freerunning" => Ok(Self::Freerunning),
            "Frenzy" => Ok(Self::Frenzy),
            "Friends forever" => Ok(Self::FriendsForever),
            "Fuse" => Ok(Self::Fuse),
            "Gift" => Ok(Self::Gift),
            "Graft" => Ok(Self::Graft),
            "Gravestorm" => Ok(Self::Gravestorm),
            "Haste" => Ok(Self::Haste),
            "Haunt" => Ok(Self::Haunt),
            "Hexproof" => Ok(Self::Hexproof),
            "Hexproof from" => Ok(Self::HexproofFrom),
            "Hidden agenda" => Ok(Self::HiddenAgenda),
            "Hideaway" => Ok(Self::Hideaway),
            "Horsemanship" => Ok(Self::Horsemanship),
            "Impending" => Ok(Self::Impending),
            "Improvise" => Ok(Self::Improvise),
            "Indestructible" => Ok(Self::Indestructible),
            "Infect" => Ok(Self::Infect),
            "Ingest" => Ok(Self::Ingest),
            "Intensity" => Ok(Self::Intensity),
            "Intimidate" => Ok(Self::Intimidate),
            "Islandcycling" => Ok(Self::Islandcycling),
            "Islandwalk" => Ok(Self::Islandwalk),
            "Jump-start" => Ok(Self::JumpStart),
            "Kicker" => Ok(Self::Kicker),
            "Landcycling" => Ok(Self::Landcycling),
            "Landwalk" => Ok(Self::Landwalk),
            "Legendary landwalk" => Ok(Self::LegendaryLandwalk),
            "Level Up" => Ok(Self::LevelUp),
            "Lifelink" => Ok(Self::Lifelink),
            "Living metal" => Ok(Self::LivingMetal),
            "Living weapon" => Ok(Self::LivingWeapon),
            "Madness" => Ok(Self::Madness),
            "Megamorph" => Ok(Self::Megamorph),
            "Melee" => Ok(Self::Melee),
            "Menace" => Ok(Self::Menace),
            "Mentor" => Ok(Self::Mentor),
            "Miracle" => Ok(Self::Miracle),
            "Modular" => Ok(Self::Modular),
            "More Than Meets the Eye" => Ok(Self::MoreThanMeetsTheEye),
            "Morph" => Ok(Self::Morph),
            "Mountaincycling" => Ok(Self::Mountaincycling),
            "Mountainwalk" => Ok(Self::Mountainwalk),
            "Multikicker" => Ok(Self::Multikicker),
            "Mutate" => Ok(Self::Mutate),
            "Myriad" => Ok(Self::Myriad),
            "Nightbound" => Ok(Self::Nightbound),
            "Ninjutsu" => Ok(Self::Ninjutsu),
            "Nonbasic landwalk" => Ok(Self::NonbasicLandwalk),
            "Offering" => Ok(Self::Offering),
            "Offspring" => Ok(Self::Offspring),
            "Outlast" => Ok(Self::Outlast),
            "Overload" => Ok(Self::Overload),
            "Partner" => Ok(Self::Partner),
            "Partner with" => Ok(Self::PartnerWith),
            "Persist" => Ok(Self::Persist),
            "Phasing" => Ok(Self::Phasing),
            "Plainscycling" => Ok(Self::Plainscycling),
            "Plainswalk" => Ok(Self::Plainswalk),
            "Poisonous" => Ok(Self::Poisonous),
            "Protection" => Ok(Self::Protection),
            "Prototype" => Ok(Self::Prototype),
            "Provoke" => Ok(Self::Provoke),
            "Prowess" => Ok(Self::Prowess),
            "Prowl" => Ok(Self::Prowl),
            "Rampage" => Ok(Self::Rampage),
            "Ravenous" => Ok(Self::Ravenous),
            "Reach" => Ok(Self::Reach),
            "Read Ahead" => Ok(Self::ReadAhead),
            "Rebound" => Ok(Self::Rebound),
            "Reconfigure" => Ok(Self::Reconfigure),
            "Recover" => Ok(Self::Recover),
            "Reinforce" => Ok(Self::Reinforce),
            "Renown" => Ok(Self::Renown),
            "Replicate" => Ok(Self::Replicate),
            "Retrace" => Ok(Self::Retrace),
            "Riot" => Ok(Self::Riot),
            "Ripple" => Ok(Self::Ripple),
            "Saddle" => Ok(Self::Saddle),
            "Scavenge" => Ok(Self::Scavenge),
            "Shadow" => Ok(Self::Shadow),
            "Shroud" => Ok(Self::Shroud),
            "Skulk" => Ok(Self::Skulk),
            "Slivercycling" => Ok(Self::Slivercycling),
            "Soulbond" => Ok(Self::Soulbond),
            "Soulshift" => Ok(Self::Soulshift),
            "Specialize" => Ok(Self::Specialize),
            "Spectacle" => Ok(Self::Spectacle),
            "Splice" => Ok(Self::Splice),
            "Split second" => Ok(Self::SplitSecond),
            "Spree" => Ok(Self::Spree),
            "Squad" => Ok(Self::Squad),
            "Storm" => Ok(Self::Storm),
            "Sunburst" => Ok(Self::Sunburst),
            "Surge" => Ok(Self::Surge),
            "Suspend" => Ok(Self::Suspend),
            "Swampcycling" => Ok(Self::Swampcycling),
            "Swampwalk" => Ok(Self::Swampwalk),
            "Toxic" => Ok(Self::Toxic),
            "Training" => Ok(Self::Training),
            "Trample" => Ok(Self::Trample),
            "Transfigure" => Ok(Self::Transfigure),
            "Transmute" => Ok(Self::Transmute),
            "Tribute" => Ok(Self::Tribute),
            "Typecycling" => Ok(Self::Typecycling),
            "Umbra armor" => Ok(Self::UmbraArmor),
            "Undaunted" => Ok(Self::Undaunted),
            "Undying" => Ok(Self::Undying),
            "Unearth" => Ok(Self::Unearth),
            "Unleash" => Ok(Self::Unleash),
            "Vanishing" => Ok(Self::Vanishing),
            "Vigilance" => Ok(Self::Vigilance),
            "Ward" => Ok(Self::Ward),
            "Wither" => Ok(Self::Wither),
            "Wizardcycling" => Ok(Self::Wizardcycling),
            _ => Err(crate::ParsingError::UnknownInput { input: s.to_string() }),
        }
    }
}

impl std::fmt::Display for KeywordAbility {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self {
            Self::Absorb => write!(f, "Absorb"),
            Self::Affinity => write!(f, "Affinity"),
            Self::Afflict => write!(f, "Afflict"),
            Self::Afterlife => write!(f, "Afterlife"),
            Self::Aftermath => write!(f, "Aftermath"),
            Self::Amplify => write!(f, "Amplify"),
            Self::Annihilator => write!(f, "Annihilator"),
            Self::Ascend => write!(f, "Ascend"),
            Self::Assist => write!(f, "Assist"),
            Self::Augment => write!(f, "Augment"),
            Self::AuraSwap => write!(f, "Aura Swap"),
            Self::Awaken => write!(f, "Awaken"),
            Self::Backup => write!(f, "Backup"),
            Self::Banding => write!(f, "Banding"),
            Self::Bargain => write!(f, "Bargain"),
            Self::BasicLandcycling => write!(f, "Basic landcycling"),
            Self::BattleCry => write!(f, "Battle Cry"),
            Self::Bestow => write!(f, "Bestow"),
            Self::Blitz => write!(f, "Blitz"),
            Self::Bloodthirst => write!(f, "Bloodthirst"),
            Self::Boast => write!(f, "Boast"),
            Self::Bushido => write!(f, "Bushido"),
            Self::Buyback => write!(f, "Buyback"),
            Self::Cascade => write!(f, "Cascade"),
            Self::Casualty => write!(f, "Casualty"),
            Self::Champion => write!(f, "Champion"),
            Self::Changeling => write!(f, "Changeling"),
            Self::ChooseABackground => write!(f, "Choose a background"),
            Self::Cipher => write!(f, "Cipher"),
            Self::Cleave => write!(f, "Cleave"),
            Self::CommanderNinjutsu => write!(f, "Commander ninjutsu"),
            Self::Companion => write!(f, "Companion"),
            Self::Compleated => write!(f, "Compleated"),
            Self::Conspire => write!(f, "Conspire"),
            Self::Convoke => write!(f, "Convoke"),
            Self::Craft => write!(f, "Craft"),
            Self::Crew => write!(f, "Crew"),
            Self::CumulativeUpkeep => write!(f, "Cumulative upkeep"),
            Self::Cycling => write!(f, "Cycling"),
            Self::Dash => write!(f, "Dash"),
            Self::Daybound => write!(f, "Daybound"),
            Self::Deathtouch => write!(f, "Deathtouch"),
            Self::Decayed => write!(f, "Decayed"),
            Self::Defender => write!(f, "Defender"),
            Self::Delve => write!(f, "Delve"),
            Self::Demonstrate => write!(f, "Demonstrate"),
            Self::Desertwalk => write!(f, "Desertwalk"),
            Self::Dethrone => write!(f, "Dethrone"),
            Self::Devoid => write!(f, "Devoid"),
            Self::Devour => write!(f, "Devour"),
            Self::Disguise => write!(f, "Disguise"),
            Self::Disturb => write!(f, "Disturb"),
            Self::DoctorsCompanion => write!(f, "Doctor's companion"),
            Self::DoubleAgenda => write!(f, "Double agenda"),
            Self::DoubleStrike => write!(f, "Double strike"),
            Self::Dredge => write!(f, "Dredge"),
            Self::Echo => write!(f, "Echo"),
            Self::Embalm => write!(f, "Embalm"),
            Self::Emerge => write!(f, "Emerge"),
            Self::Enchant => write!(f, "Enchant"),
            Self::Encore => write!(f, "Encore"),
            Self::Enlist => write!(f, "Enlist"),
            Self::Entwine => write!(f, "Entwine"),
            Self::Epic => write!(f, "Epic"),
            Self::Equip => write!(f, "Equip"),
            Self::Escalate => write!(f, "Escalate"),
            Self::Escape => write!(f, "Escape"),
            Self::Eternalize => write!(f, "Eternalize"),
            Self::Evoke => write!(f, "Evoke"),
            Self::Evolve => write!(f, "Evolve"),
            Self::Exalted => write!(f, "Exalted"),
            Self::Exploit => write!(f, "Exploit"),
            Self::Extort => write!(f, "Extort"),
            Self::Fabricate => write!(f, "Fabricate"),
            Self::Fading => write!(f, "Fading"),
            Self::Fear => write!(f, "Fear"),
            Self::FirstStrike => write!(f, "First strike"),
            Self::Flanking => write!(f, "Flanking"),
            Self::Flash => write!(f, "Flash"),
            Self::Flashback => write!(f, "Flashback"),
            Self::Flying => write!(f, "Flying"),
            Self::ForMirrodin => write!(f, "For Mirrodin!"),
            Self::Forecast => write!(f, "Forecast"),
            Self::Forestcycling => write!(f, "Forestcycling"),
            Self::Forestwalk => write!(f, "Forestwalk"),
            Self::Foretell => write!(f, "Foretell"),
            Self::Fortify => write!(f, "Fortify"),
            Self::Freerunning => write!(f, "Freerunning"),
            Self::Frenzy => write!(f, "Frenzy"),
            Self::FriendsForever => write!(f, "Friends forever"),
            Self::Fuse => write!(f, "Fuse"),
            Self::Gift => write!(f, "Gift"),
            Self::Graft => write!(f, "Graft"),
            Self::Gravestorm => write!(f, "Gravestorm"),
            Self::Haste => write!(f, "Haste"),
            Self::Haunt => write!(f, "Haunt"),
            Self::Hexproof => write!(f, "Hexproof"),
            Self::HexproofFrom => write!(f, "Hexproof from"),
            Self::HiddenAgenda => write!(f, "Hidden agenda"),
            Self::Hideaway => write!(f, "Hideaway"),
            Self::Horsemanship => write!(f, "Horsemanship"),
            Self::Impending => write!(f, "Impending"),
            Self::Improvise => write!(f, "Improvise"),
            Self::Indestructible => write!(f, "Indestructible"),
            Self::Infect => write!(f, "Infect"),
            Self::Ingest => write!(f, "Ingest"),
            Self::Intensity => write!(f, "Intensity"),
            Self::Intimidate => write!(f, "Intimidate"),
            Self::Islandcycling => write!(f, "Islandcycling"),
            Self::Islandwalk => write!(f, "Islandwalk"),
            Self::JumpStart => write!(f, "Jump-start"),
            Self::Kicker => write!(f, "Kicker"),
            Self::Landcycling => write!(f, "Landcycling"),
            Self::Landwalk => write!(f, "Landwalk"),
            Self::LegendaryLandwalk => write!(f, "Legendary landwalk"),
            Self::LevelUp => write!(f, "Level Up"),
            Self::Lifelink => write!(f, "Lifelink"),
            Self::LivingMetal => write!(f, "Living metal"),
            Self::LivingWeapon => write!(f, "Living weapon"),
            Self::Madness => write!(f, "Madness"),
            Self::Megamorph => write!(f, "Megamorph"),
            Self::Melee => write!(f, "Melee"),
            Self::Menace => write!(f, "Menace"),
            Self::Mentor => write!(f, "Mentor"),
            Self::Miracle => write!(f, "Miracle"),
            Self::Modular => write!(f, "Modular"),
            Self::MoreThanMeetsTheEye => write!(f, "More Than Meets the Eye"),
            Self::Morph => write!(f, "Morph"),
            Self::Mountaincycling => write!(f, "Mountaincycling"),
            Self::Mountainwalk => write!(f, "Mountainwalk"),
            Self::Multikicker => write!(f, "Multikicker"),
            Self::Mutate => write!(f, "Mutate"),
            Self::Myriad => write!(f, "Myriad"),
            Self::Nightbound => write!(f, "Nightbound"),
            Self::Ninjutsu => write!(f, "Ninjutsu"),
            Self::NonbasicLandwalk => write!(f, "Nonbasic landwalk"),
            Self::Offering => write!(f, "Offering"),
            Self::Offspring => write!(f, "Offspring"),
            Self::Outlast => write!(f, "Outlast"),
            Self::Overload => write!(f, "Overload"),
            Self::Partner => write!(f, "Partner"),
            Self::PartnerWith => write!(f, "Partner with"),
            Self::Persist => write!(f, "Persist"),
            Self::Phasing => write!(f, "Phasing"),
            Self::Plainscycling => write!(f, "Plainscycling"),
            Self::Plainswalk => write!(f, "Plainswalk"),
            Self::Poisonous => write!(f, "Poisonous"),
            Self::Protection => write!(f, "Protection"),
            Self::Prototype => write!(f, "Prototype"),
            Self::Provoke => write!(f, "Provoke"),
            Self::Prowess => write!(f, "Prowess"),
            Self::Prowl => write!(f, "Prowl"),
            Self::Rampage => write!(f, "Rampage"),
            Self::Ravenous => write!(f, "Ravenous"),
            Self::Reach => write!(f, "Reach"),
            Self::ReadAhead => write!(f, "Read Ahead"),
            Self::Rebound => write!(f, "Rebound"),
            Self::Reconfigure => write!(f, "Reconfigure"),
            Self::Recover => write!(f, "Recover"),
            Self::Reinforce => write!(f, "Reinforce"),
            Self::Renown => write!(f, "Renown"),
            Self::Replicate => write!(f, "Replicate"),
            Self::Retrace => write!(f, "Retrace"),
            Self::Riot => write!(f, "Riot"),
            Self::Ripple => write!(f, "Ripple"),
            Self::Saddle => write!(f, "Saddle"),
            Self::Scavenge => write!(f, "Scavenge"),
            Self::Shadow => write!(f, "Shadow"),
            Self::Shroud => write!(f, "Shroud"),
            Self::Skulk => write!(f, "Skulk"),
            Self::Slivercycling => write!(f, "Slivercycling"),
            Self::Soulbond => write!(f, "Soulbond"),
            Self::Soulshift => write!(f, "Soulshift"),
            Self::Specialize => write!(f, "Specialize"),
            Self::Spectacle => write!(f, "Spectacle"),
            Self::Splice => write!(f, "Splice"),
            Self::SplitSecond => write!(f, "Split second"),
            Self::Spree => write!(f, "Spree"),
            Self::Squad => write!(f, "Squad"),
            Self::Storm => write!(f, "Storm"),
            Self::Sunburst => write!(f, "Sunburst"),
            Self::Surge => write!(f, "Surge"),
            Self::Suspend => write!(f, "Suspend"),
            Self::Swampcycling => write!(f, "Swampcycling"),
            Self::Swampwalk => write!(f, "Swampwalk"),
            Self::Toxic => write!(f, "Toxic"),
            Self::Training => write!(f, "Training"),
            Self::Trample => write!(f, "Trample"),
            Self::Transfigure => write!(f, "Transfigure"),
            Self::Transmute => write!(f, "Transmute"),
            Self::Tribute => write!(f, "Tribute"),
            Self::Typecycling => write!(f, "Typecycling"),
            Self::UmbraArmor => write!(f, "Umbra armor"),
            Self::Undaunted => write!(f, "Undaunted"),
            Self::Undying => write!(f, "Undying"),
            Self::Unearth => write!(f, "Unearth"),
            Self::Unleash => write!(f, "Unleash"),
            Self::Vanishing => write!(f, "Vanishing"),
            Self::Vigilance => write!(f, "Vigilance"),
            Self::Ward => write!(f, "Ward"),
            Self::Wither => write!(f, "Wither"),
            Self::Wizardcycling => write!(f, "Wizardcycling"),
        }
    }
}

impl KeywordAbility {
    pub fn iter() -> impl Iterator<Item = Self> {
        [
            Self::Absorb,
            Self::Affinity,
            Self::Afflict,
            Self::Afterlife,
            Self::Aftermath,
            Self::Amplify,
            Self::Annihilator,
            Self::Ascend,
            Self::Assist,
            Self::Augment,
            Self::AuraSwap,
            Self::Awaken,
            Self::Backup,
            Self::Banding,
            Self::Bargain,
            Self::BasicLandcycling,
            Self::BattleCry,
            Self::Bestow,
            Self::Blitz,
            Self::Bloodthirst,
            Self::Boast,
            Self::Bushido,
            Self::Buyback,
            Self::Cascade,
            Self::Casualty,
            Self::Champion,
            Self::Changeling,
            Self::ChooseABackground,
            Self::Cipher,
            Self::Cleave,
            Self::CommanderNinjutsu,
            Self::Companion,
            Self::Compleated,
            Self::Conspire,
            Self::Convoke,
            Self::Craft,
            Self::Crew,
            Self::CumulativeUpkeep,
            Self::Cycling,
            Self::Dash,
            Self::Daybound,
            Self::Deathtouch,
            Self::Decayed,
            Self::Defender,
            Self::Delve,
            Self::Demonstrate,
            Self::Desertwalk,
            Self::Dethrone,
            Self::Devoid,
            Self::Devour,
            Self::Disguise,
            Self::Disturb,
            Self::DoctorsCompanion,
            Self::DoubleAgenda,
            Self::DoubleStrike,
            Self::Dredge,
            Self::Echo,
            Self::Embalm,
            Self::Emerge,
            Self::Enchant,
            Self::Encore,
            Self::Enlist,
            Self::Entwine,
            Self::Epic,
            Self::Equip,
            Self::Escalate,
            Self::Escape,
            Self::Eternalize,
            Self::Evoke,
            Self::Evolve,
            Self::Exalted,
            Self::Exploit,
            Self::Extort,
            Self::Fabricate,
            Self::Fading,
            Self::Fear,
            Self::FirstStrike,
            Self::Flanking,
            Self::Flash,
            Self::Flashback,
            Self::Flying,
            Self::ForMirrodin,
            Self::Forecast,
            Self::Forestcycling,
            Self::Forestwalk,
            Self::Foretell,
            Self::Fortify,
            Self::Freerunning,
            Self::Frenzy,
            Self::FriendsForever,
            Self::Fuse,
            Self::Gift,
            Self::Graft,
            Self::Gravestorm,
            Self::Haste,
            Self::Haunt,
            Self::Hexproof,
            Self::HexproofFrom,
            Self::HiddenAgenda,
            Self::Hideaway,
            Self::Horsemanship,
            Self::Impending,
            Self::Improvise,
            Self::Indestructible,
            Self::Infect,
            Self::Ingest,
            Self::Intensity,
            Self::Intimidate,
            Self::Islandcycling,
            Self::Islandwalk,
            Self::JumpStart,
            Self::Kicker,
            Self::Landcycling,
            Self::Landwalk,
            Self::LegendaryLandwalk,
            Self::LevelUp,
            Self::Lifelink,
            Self::LivingMetal,
            Self::LivingWeapon,
            Self::Madness,
            Self::Megamorph,
            Self::Melee,
            Self::Menace,
            Self::Mentor,
            Self::Miracle,
            Self::Modular,
            Self::MoreThanMeetsTheEye,
            Self::Morph,
            Self::Mountaincycling,
            Self::Mountainwalk,
            Self::Multikicker,
            Self::Mutate,
            Self::Myriad,
            Self::Nightbound,
            Self::Ninjutsu,
            Self::NonbasicLandwalk,
            Self::Offering,
            Self::Offspring,
            Self::Outlast,
            Self::Overload,
            Self::Partner,
            Self::PartnerWith,
            Self::Persist,
            Self::Phasing,
            Self::Plainscycling,
            Self::Plainswalk,
            Self::Poisonous,
            Self::Protection,
            Self::Prototype,
            Self::Provoke,
            Self::Prowess,
            Self::Prowl,
            Self::Rampage,
            Self::Ravenous,
            Self::Reach,
            Self::ReadAhead,
            Self::Rebound,
            Self::Reconfigure,
            Self::Recover,
            Self::Reinforce,
            Self::Renown,
            Self::Replicate,
            Self::Retrace,
            Self::Riot,
            Self::Ripple,
            Self::Saddle,
            Self::Scavenge,
            Self::Shadow,
            Self::Shroud,
            Self::Skulk,
            Self::Slivercycling,
            Self::Soulbond,
            Self::Soulshift,
            Self::Specialize,
            Self::Spectacle,
            Self::Splice,
            Self::SplitSecond,
            Self::Spree,
            Self::Squad,
            Self::Storm,
            Self::Sunburst,
            Self::Surge,
            Self::Suspend,
            Self::Swampcycling,
            Self::Swampwalk,
            Self::Toxic,
            Self::Training,
            Self::Trample,
            Self::Transfigure,
            Self::Transmute,
            Self::Tribute,
            Self::Typecycling,
            Self::UmbraArmor,
            Self::Undaunted,
            Self::Undying,
            Self::Unearth,
            Self::Unleash,
            Self::Vanishing,
            Self::Vigilance,
            Self::Ward,
            Self::Wither,
            Self::Wizardcycling,
        ].into_iter()
    }
}
