#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum KeywordAbility {
    Absorb,
    Affinity,
    Afflict,
    Afterlife,
    Aftermath,
    Amplify,
    Annihilator,
    Ascend,
    Assist,
    Augment,
    AuraSwap,
    Awaken,
    Backup,
    Banding,
    Bargain,
    BasicLandcycling,
    BattleCry,
    Bestow,
    Blitz,
    Bloodthirst,
    Boast,
    Bushido,
    Buyback,
    Cascade,
    Casualty,
    Champion,
    Changeling,
    ChooseABackground,
    Cipher,
    Cleave,
    CommanderNinjutsu,
    Companion,
    Compleated,
    Conspire,
    Convoke,
    Craft,
    Crew,
    CumulativeUpkeep,
    Cycling,
    Dash,
    Daybound,
    Deathtouch,
    Decayed,
    Defender,
    Delve,
    Demonstrate,
    Desertwalk,
    Dethrone,
    Devoid,
    Devour,
    Disguise,
    Disturb,
    DoctorsCompanion,
    DoubleAgenda,
    DoubleStrike,
    DoubleTeam,
    Dredge,
    Echo,
    Embalm,
    Emerge,
    Enchant,
    Encore,
    Enlist,
    Entwine,
    Epic,
    Equip,
    Escalate,
    Escape,
    Eternalize,
    Evoke,
    Evolve,
    Exalted,
    Exhaust,
    Exploit,
    Extort,
    Fabricate,
    Fading,
    Fear,
    FirstStrike,
    Flanking,
    Flash,
    Flashback,
    Flying,
    ForMirrodin,
    Forecast,
    Forestcycling,
    Forestwalk,
    Foretell,
    Fortify,
    Freerunning,
    Frenzy,
    FriendsForever,
    Fuse,
    Gift,
    Graft,
    Gravestorm,
    Harmonize,
    Haste,
    Haunt,
    Hexproof,
    HexproofFrom,
    HiddenAgenda,
    Hideaway,
    Horsemanship,
    Impending,
    Improvise,
    Indestructible,
    Infect,
    Ingest,
    Intensity,
    Intimidate,
    Islandcycling,
    Islandwalk,
    JobSelect,
    JumpStart,
    Kicker,
    Landcycling,
    Landwalk,
    LegendaryLandwalk,
    LevelUp,
    Lifelink,
    LivingMetal,
    LivingWeapon,
    Madness,
    MaxSpeed,
    Mayhem,
    Megamorph,
    Melee,
    Menace,
    Mentor,
    Miracle,
    Mobilize,
    Modular,
    MoreThanMeetsTheEye,
    Morph,
    Mountaincycling,
    Mountainwalk,
    Multikicker,
    Mutate,
    Myriad,
    Nightbound,
    Ninjutsu,
    NonbasicLandwalk,
    Offering,
    Offspring,
    Outlast,
    Overload,
    Partner,
    PartnerWith,
    Persist,
    Phasing,
    Plainscycling,
    Plainswalk,
    Poisonous,
    Protection,
    Prototype,
    Provoke,
    Prowess,
    Prowl,
    Rampage,
    Ravenous,
    Reach,
    ReadAhead,
    Rebound,
    Reconfigure,
    Recover,
    Reinforce,
    Renown,
    Replicate,
    Retrace,
    Riot,
    Ripple,
    Saddle,
    Scavenge,
    Shadow,
    Shroud,
    Skulk,
    Slivercycling,
    Soulbond,
    Soulshift,
    Specialize,
    Spectacle,
    Splice,
    SplitSecond,
    Spree,
    Squad,
    Station,
    Storm,
    Sunburst,
    Surge,
    Suspend,
    Swampcycling,
    Swampwalk,
    Toxic,
    Training,
    Trample,
    Transfigure,
    Transmute,
    Tribute,
    Typecycling,
    UmbraArmor,
    Undaunted,
    Undying,
    Unearth,
    Unleash,
    Vanishing,
    Vigilance,
    Ward,
    Warp,
    WebSlinging,
    Wither,
    Wizardcycling,
}
impl std::str::FromStr for KeywordAbility {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "absorb" => Ok(Self::Absorb),
            "affinity" => Ok(Self::Affinity),
            "afflict" => Ok(Self::Afflict),
            "afterlife" => Ok(Self::Afterlife),
            "aftermath" => Ok(Self::Aftermath),
            "amplify" => Ok(Self::Amplify),
            "annihilator" => Ok(Self::Annihilator),
            "ascend" => Ok(Self::Ascend),
            "assist" => Ok(Self::Assist),
            "augment" => Ok(Self::Augment),
            "aura swap" => Ok(Self::AuraSwap),
            "awaken" => Ok(Self::Awaken),
            "backup" => Ok(Self::Backup),
            "banding" => Ok(Self::Banding),
            "bargain" => Ok(Self::Bargain),
            "basic landcycling" => Ok(Self::BasicLandcycling),
            "battle cry" => Ok(Self::BattleCry),
            "bestow" => Ok(Self::Bestow),
            "blitz" => Ok(Self::Blitz),
            "bloodthirst" => Ok(Self::Bloodthirst),
            "boast" => Ok(Self::Boast),
            "bushido" => Ok(Self::Bushido),
            "buyback" => Ok(Self::Buyback),
            "cascade" => Ok(Self::Cascade),
            "casualty" => Ok(Self::Casualty),
            "champion" => Ok(Self::Champion),
            "changeling" => Ok(Self::Changeling),
            "choose a background" => Ok(Self::ChooseABackground),
            "cipher" => Ok(Self::Cipher),
            "cleave" => Ok(Self::Cleave),
            "commander ninjutsu" => Ok(Self::CommanderNinjutsu),
            "companion" => Ok(Self::Companion),
            "compleated" => Ok(Self::Compleated),
            "conspire" => Ok(Self::Conspire),
            "convoke" => Ok(Self::Convoke),
            "craft" => Ok(Self::Craft),
            "crew" => Ok(Self::Crew),
            "cumulative upkeep" => Ok(Self::CumulativeUpkeep),
            "cycling" => Ok(Self::Cycling),
            "dash" => Ok(Self::Dash),
            "daybound" => Ok(Self::Daybound),
            "deathtouch" => Ok(Self::Deathtouch),
            "decayed" => Ok(Self::Decayed),
            "defender" => Ok(Self::Defender),
            "delve" => Ok(Self::Delve),
            "demonstrate" => Ok(Self::Demonstrate),
            "desertwalk" => Ok(Self::Desertwalk),
            "dethrone" => Ok(Self::Dethrone),
            "devoid" => Ok(Self::Devoid),
            "devour" => Ok(Self::Devour),
            "disguise" => Ok(Self::Disguise),
            "disturb" => Ok(Self::Disturb),
            "doctor's companion" => Ok(Self::DoctorsCompanion),
            "double agenda" => Ok(Self::DoubleAgenda),
            "double strike" => Ok(Self::DoubleStrike),
            "double team" => Ok(Self::DoubleTeam),
            "dredge" => Ok(Self::Dredge),
            "echo" => Ok(Self::Echo),
            "embalm" => Ok(Self::Embalm),
            "emerge" => Ok(Self::Emerge),
            "enchant" => Ok(Self::Enchant),
            "encore" => Ok(Self::Encore),
            "enlist" => Ok(Self::Enlist),
            "entwine" => Ok(Self::Entwine),
            "epic" => Ok(Self::Epic),
            "equip" => Ok(Self::Equip),
            "escalate" => Ok(Self::Escalate),
            "escape" => Ok(Self::Escape),
            "eternalize" => Ok(Self::Eternalize),
            "evoke" => Ok(Self::Evoke),
            "evolve" => Ok(Self::Evolve),
            "exalted" => Ok(Self::Exalted),
            "exhaust" => Ok(Self::Exhaust),
            "exploit" => Ok(Self::Exploit),
            "extort" => Ok(Self::Extort),
            "fabricate" => Ok(Self::Fabricate),
            "fading" => Ok(Self::Fading),
            "fear" => Ok(Self::Fear),
            "first strike" => Ok(Self::FirstStrike),
            "flanking" => Ok(Self::Flanking),
            "flash" => Ok(Self::Flash),
            "flashback" => Ok(Self::Flashback),
            "flying" => Ok(Self::Flying),
            "for mirrodin!" => Ok(Self::ForMirrodin),
            "forecast" => Ok(Self::Forecast),
            "forestcycling" => Ok(Self::Forestcycling),
            "forestwalk" => Ok(Self::Forestwalk),
            "foretell" => Ok(Self::Foretell),
            "fortify" => Ok(Self::Fortify),
            "freerunning" => Ok(Self::Freerunning),
            "frenzy" => Ok(Self::Frenzy),
            "friends forever" => Ok(Self::FriendsForever),
            "fuse" => Ok(Self::Fuse),
            "gift" => Ok(Self::Gift),
            "graft" => Ok(Self::Graft),
            "gravestorm" => Ok(Self::Gravestorm),
            "harmonize" => Ok(Self::Harmonize),
            "haste" => Ok(Self::Haste),
            "haunt" => Ok(Self::Haunt),
            "hexproof" => Ok(Self::Hexproof),
            "hexproof from" => Ok(Self::HexproofFrom),
            "hidden agenda" => Ok(Self::HiddenAgenda),
            "hideaway" => Ok(Self::Hideaway),
            "horsemanship" => Ok(Self::Horsemanship),
            "impending" => Ok(Self::Impending),
            "improvise" => Ok(Self::Improvise),
            "indestructible" => Ok(Self::Indestructible),
            "infect" => Ok(Self::Infect),
            "ingest" => Ok(Self::Ingest),
            "intensity" => Ok(Self::Intensity),
            "intimidate" => Ok(Self::Intimidate),
            "islandcycling" => Ok(Self::Islandcycling),
            "islandwalk" => Ok(Self::Islandwalk),
            "job select" => Ok(Self::JobSelect),
            "jump-start" => Ok(Self::JumpStart),
            "kicker" => Ok(Self::Kicker),
            "landcycling" => Ok(Self::Landcycling),
            "landwalk" => Ok(Self::Landwalk),
            "legendary landwalk" => Ok(Self::LegendaryLandwalk),
            "level up" => Ok(Self::LevelUp),
            "lifelink" => Ok(Self::Lifelink),
            "living metal" => Ok(Self::LivingMetal),
            "living weapon" => Ok(Self::LivingWeapon),
            "madness" => Ok(Self::Madness),
            "max speed" => Ok(Self::MaxSpeed),
            "mayhem" => Ok(Self::Mayhem),
            "megamorph" => Ok(Self::Megamorph),
            "melee" => Ok(Self::Melee),
            "menace" => Ok(Self::Menace),
            "mentor" => Ok(Self::Mentor),
            "miracle" => Ok(Self::Miracle),
            "mobilize" => Ok(Self::Mobilize),
            "modular" => Ok(Self::Modular),
            "more than meets the eye" => Ok(Self::MoreThanMeetsTheEye),
            "morph" => Ok(Self::Morph),
            "mountaincycling" => Ok(Self::Mountaincycling),
            "mountainwalk" => Ok(Self::Mountainwalk),
            "multikicker" => Ok(Self::Multikicker),
            "mutate" => Ok(Self::Mutate),
            "myriad" => Ok(Self::Myriad),
            "nightbound" => Ok(Self::Nightbound),
            "ninjutsu" => Ok(Self::Ninjutsu),
            "nonbasic landwalk" => Ok(Self::NonbasicLandwalk),
            "offering" => Ok(Self::Offering),
            "offspring" => Ok(Self::Offspring),
            "outlast" => Ok(Self::Outlast),
            "overload" => Ok(Self::Overload),
            "partner" => Ok(Self::Partner),
            "partner with" => Ok(Self::PartnerWith),
            "persist" => Ok(Self::Persist),
            "phasing" => Ok(Self::Phasing),
            "plainscycling" => Ok(Self::Plainscycling),
            "plainswalk" => Ok(Self::Plainswalk),
            "poisonous" => Ok(Self::Poisonous),
            "protection" => Ok(Self::Protection),
            "prototype" => Ok(Self::Prototype),
            "provoke" => Ok(Self::Provoke),
            "prowess" => Ok(Self::Prowess),
            "prowl" => Ok(Self::Prowl),
            "rampage" => Ok(Self::Rampage),
            "ravenous" => Ok(Self::Ravenous),
            "reach" => Ok(Self::Reach),
            "read ahead" => Ok(Self::ReadAhead),
            "rebound" => Ok(Self::Rebound),
            "reconfigure" => Ok(Self::Reconfigure),
            "recover" => Ok(Self::Recover),
            "reinforce" => Ok(Self::Reinforce),
            "renown" => Ok(Self::Renown),
            "replicate" => Ok(Self::Replicate),
            "retrace" => Ok(Self::Retrace),
            "riot" => Ok(Self::Riot),
            "ripple" => Ok(Self::Ripple),
            "saddle" => Ok(Self::Saddle),
            "scavenge" => Ok(Self::Scavenge),
            "shadow" => Ok(Self::Shadow),
            "shroud" => Ok(Self::Shroud),
            "skulk" => Ok(Self::Skulk),
            "slivercycling" => Ok(Self::Slivercycling),
            "soulbond" => Ok(Self::Soulbond),
            "soulshift" => Ok(Self::Soulshift),
            "specialize" => Ok(Self::Specialize),
            "spectacle" => Ok(Self::Spectacle),
            "splice" => Ok(Self::Splice),
            "split second" => Ok(Self::SplitSecond),
            "spree" => Ok(Self::Spree),
            "squad" => Ok(Self::Squad),
            "station" => Ok(Self::Station),
            "storm" => Ok(Self::Storm),
            "sunburst" => Ok(Self::Sunburst),
            "surge" => Ok(Self::Surge),
            "suspend" => Ok(Self::Suspend),
            "swampcycling" => Ok(Self::Swampcycling),
            "swampwalk" => Ok(Self::Swampwalk),
            "toxic" => Ok(Self::Toxic),
            "training" => Ok(Self::Training),
            "trample" => Ok(Self::Trample),
            "transfigure" => Ok(Self::Transfigure),
            "transmute" => Ok(Self::Transmute),
            "tribute" => Ok(Self::Tribute),
            "typecycling" => Ok(Self::Typecycling),
            "umbra armor" => Ok(Self::UmbraArmor),
            "undaunted" => Ok(Self::Undaunted),
            "undying" => Ok(Self::Undying),
            "unearth" => Ok(Self::Unearth),
            "unleash" => Ok(Self::Unleash),
            "vanishing" => Ok(Self::Vanishing),
            "vigilance" => Ok(Self::Vigilance),
            "ward" => Ok(Self::Ward),
            "warp" => Ok(Self::Warp),
            "web-slinging" => Ok(Self::WebSlinging),
            "wither" => Ok(Self::Wither),
            "wizardcycling" => Ok(Self::Wizardcycling),
            other => Err(format!("Unknown KeywordAbility: {}", other.to_string())),
        }
    }
}
impl KeywordAbility {
    fn as_str(&self) -> &'static str {
        match self {
            Self::Absorb => "absorb",
            Self::Affinity => "affinity",
            Self::Afflict => "afflict",
            Self::Afterlife => "afterlife",
            Self::Aftermath => "aftermath",
            Self::Amplify => "amplify",
            Self::Annihilator => "annihilator",
            Self::Ascend => "ascend",
            Self::Assist => "assist",
            Self::Augment => "augment",
            Self::AuraSwap => "aura swap",
            Self::Awaken => "awaken",
            Self::Backup => "backup",
            Self::Banding => "banding",
            Self::Bargain => "bargain",
            Self::BasicLandcycling => "basic landcycling",
            Self::BattleCry => "battle cry",
            Self::Bestow => "bestow",
            Self::Blitz => "blitz",
            Self::Bloodthirst => "bloodthirst",
            Self::Boast => "boast",
            Self::Bushido => "bushido",
            Self::Buyback => "buyback",
            Self::Cascade => "cascade",
            Self::Casualty => "casualty",
            Self::Champion => "champion",
            Self::Changeling => "changeling",
            Self::ChooseABackground => "choose a background",
            Self::Cipher => "cipher",
            Self::Cleave => "cleave",
            Self::CommanderNinjutsu => "commander ninjutsu",
            Self::Companion => "companion",
            Self::Compleated => "compleated",
            Self::Conspire => "conspire",
            Self::Convoke => "convoke",
            Self::Craft => "craft",
            Self::Crew => "crew",
            Self::CumulativeUpkeep => "cumulative upkeep",
            Self::Cycling => "cycling",
            Self::Dash => "dash",
            Self::Daybound => "daybound",
            Self::Deathtouch => "deathtouch",
            Self::Decayed => "decayed",
            Self::Defender => "defender",
            Self::Delve => "delve",
            Self::Demonstrate => "demonstrate",
            Self::Desertwalk => "desertwalk",
            Self::Dethrone => "dethrone",
            Self::Devoid => "devoid",
            Self::Devour => "devour",
            Self::Disguise => "disguise",
            Self::Disturb => "disturb",
            Self::DoctorsCompanion => "doctor's companion",
            Self::DoubleAgenda => "double agenda",
            Self::DoubleStrike => "double strike",
            Self::DoubleTeam => "double team",
            Self::Dredge => "dredge",
            Self::Echo => "echo",
            Self::Embalm => "embalm",
            Self::Emerge => "emerge",
            Self::Enchant => "enchant",
            Self::Encore => "encore",
            Self::Enlist => "enlist",
            Self::Entwine => "entwine",
            Self::Epic => "epic",
            Self::Equip => "equip",
            Self::Escalate => "escalate",
            Self::Escape => "escape",
            Self::Eternalize => "eternalize",
            Self::Evoke => "evoke",
            Self::Evolve => "evolve",
            Self::Exalted => "exalted",
            Self::Exhaust => "exhaust",
            Self::Exploit => "exploit",
            Self::Extort => "extort",
            Self::Fabricate => "fabricate",
            Self::Fading => "fading",
            Self::Fear => "fear",
            Self::FirstStrike => "first strike",
            Self::Flanking => "flanking",
            Self::Flash => "flash",
            Self::Flashback => "flashback",
            Self::Flying => "flying",
            Self::ForMirrodin => "for mirrodin!",
            Self::Forecast => "forecast",
            Self::Forestcycling => "forestcycling",
            Self::Forestwalk => "forestwalk",
            Self::Foretell => "foretell",
            Self::Fortify => "fortify",
            Self::Freerunning => "freerunning",
            Self::Frenzy => "frenzy",
            Self::FriendsForever => "friends forever",
            Self::Fuse => "fuse",
            Self::Gift => "gift",
            Self::Graft => "graft",
            Self::Gravestorm => "gravestorm",
            Self::Harmonize => "harmonize",
            Self::Haste => "haste",
            Self::Haunt => "haunt",
            Self::Hexproof => "hexproof",
            Self::HexproofFrom => "hexproof from",
            Self::HiddenAgenda => "hidden agenda",
            Self::Hideaway => "hideaway",
            Self::Horsemanship => "horsemanship",
            Self::Impending => "impending",
            Self::Improvise => "improvise",
            Self::Indestructible => "indestructible",
            Self::Infect => "infect",
            Self::Ingest => "ingest",
            Self::Intensity => "intensity",
            Self::Intimidate => "intimidate",
            Self::Islandcycling => "islandcycling",
            Self::Islandwalk => "islandwalk",
            Self::JobSelect => "job select",
            Self::JumpStart => "jump-start",
            Self::Kicker => "kicker",
            Self::Landcycling => "landcycling",
            Self::Landwalk => "landwalk",
            Self::LegendaryLandwalk => "legendary landwalk",
            Self::LevelUp => "level up",
            Self::Lifelink => "lifelink",
            Self::LivingMetal => "living metal",
            Self::LivingWeapon => "living weapon",
            Self::Madness => "madness",
            Self::MaxSpeed => "max speed",
            Self::Mayhem => "mayhem",
            Self::Megamorph => "megamorph",
            Self::Melee => "melee",
            Self::Menace => "menace",
            Self::Mentor => "mentor",
            Self::Miracle => "miracle",
            Self::Mobilize => "mobilize",
            Self::Modular => "modular",
            Self::MoreThanMeetsTheEye => "more than meets the eye",
            Self::Morph => "morph",
            Self::Mountaincycling => "mountaincycling",
            Self::Mountainwalk => "mountainwalk",
            Self::Multikicker => "multikicker",
            Self::Mutate => "mutate",
            Self::Myriad => "myriad",
            Self::Nightbound => "nightbound",
            Self::Ninjutsu => "ninjutsu",
            Self::NonbasicLandwalk => "nonbasic landwalk",
            Self::Offering => "offering",
            Self::Offspring => "offspring",
            Self::Outlast => "outlast",
            Self::Overload => "overload",
            Self::Partner => "partner",
            Self::PartnerWith => "partner with",
            Self::Persist => "persist",
            Self::Phasing => "phasing",
            Self::Plainscycling => "plainscycling",
            Self::Plainswalk => "plainswalk",
            Self::Poisonous => "poisonous",
            Self::Protection => "protection",
            Self::Prototype => "prototype",
            Self::Provoke => "provoke",
            Self::Prowess => "prowess",
            Self::Prowl => "prowl",
            Self::Rampage => "rampage",
            Self::Ravenous => "ravenous",
            Self::Reach => "reach",
            Self::ReadAhead => "read ahead",
            Self::Rebound => "rebound",
            Self::Reconfigure => "reconfigure",
            Self::Recover => "recover",
            Self::Reinforce => "reinforce",
            Self::Renown => "renown",
            Self::Replicate => "replicate",
            Self::Retrace => "retrace",
            Self::Riot => "riot",
            Self::Ripple => "ripple",
            Self::Saddle => "saddle",
            Self::Scavenge => "scavenge",
            Self::Shadow => "shadow",
            Self::Shroud => "shroud",
            Self::Skulk => "skulk",
            Self::Slivercycling => "slivercycling",
            Self::Soulbond => "soulbond",
            Self::Soulshift => "soulshift",
            Self::Specialize => "specialize",
            Self::Spectacle => "spectacle",
            Self::Splice => "splice",
            Self::SplitSecond => "split second",
            Self::Spree => "spree",
            Self::Squad => "squad",
            Self::Station => "station",
            Self::Storm => "storm",
            Self::Sunburst => "sunburst",
            Self::Surge => "surge",
            Self::Suspend => "suspend",
            Self::Swampcycling => "swampcycling",
            Self::Swampwalk => "swampwalk",
            Self::Toxic => "toxic",
            Self::Training => "training",
            Self::Trample => "trample",
            Self::Transfigure => "transfigure",
            Self::Transmute => "transmute",
            Self::Tribute => "tribute",
            Self::Typecycling => "typecycling",
            Self::UmbraArmor => "umbra armor",
            Self::Undaunted => "undaunted",
            Self::Undying => "undying",
            Self::Unearth => "unearth",
            Self::Unleash => "unleash",
            Self::Vanishing => "vanishing",
            Self::Vigilance => "vigilance",
            Self::Ward => "ward",
            Self::Warp => "warp",
            Self::WebSlinging => "web-slinging",
            Self::Wither => "wither",
            Self::Wizardcycling => "wizardcycling",
        }
    }
}
impl std::fmt::Display for KeywordAbility {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
impl KeywordAbility {
    pub fn all() -> impl Iterator<Item = Self> {
        [
            Self::Absorb,
            Self::Affinity,
            Self::Afflict,
            Self::Afterlife,
            Self::Aftermath,
            Self::Amplify,
            Self::Annihilator,
            Self::Ascend,
            Self::Assist,
            Self::Augment,
            Self::AuraSwap,
            Self::Awaken,
            Self::Backup,
            Self::Banding,
            Self::Bargain,
            Self::BasicLandcycling,
            Self::BattleCry,
            Self::Bestow,
            Self::Blitz,
            Self::Bloodthirst,
            Self::Boast,
            Self::Bushido,
            Self::Buyback,
            Self::Cascade,
            Self::Casualty,
            Self::Champion,
            Self::Changeling,
            Self::ChooseABackground,
            Self::Cipher,
            Self::Cleave,
            Self::CommanderNinjutsu,
            Self::Companion,
            Self::Compleated,
            Self::Conspire,
            Self::Convoke,
            Self::Craft,
            Self::Crew,
            Self::CumulativeUpkeep,
            Self::Cycling,
            Self::Dash,
            Self::Daybound,
            Self::Deathtouch,
            Self::Decayed,
            Self::Defender,
            Self::Delve,
            Self::Demonstrate,
            Self::Desertwalk,
            Self::Dethrone,
            Self::Devoid,
            Self::Devour,
            Self::Disguise,
            Self::Disturb,
            Self::DoctorsCompanion,
            Self::DoubleAgenda,
            Self::DoubleStrike,
            Self::DoubleTeam,
            Self::Dredge,
            Self::Echo,
            Self::Embalm,
            Self::Emerge,
            Self::Enchant,
            Self::Encore,
            Self::Enlist,
            Self::Entwine,
            Self::Epic,
            Self::Equip,
            Self::Escalate,
            Self::Escape,
            Self::Eternalize,
            Self::Evoke,
            Self::Evolve,
            Self::Exalted,
            Self::Exhaust,
            Self::Exploit,
            Self::Extort,
            Self::Fabricate,
            Self::Fading,
            Self::Fear,
            Self::FirstStrike,
            Self::Flanking,
            Self::Flash,
            Self::Flashback,
            Self::Flying,
            Self::ForMirrodin,
            Self::Forecast,
            Self::Forestcycling,
            Self::Forestwalk,
            Self::Foretell,
            Self::Fortify,
            Self::Freerunning,
            Self::Frenzy,
            Self::FriendsForever,
            Self::Fuse,
            Self::Gift,
            Self::Graft,
            Self::Gravestorm,
            Self::Harmonize,
            Self::Haste,
            Self::Haunt,
            Self::Hexproof,
            Self::HexproofFrom,
            Self::HiddenAgenda,
            Self::Hideaway,
            Self::Horsemanship,
            Self::Impending,
            Self::Improvise,
            Self::Indestructible,
            Self::Infect,
            Self::Ingest,
            Self::Intensity,
            Self::Intimidate,
            Self::Islandcycling,
            Self::Islandwalk,
            Self::JobSelect,
            Self::JumpStart,
            Self::Kicker,
            Self::Landcycling,
            Self::Landwalk,
            Self::LegendaryLandwalk,
            Self::LevelUp,
            Self::Lifelink,
            Self::LivingMetal,
            Self::LivingWeapon,
            Self::Madness,
            Self::MaxSpeed,
            Self::Mayhem,
            Self::Megamorph,
            Self::Melee,
            Self::Menace,
            Self::Mentor,
            Self::Miracle,
            Self::Mobilize,
            Self::Modular,
            Self::MoreThanMeetsTheEye,
            Self::Morph,
            Self::Mountaincycling,
            Self::Mountainwalk,
            Self::Multikicker,
            Self::Mutate,
            Self::Myriad,
            Self::Nightbound,
            Self::Ninjutsu,
            Self::NonbasicLandwalk,
            Self::Offering,
            Self::Offspring,
            Self::Outlast,
            Self::Overload,
            Self::Partner,
            Self::PartnerWith,
            Self::Persist,
            Self::Phasing,
            Self::Plainscycling,
            Self::Plainswalk,
            Self::Poisonous,
            Self::Protection,
            Self::Prototype,
            Self::Provoke,
            Self::Prowess,
            Self::Prowl,
            Self::Rampage,
            Self::Ravenous,
            Self::Reach,
            Self::ReadAhead,
            Self::Rebound,
            Self::Reconfigure,
            Self::Recover,
            Self::Reinforce,
            Self::Renown,
            Self::Replicate,
            Self::Retrace,
            Self::Riot,
            Self::Ripple,
            Self::Saddle,
            Self::Scavenge,
            Self::Shadow,
            Self::Shroud,
            Self::Skulk,
            Self::Slivercycling,
            Self::Soulbond,
            Self::Soulshift,
            Self::Specialize,
            Self::Spectacle,
            Self::Splice,
            Self::SplitSecond,
            Self::Spree,
            Self::Squad,
            Self::Station,
            Self::Storm,
            Self::Sunburst,
            Self::Surge,
            Self::Suspend,
            Self::Swampcycling,
            Self::Swampwalk,
            Self::Toxic,
            Self::Training,
            Self::Trample,
            Self::Transfigure,
            Self::Transmute,
            Self::Tribute,
            Self::Typecycling,
            Self::UmbraArmor,
            Self::Undaunted,
            Self::Undying,
            Self::Unearth,
            Self::Unleash,
            Self::Vanishing,
            Self::Vigilance,
            Self::Ward,
            Self::Warp,
            Self::WebSlinging,
            Self::Wither,
            Self::Wizardcycling,
        ]
        .into_iter()
    }
}
