#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum KeywordAbility {
    Absorb,
    Affinity,
    Afflict,
    Afterlife,
    Aftermath,
    Amplify,
    Annihilator,
    Ascend,
    Assist,
    Augment,
    AuraSwap,
    Awaken,
    Backup,
    Banding,
    Bargain,
    BasicLandcycling,
    BattleCry,
    Bestow,
    Blitz,
    Bloodthirst,
    Boast,
    Bushido,
    Buyback,
    Cascade,
    Casualty,
    Champion,
    Changeling,
    ChooseABackground,
    Cipher,
    Cleave,
    CommanderNinjutsu,
    Companion,
    Compleated,
    Conspire,
    Convoke,
    Craft,
    Crew,
    CumulativeUpkeep,
    Cycling,
    Dash,
    Daybound,
    Deathtouch,
    Decayed,
    Defender,
    Delve,
    Demonstrate,
    Desertwalk,
    Dethrone,
    Devoid,
    Devour,
    Disguise,
    Disturb,
    DoctorsCompanion,
    DoubleAgenda,
    DoubleStrike,
    DoubleTeam,
    Dredge,
    Echo,
    Embalm,
    Emerge,
    Enchant,
    Encore,
    Enlist,
    Entwine,
    Epic,
    Equip,
    Escalate,
    Escape,
    Eternalize,
    Evoke,
    Evolve,
    Exalted,
    Exhaust,
    Exploit,
    Extort,
    Fabricate,
    Fading,
    Fear,
    FirstStrike,
    Flanking,
    Flash,
    Flashback,
    Flying,
    ForMirrodin,
    Forecast,
    Forestcycling,
    Forestwalk,
    Foretell,
    Fortify,
    Freerunning,
    Frenzy,
    FriendsForever,
    Fuse,
    Gift,
    Graft,
    Gravestorm,
    Harmonize,
    Haste,
    Haunt,
    Hexproof,
    HexproofFrom,
    HiddenAgenda,
    Hideaway,
    Horsemanship,
    Impending,
    Improvise,
    Indestructible,
    Infect,
    Ingest,
    Intensity,
    Intimidate,
    Islandcycling,
    Islandwalk,
    JobSelect,
    JumpStart,
    Kicker,
    Landcycling,
    Landwalk,
    LegendaryLandwalk,
    LevelUp,
    Lifelink,
    LivingMetal,
    LivingWeapon,
    Madness,
    MaxSpeed,
    Mayhem,
    Megamorph,
    Melee,
    Menace,
    Mentor,
    Miracle,
    Mobilize,
    Modular,
    MoreThanMeetsTheEye,
    Morph,
    Mountaincycling,
    Mountainwalk,
    Multikicker,
    Mutate,
    Myriad,
    Nightbound,
    Ninjutsu,
    NonbasicLandwalk,
    Offering,
    Offspring,
    Outlast,
    Overload,
    Partner,
    PartnerWith,
    Persist,
    Phasing,
    Plainscycling,
    Plainswalk,
    Poisonous,
    Protection,
    Prototype,
    Provoke,
    Prowess,
    Prowl,
    Rampage,
    Ravenous,
    Reach,
    ReadAhead,
    Rebound,
    Reconfigure,
    Recover,
    Reinforce,
    Renown,
    Replicate,
    Retrace,
    Riot,
    Ripple,
    Saddle,
    Scavenge,
    Shadow,
    Shroud,
    Skulk,
    Slivercycling,
    Soulbond,
    Soulshift,
    Specialize,
    Spectacle,
    Splice,
    SplitSecond,
    Spree,
    Squad,
    Station,
    Storm,
    Sunburst,
    Surge,
    Suspend,
    Swampcycling,
    Swampwalk,
    Toxic,
    Training,
    Trample,
    Transfigure,
    Transmute,
    Tribute,
    Typecycling,
    UmbraArmor,
    Undaunted,
    Undying,
    Unearth,
    Unleash,
    Vanishing,
    Vigilance,
    Ward,
    Warp,
    WebSlinging,
    Wither,
    Wizardcycling,
}
impl std::str::FromStr for KeywordAbility {
    type Err = String;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Absorb" => Ok(Self::Absorb),
            "Affinity" => Ok(Self::Affinity),
            "Afflict" => Ok(Self::Afflict),
            "Afterlife" => Ok(Self::Afterlife),
            "Aftermath" => Ok(Self::Aftermath),
            "Amplify" => Ok(Self::Amplify),
            "Annihilator" => Ok(Self::Annihilator),
            "Ascend" => Ok(Self::Ascend),
            "Assist" => Ok(Self::Assist),
            "Augment" => Ok(Self::Augment),
            "Aura Swap" => Ok(Self::AuraSwap),
            "Awaken" => Ok(Self::Awaken),
            "Backup" => Ok(Self::Backup),
            "Banding" => Ok(Self::Banding),
            "Bargain" => Ok(Self::Bargain),
            "Basic landcycling" => Ok(Self::BasicLandcycling),
            "Battle Cry" => Ok(Self::BattleCry),
            "Bestow" => Ok(Self::Bestow),
            "Blitz" => Ok(Self::Blitz),
            "Bloodthirst" => Ok(Self::Bloodthirst),
            "Boast" => Ok(Self::Boast),
            "Bushido" => Ok(Self::Bushido),
            "Buyback" => Ok(Self::Buyback),
            "Cascade" => Ok(Self::Cascade),
            "Casualty" => Ok(Self::Casualty),
            "Champion" => Ok(Self::Champion),
            "Changeling" => Ok(Self::Changeling),
            "Choose a background" => Ok(Self::ChooseABackground),
            "Cipher" => Ok(Self::Cipher),
            "Cleave" => Ok(Self::Cleave),
            "Commander ninjutsu" => Ok(Self::CommanderNinjutsu),
            "Companion" => Ok(Self::Companion),
            "Compleated" => Ok(Self::Compleated),
            "Conspire" => Ok(Self::Conspire),
            "Convoke" => Ok(Self::Convoke),
            "Craft" => Ok(Self::Craft),
            "Crew" => Ok(Self::Crew),
            "Cumulative upkeep" => Ok(Self::CumulativeUpkeep),
            "Cycling" => Ok(Self::Cycling),
            "Dash" => Ok(Self::Dash),
            "Daybound" => Ok(Self::Daybound),
            "Deathtouch" => Ok(Self::Deathtouch),
            "Decayed" => Ok(Self::Decayed),
            "Defender" => Ok(Self::Defender),
            "Delve" => Ok(Self::Delve),
            "Demonstrate" => Ok(Self::Demonstrate),
            "Desertwalk" => Ok(Self::Desertwalk),
            "Dethrone" => Ok(Self::Dethrone),
            "Devoid" => Ok(Self::Devoid),
            "Devour" => Ok(Self::Devour),
            "Disguise" => Ok(Self::Disguise),
            "Disturb" => Ok(Self::Disturb),
            "Doctor's companion" => Ok(Self::DoctorsCompanion),
            "Double agenda" => Ok(Self::DoubleAgenda),
            "Double strike" => Ok(Self::DoubleStrike),
            "Double team" => Ok(Self::DoubleTeam),
            "Dredge" => Ok(Self::Dredge),
            "Echo" => Ok(Self::Echo),
            "Embalm" => Ok(Self::Embalm),
            "Emerge" => Ok(Self::Emerge),
            "Enchant" => Ok(Self::Enchant),
            "Encore" => Ok(Self::Encore),
            "Enlist" => Ok(Self::Enlist),
            "Entwine" => Ok(Self::Entwine),
            "Epic" => Ok(Self::Epic),
            "Equip" => Ok(Self::Equip),
            "Escalate" => Ok(Self::Escalate),
            "Escape" => Ok(Self::Escape),
            "Eternalize" => Ok(Self::Eternalize),
            "Evoke" => Ok(Self::Evoke),
            "Evolve" => Ok(Self::Evolve),
            "Exalted" => Ok(Self::Exalted),
            "Exhaust" => Ok(Self::Exhaust),
            "Exploit" => Ok(Self::Exploit),
            "Extort" => Ok(Self::Extort),
            "Fabricate" => Ok(Self::Fabricate),
            "Fading" => Ok(Self::Fading),
            "Fear" => Ok(Self::Fear),
            "First strike" => Ok(Self::FirstStrike),
            "Flanking" => Ok(Self::Flanking),
            "Flash" => Ok(Self::Flash),
            "Flashback" => Ok(Self::Flashback),
            "Flying" => Ok(Self::Flying),
            "For Mirrodin!" => Ok(Self::ForMirrodin),
            "Forecast" => Ok(Self::Forecast),
            "Forestcycling" => Ok(Self::Forestcycling),
            "Forestwalk" => Ok(Self::Forestwalk),
            "Foretell" => Ok(Self::Foretell),
            "Fortify" => Ok(Self::Fortify),
            "Freerunning" => Ok(Self::Freerunning),
            "Frenzy" => Ok(Self::Frenzy),
            "Friends forever" => Ok(Self::FriendsForever),
            "Fuse" => Ok(Self::Fuse),
            "Gift" => Ok(Self::Gift),
            "Graft" => Ok(Self::Graft),
            "Gravestorm" => Ok(Self::Gravestorm),
            "Harmonize" => Ok(Self::Harmonize),
            "Haste" => Ok(Self::Haste),
            "Haunt" => Ok(Self::Haunt),
            "Hexproof" => Ok(Self::Hexproof),
            "Hexproof from" => Ok(Self::HexproofFrom),
            "Hidden agenda" => Ok(Self::HiddenAgenda),
            "Hideaway" => Ok(Self::Hideaway),
            "Horsemanship" => Ok(Self::Horsemanship),
            "Impending" => Ok(Self::Impending),
            "Improvise" => Ok(Self::Improvise),
            "Indestructible" => Ok(Self::Indestructible),
            "Infect" => Ok(Self::Infect),
            "Ingest" => Ok(Self::Ingest),
            "Intensity" => Ok(Self::Intensity),
            "Intimidate" => Ok(Self::Intimidate),
            "Islandcycling" => Ok(Self::Islandcycling),
            "Islandwalk" => Ok(Self::Islandwalk),
            "Job select" => Ok(Self::JobSelect),
            "Jump-start" => Ok(Self::JumpStart),
            "Kicker" => Ok(Self::Kicker),
            "Landcycling" => Ok(Self::Landcycling),
            "Landwalk" => Ok(Self::Landwalk),
            "Legendary landwalk" => Ok(Self::LegendaryLandwalk),
            "Level Up" => Ok(Self::LevelUp),
            "Lifelink" => Ok(Self::Lifelink),
            "Living metal" => Ok(Self::LivingMetal),
            "Living weapon" => Ok(Self::LivingWeapon),
            "Madness" => Ok(Self::Madness),
            "Max speed" => Ok(Self::MaxSpeed),
            "Mayhem" => Ok(Self::Mayhem),
            "Megamorph" => Ok(Self::Megamorph),
            "Melee" => Ok(Self::Melee),
            "Menace" => Ok(Self::Menace),
            "Mentor" => Ok(Self::Mentor),
            "Miracle" => Ok(Self::Miracle),
            "Mobilize" => Ok(Self::Mobilize),
            "Modular" => Ok(Self::Modular),
            "More Than Meets the Eye" => Ok(Self::MoreThanMeetsTheEye),
            "Morph" => Ok(Self::Morph),
            "Mountaincycling" => Ok(Self::Mountaincycling),
            "Mountainwalk" => Ok(Self::Mountainwalk),
            "Multikicker" => Ok(Self::Multikicker),
            "Mutate" => Ok(Self::Mutate),
            "Myriad" => Ok(Self::Myriad),
            "Nightbound" => Ok(Self::Nightbound),
            "Ninjutsu" => Ok(Self::Ninjutsu),
            "Nonbasic landwalk" => Ok(Self::NonbasicLandwalk),
            "Offering" => Ok(Self::Offering),
            "Offspring" => Ok(Self::Offspring),
            "Outlast" => Ok(Self::Outlast),
            "Overload" => Ok(Self::Overload),
            "Partner" => Ok(Self::Partner),
            "Partner with" => Ok(Self::PartnerWith),
            "Persist" => Ok(Self::Persist),
            "Phasing" => Ok(Self::Phasing),
            "Plainscycling" => Ok(Self::Plainscycling),
            "Plainswalk" => Ok(Self::Plainswalk),
            "Poisonous" => Ok(Self::Poisonous),
            "Protection" => Ok(Self::Protection),
            "Prototype" => Ok(Self::Prototype),
            "Provoke" => Ok(Self::Provoke),
            "Prowess" => Ok(Self::Prowess),
            "Prowl" => Ok(Self::Prowl),
            "Rampage" => Ok(Self::Rampage),
            "Ravenous" => Ok(Self::Ravenous),
            "Reach" => Ok(Self::Reach),
            "Read Ahead" => Ok(Self::ReadAhead),
            "Rebound" => Ok(Self::Rebound),
            "Reconfigure" => Ok(Self::Reconfigure),
            "Recover" => Ok(Self::Recover),
            "Reinforce" => Ok(Self::Reinforce),
            "Renown" => Ok(Self::Renown),
            "Replicate" => Ok(Self::Replicate),
            "Retrace" => Ok(Self::Retrace),
            "Riot" => Ok(Self::Riot),
            "Ripple" => Ok(Self::Ripple),
            "Saddle" => Ok(Self::Saddle),
            "Scavenge" => Ok(Self::Scavenge),
            "Shadow" => Ok(Self::Shadow),
            "Shroud" => Ok(Self::Shroud),
            "Skulk" => Ok(Self::Skulk),
            "Slivercycling" => Ok(Self::Slivercycling),
            "Soulbond" => Ok(Self::Soulbond),
            "Soulshift" => Ok(Self::Soulshift),
            "Specialize" => Ok(Self::Specialize),
            "Spectacle" => Ok(Self::Spectacle),
            "Splice" => Ok(Self::Splice),
            "Split second" => Ok(Self::SplitSecond),
            "Spree" => Ok(Self::Spree),
            "Squad" => Ok(Self::Squad),
            "Station" => Ok(Self::Station),
            "Storm" => Ok(Self::Storm),
            "Sunburst" => Ok(Self::Sunburst),
            "Surge" => Ok(Self::Surge),
            "Suspend" => Ok(Self::Suspend),
            "Swampcycling" => Ok(Self::Swampcycling),
            "Swampwalk" => Ok(Self::Swampwalk),
            "Toxic" => Ok(Self::Toxic),
            "Training" => Ok(Self::Training),
            "Trample" => Ok(Self::Trample),
            "Transfigure" => Ok(Self::Transfigure),
            "Transmute" => Ok(Self::Transmute),
            "Tribute" => Ok(Self::Tribute),
            "Typecycling" => Ok(Self::Typecycling),
            "Umbra armor" => Ok(Self::UmbraArmor),
            "Undaunted" => Ok(Self::Undaunted),
            "Undying" => Ok(Self::Undying),
            "Unearth" => Ok(Self::Unearth),
            "Unleash" => Ok(Self::Unleash),
            "Vanishing" => Ok(Self::Vanishing),
            "Vigilance" => Ok(Self::Vigilance),
            "Ward" => Ok(Self::Ward),
            "Warp" => Ok(Self::Warp),
            "Web-slinging" => Ok(Self::WebSlinging),
            "Wither" => Ok(Self::Wither),
            "Wizardcycling" => Ok(Self::Wizardcycling),
            other => Err(format!("Unknown KeywordAbility: {}", other.to_string())),
        }
    }
}
impl KeywordAbility {
    fn as_str(&self) -> &'static str {
        match self {
            Self::Absorb => "Absorb",
            Self::Affinity => "Affinity",
            Self::Afflict => "Afflict",
            Self::Afterlife => "Afterlife",
            Self::Aftermath => "Aftermath",
            Self::Amplify => "Amplify",
            Self::Annihilator => "Annihilator",
            Self::Ascend => "Ascend",
            Self::Assist => "Assist",
            Self::Augment => "Augment",
            Self::AuraSwap => "Aura Swap",
            Self::Awaken => "Awaken",
            Self::Backup => "Backup",
            Self::Banding => "Banding",
            Self::Bargain => "Bargain",
            Self::BasicLandcycling => "Basic landcycling",
            Self::BattleCry => "Battle Cry",
            Self::Bestow => "Bestow",
            Self::Blitz => "Blitz",
            Self::Bloodthirst => "Bloodthirst",
            Self::Boast => "Boast",
            Self::Bushido => "Bushido",
            Self::Buyback => "Buyback",
            Self::Cascade => "Cascade",
            Self::Casualty => "Casualty",
            Self::Champion => "Champion",
            Self::Changeling => "Changeling",
            Self::ChooseABackground => "Choose a background",
            Self::Cipher => "Cipher",
            Self::Cleave => "Cleave",
            Self::CommanderNinjutsu => "Commander ninjutsu",
            Self::Companion => "Companion",
            Self::Compleated => "Compleated",
            Self::Conspire => "Conspire",
            Self::Convoke => "Convoke",
            Self::Craft => "Craft",
            Self::Crew => "Crew",
            Self::CumulativeUpkeep => "Cumulative upkeep",
            Self::Cycling => "Cycling",
            Self::Dash => "Dash",
            Self::Daybound => "Daybound",
            Self::Deathtouch => "Deathtouch",
            Self::Decayed => "Decayed",
            Self::Defender => "Defender",
            Self::Delve => "Delve",
            Self::Demonstrate => "Demonstrate",
            Self::Desertwalk => "Desertwalk",
            Self::Dethrone => "Dethrone",
            Self::Devoid => "Devoid",
            Self::Devour => "Devour",
            Self::Disguise => "Disguise",
            Self::Disturb => "Disturb",
            Self::DoctorsCompanion => "Doctor's companion",
            Self::DoubleAgenda => "Double agenda",
            Self::DoubleStrike => "Double strike",
            Self::DoubleTeam => "Double team",
            Self::Dredge => "Dredge",
            Self::Echo => "Echo",
            Self::Embalm => "Embalm",
            Self::Emerge => "Emerge",
            Self::Enchant => "Enchant",
            Self::Encore => "Encore",
            Self::Enlist => "Enlist",
            Self::Entwine => "Entwine",
            Self::Epic => "Epic",
            Self::Equip => "Equip",
            Self::Escalate => "Escalate",
            Self::Escape => "Escape",
            Self::Eternalize => "Eternalize",
            Self::Evoke => "Evoke",
            Self::Evolve => "Evolve",
            Self::Exalted => "Exalted",
            Self::Exhaust => "Exhaust",
            Self::Exploit => "Exploit",
            Self::Extort => "Extort",
            Self::Fabricate => "Fabricate",
            Self::Fading => "Fading",
            Self::Fear => "Fear",
            Self::FirstStrike => "First strike",
            Self::Flanking => "Flanking",
            Self::Flash => "Flash",
            Self::Flashback => "Flashback",
            Self::Flying => "Flying",
            Self::ForMirrodin => "For Mirrodin!",
            Self::Forecast => "Forecast",
            Self::Forestcycling => "Forestcycling",
            Self::Forestwalk => "Forestwalk",
            Self::Foretell => "Foretell",
            Self::Fortify => "Fortify",
            Self::Freerunning => "Freerunning",
            Self::Frenzy => "Frenzy",
            Self::FriendsForever => "Friends forever",
            Self::Fuse => "Fuse",
            Self::Gift => "Gift",
            Self::Graft => "Graft",
            Self::Gravestorm => "Gravestorm",
            Self::Harmonize => "Harmonize",
            Self::Haste => "Haste",
            Self::Haunt => "Haunt",
            Self::Hexproof => "Hexproof",
            Self::HexproofFrom => "Hexproof from",
            Self::HiddenAgenda => "Hidden agenda",
            Self::Hideaway => "Hideaway",
            Self::Horsemanship => "Horsemanship",
            Self::Impending => "Impending",
            Self::Improvise => "Improvise",
            Self::Indestructible => "Indestructible",
            Self::Infect => "Infect",
            Self::Ingest => "Ingest",
            Self::Intensity => "Intensity",
            Self::Intimidate => "Intimidate",
            Self::Islandcycling => "Islandcycling",
            Self::Islandwalk => "Islandwalk",
            Self::JobSelect => "Job select",
            Self::JumpStart => "Jump-start",
            Self::Kicker => "Kicker",
            Self::Landcycling => "Landcycling",
            Self::Landwalk => "Landwalk",
            Self::LegendaryLandwalk => "Legendary landwalk",
            Self::LevelUp => "Level Up",
            Self::Lifelink => "Lifelink",
            Self::LivingMetal => "Living metal",
            Self::LivingWeapon => "Living weapon",
            Self::Madness => "Madness",
            Self::MaxSpeed => "Max speed",
            Self::Mayhem => "Mayhem",
            Self::Megamorph => "Megamorph",
            Self::Melee => "Melee",
            Self::Menace => "Menace",
            Self::Mentor => "Mentor",
            Self::Miracle => "Miracle",
            Self::Mobilize => "Mobilize",
            Self::Modular => "Modular",
            Self::MoreThanMeetsTheEye => "More Than Meets the Eye",
            Self::Morph => "Morph",
            Self::Mountaincycling => "Mountaincycling",
            Self::Mountainwalk => "Mountainwalk",
            Self::Multikicker => "Multikicker",
            Self::Mutate => "Mutate",
            Self::Myriad => "Myriad",
            Self::Nightbound => "Nightbound",
            Self::Ninjutsu => "Ninjutsu",
            Self::NonbasicLandwalk => "Nonbasic landwalk",
            Self::Offering => "Offering",
            Self::Offspring => "Offspring",
            Self::Outlast => "Outlast",
            Self::Overload => "Overload",
            Self::Partner => "Partner",
            Self::PartnerWith => "Partner with",
            Self::Persist => "Persist",
            Self::Phasing => "Phasing",
            Self::Plainscycling => "Plainscycling",
            Self::Plainswalk => "Plainswalk",
            Self::Poisonous => "Poisonous",
            Self::Protection => "Protection",
            Self::Prototype => "Prototype",
            Self::Provoke => "Provoke",
            Self::Prowess => "Prowess",
            Self::Prowl => "Prowl",
            Self::Rampage => "Rampage",
            Self::Ravenous => "Ravenous",
            Self::Reach => "Reach",
            Self::ReadAhead => "Read Ahead",
            Self::Rebound => "Rebound",
            Self::Reconfigure => "Reconfigure",
            Self::Recover => "Recover",
            Self::Reinforce => "Reinforce",
            Self::Renown => "Renown",
            Self::Replicate => "Replicate",
            Self::Retrace => "Retrace",
            Self::Riot => "Riot",
            Self::Ripple => "Ripple",
            Self::Saddle => "Saddle",
            Self::Scavenge => "Scavenge",
            Self::Shadow => "Shadow",
            Self::Shroud => "Shroud",
            Self::Skulk => "Skulk",
            Self::Slivercycling => "Slivercycling",
            Self::Soulbond => "Soulbond",
            Self::Soulshift => "Soulshift",
            Self::Specialize => "Specialize",
            Self::Spectacle => "Spectacle",
            Self::Splice => "Splice",
            Self::SplitSecond => "Split second",
            Self::Spree => "Spree",
            Self::Squad => "Squad",
            Self::Station => "Station",
            Self::Storm => "Storm",
            Self::Sunburst => "Sunburst",
            Self::Surge => "Surge",
            Self::Suspend => "Suspend",
            Self::Swampcycling => "Swampcycling",
            Self::Swampwalk => "Swampwalk",
            Self::Toxic => "Toxic",
            Self::Training => "Training",
            Self::Trample => "Trample",
            Self::Transfigure => "Transfigure",
            Self::Transmute => "Transmute",
            Self::Tribute => "Tribute",
            Self::Typecycling => "Typecycling",
            Self::UmbraArmor => "Umbra armor",
            Self::Undaunted => "Undaunted",
            Self::Undying => "Undying",
            Self::Unearth => "Unearth",
            Self::Unleash => "Unleash",
            Self::Vanishing => "Vanishing",
            Self::Vigilance => "Vigilance",
            Self::Ward => "Ward",
            Self::Warp => "Warp",
            Self::WebSlinging => "Web-slinging",
            Self::Wither => "Wither",
            Self::Wizardcycling => "Wizardcycling",
        }
    }
}
impl std::fmt::Display for KeywordAbility {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
impl KeywordAbility {
    pub fn all() -> impl Iterator<Item = Self> {
        [
            Self::Absorb,
            Self::Affinity,
            Self::Afflict,
            Self::Afterlife,
            Self::Aftermath,
            Self::Amplify,
            Self::Annihilator,
            Self::Ascend,
            Self::Assist,
            Self::Augment,
            Self::AuraSwap,
            Self::Awaken,
            Self::Backup,
            Self::Banding,
            Self::Bargain,
            Self::BasicLandcycling,
            Self::BattleCry,
            Self::Bestow,
            Self::Blitz,
            Self::Bloodthirst,
            Self::Boast,
            Self::Bushido,
            Self::Buyback,
            Self::Cascade,
            Self::Casualty,
            Self::Champion,
            Self::Changeling,
            Self::ChooseABackground,
            Self::Cipher,
            Self::Cleave,
            Self::CommanderNinjutsu,
            Self::Companion,
            Self::Compleated,
            Self::Conspire,
            Self::Convoke,
            Self::Craft,
            Self::Crew,
            Self::CumulativeUpkeep,
            Self::Cycling,
            Self::Dash,
            Self::Daybound,
            Self::Deathtouch,
            Self::Decayed,
            Self::Defender,
            Self::Delve,
            Self::Demonstrate,
            Self::Desertwalk,
            Self::Dethrone,
            Self::Devoid,
            Self::Devour,
            Self::Disguise,
            Self::Disturb,
            Self::DoctorsCompanion,
            Self::DoubleAgenda,
            Self::DoubleStrike,
            Self::DoubleTeam,
            Self::Dredge,
            Self::Echo,
            Self::Embalm,
            Self::Emerge,
            Self::Enchant,
            Self::Encore,
            Self::Enlist,
            Self::Entwine,
            Self::Epic,
            Self::Equip,
            Self::Escalate,
            Self::Escape,
            Self::Eternalize,
            Self::Evoke,
            Self::Evolve,
            Self::Exalted,
            Self::Exhaust,
            Self::Exploit,
            Self::Extort,
            Self::Fabricate,
            Self::Fading,
            Self::Fear,
            Self::FirstStrike,
            Self::Flanking,
            Self::Flash,
            Self::Flashback,
            Self::Flying,
            Self::ForMirrodin,
            Self::Forecast,
            Self::Forestcycling,
            Self::Forestwalk,
            Self::Foretell,
            Self::Fortify,
            Self::Freerunning,
            Self::Frenzy,
            Self::FriendsForever,
            Self::Fuse,
            Self::Gift,
            Self::Graft,
            Self::Gravestorm,
            Self::Harmonize,
            Self::Haste,
            Self::Haunt,
            Self::Hexproof,
            Self::HexproofFrom,
            Self::HiddenAgenda,
            Self::Hideaway,
            Self::Horsemanship,
            Self::Impending,
            Self::Improvise,
            Self::Indestructible,
            Self::Infect,
            Self::Ingest,
            Self::Intensity,
            Self::Intimidate,
            Self::Islandcycling,
            Self::Islandwalk,
            Self::JobSelect,
            Self::JumpStart,
            Self::Kicker,
            Self::Landcycling,
            Self::Landwalk,
            Self::LegendaryLandwalk,
            Self::LevelUp,
            Self::Lifelink,
            Self::LivingMetal,
            Self::LivingWeapon,
            Self::Madness,
            Self::MaxSpeed,
            Self::Mayhem,
            Self::Megamorph,
            Self::Melee,
            Self::Menace,
            Self::Mentor,
            Self::Miracle,
            Self::Mobilize,
            Self::Modular,
            Self::MoreThanMeetsTheEye,
            Self::Morph,
            Self::Mountaincycling,
            Self::Mountainwalk,
            Self::Multikicker,
            Self::Mutate,
            Self::Myriad,
            Self::Nightbound,
            Self::Ninjutsu,
            Self::NonbasicLandwalk,
            Self::Offering,
            Self::Offspring,
            Self::Outlast,
            Self::Overload,
            Self::Partner,
            Self::PartnerWith,
            Self::Persist,
            Self::Phasing,
            Self::Plainscycling,
            Self::Plainswalk,
            Self::Poisonous,
            Self::Protection,
            Self::Prototype,
            Self::Provoke,
            Self::Prowess,
            Self::Prowl,
            Self::Rampage,
            Self::Ravenous,
            Self::Reach,
            Self::ReadAhead,
            Self::Rebound,
            Self::Reconfigure,
            Self::Recover,
            Self::Reinforce,
            Self::Renown,
            Self::Replicate,
            Self::Retrace,
            Self::Riot,
            Self::Ripple,
            Self::Saddle,
            Self::Scavenge,
            Self::Shadow,
            Self::Shroud,
            Self::Skulk,
            Self::Slivercycling,
            Self::Soulbond,
            Self::Soulshift,
            Self::Specialize,
            Self::Spectacle,
            Self::Splice,
            Self::SplitSecond,
            Self::Spree,
            Self::Squad,
            Self::Station,
            Self::Storm,
            Self::Sunburst,
            Self::Surge,
            Self::Suspend,
            Self::Swampcycling,
            Self::Swampwalk,
            Self::Toxic,
            Self::Training,
            Self::Trample,
            Self::Transfigure,
            Self::Transmute,
            Self::Tribute,
            Self::Typecycling,
            Self::UmbraArmor,
            Self::Undaunted,
            Self::Undying,
            Self::Unearth,
            Self::Unleash,
            Self::Vanishing,
            Self::Vigilance,
            Self::Ward,
            Self::Warp,
            Self::WebSlinging,
            Self::Wither,
            Self::Wizardcycling,
        ]
        .into_iter()
    }
}
